# Stage 7 — Fairness and Sensitive Feature Analysis

**Post-Test Fairness and Sensitive Feature Analysis.** Descriptive evidence for approved applications only; this is not a fairness or legal certification.

## 0. Stage Objective and Scope

Why: This section documents stage objective and scope from saved public or aggregate artifacts.

Conclusion: The Stage is bounded to frozen predictions and approved applications with observed outcomes.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [1]:
print('Artifact-only section contract: PASS')

Artifact-only section contract: PASS

## 1. Imports and Configuration

Why: This section documents imports and configuration from saved public or aggregate artifacts.

Conclusion: The saved imports and configuration evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [2]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

def show_json(path, keys=None):
    value=json.loads(Path(path).read_text(encoding='utf-8'))
    if keys: value={key:value.get(key) for key in keys}
    display(value)

def show_csv(path, n=10, query=None):
    value=pd.read_csv(path)
    if query: value=value.query(query)
    display(value.head(n))

print('Artifact-loading configuration: PASS')

Artifact-loading configuration: PASS

## 2. State Reconstruction

Why: This section documents state reconstruction from saved public or aggregate artifacts.

Conclusion: The saved state reconstruction evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [3]:
for name in ['TASK.md','PLAN.md','DECISIONS.md','LOG.md','AGENTS.md']:
    print(name, 'present=', Path(name).is_file())

TASK.md present= True
PLAN.md present= True
DECISIONS.md present= True
LOG.md present= True
AGENTS.md present= True

## 3. Stage 6 Verification and Handoff

Why: This section documents stage 6 verification and handoff from saved public or aggregate artifacts.

Conclusion: Stage 6 passed and handed off immutable evidence.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [4]:
show_json('artifacts/manifests/stage6/stage6_stage7_handoff.json')

{'candidate_metric_snapshot': {'path': 'artifacts/results/stage6/error_analysis/stage6_candidate_metric_snapshot.csv',
  'sha256': 'db09c011296b97981c0b202e569661dd244b851b72cc1e36d6043f4feaa759b5'},
 'created_at_utc': '2026-07-16T12:16:20.559164+00:00',
 'decile_analysis': {'path': 'artifacts/results/stage6/error_analysis/stage6_target_decile_analysis.csv',
  'sha256': 'c8b505e4c2f6920827046e58238549dd1573d41f87fc1aae5a01a08869d8606b'},
 'deep_with_sensitive_candidate_id': 'stage5c__realmlp__with_sensitive__test_evaluation',
 'deep_with_sensitive_prediction': {'path': 'artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_with_sensitive.csv',
  'sha256': 'b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99'},
 'deep_without_sensitive_candidate_id': 'stage5c__realmlp__without_sensitive__test_evaluation',
 'deep_without_sensitive_prediction': {'path': 'artifacts/predictions/stage5/posttest_evaluation/stage5c_test_predictions_without_sensitive.csv',
  'sha256': '972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5'},
 'ensemble_prediction_path': None,
 'ensemble_status': 'rejected',
 'error_distribution': {'path': 'artifacts/results/stage6/error_analysis/stage6_error_distribution_summary.csv',
  'sha256': '66d74099000613126ac2e1ed8623b988e147f2b1d6a1a577e2b2b8cd48540490'},
 'model_error_profile': {'path': 'artifacts/results/stage6/error_analysis/stage6_model_error_profile.json',
  'sha256': '7f59111f9206227af831775b20566934248e8f80e66234208daf3b795120c289'},
 'next_stage': 'Stage 7',
 'pairwise_disagreement': [{'path': 'artifacts/results/stage6/error_analysis/stage6_pairwise_disagreement_summary.csv',
   'sha256': 'cd9bc50ac75c02e429e1f11ded6af52b554fdb78e71542b22f701ebbc5fc5cf6'},
  {'path': 'artifacts/results/stage6/error_analysis/stage6_pairwise_disagreement_by_target_decile.csv',
   'sha256': 'dc2511c972871e6cb4112f763071b8680f64d88226bca5d81669865c287c639c'},
  {'path': 'artifacts/results/stage6/error_analysis/stage6_pairwise_error_delta_quantiles.csv',
   'sha256': 'd4a16fddec2dcef363b0e0b5750351efce7b13bf56a4e47b04c0fa30a034f2e8'}],
 'representative_case': {'path': 'artifacts/results/stage6/error_analysis/stage6_representative_cases.csv',
  'sha256': '63a300c49d1d3a991828b20729a507c35724de0cbbe93fd811e76b107ba45425'},
 'sensitive_accuracy_profile': {'path': 'artifacts/results/stage6/error_analysis/stage6_sensitive_accuracy_profile.csv',
  'sha256': '3daeb764c34469d078c4ba9c691f060e41a0ec42da33f1af05cafed0fa9142f0'},
 'stage4l_official_candidate_id': 'stage4l__blend__without_sensitive',
 'stage4l_prediction': {'path': 'artifacts/predictions/final_test/stage4l__blend__without_sensitive.csv',
  'sha256': '9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed'},
 'stage4l_remains_official': True,
 'stage5a_governance_exception_summary': 'Historical literal zero-Test-loading failed under an accepted procedural exception; zero Test rows entered learned preprocessing, fitting, selection, or Validation metrics.',
 'stage6_analysis_label': 'Post-Test Error Analysis',
 'stage6_loaded_group_labels': False,
 'stage6_loaded_source_features': False,
 'stage6_performed_model_selection': False,
 'stage6_status': 'PASS',
 'stage7_must_not_rerun_inference': True,
 'stage7_must_use_saved_predictions': True,
 'stage7_owns_subgroup_fairness_analysis': True,
 'stage7_safe_loader_rule': 'Load only required sensitive-group fields under an approved parser-boundary safe-loader plan.',
 'stage7_started': False,
 'stage8_candidate_row_artifact_path': 'artifacts/results/stage6/error_analysis/stage6_representative_cases.csv',
 'stage8_started': False,
 'stage_id': 'stage6',
 'tail_analysis': {'path': 'artifacts/results/stage6/error_analysis/stage6_target_tail_analysis.csv',
  'sha256': 'a81a16f800e0405bc5f81d678817fd129ef553d91d2b6e68e9510d121a49ecd6'},
 'target_hash': '889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a',
 'test_row_count': 99948,
 'test_row_id_hash': 'e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e',
 'under_over_analysis': {'path': 'artifacts/results/stage6/error_analysis/stage6_under_over_analysis.csv',
  'sha256': 'f725fb8e08ee0fb14b27c26ffe18c837e3b3273e34453f195a0d7e7556acfe5a'},
 'visualization_manifest': {'path': 'artifacts/manifests/stage6/stage6_visualization_manifest.json',
  'sha256': '8b282e56a3d159999c25cb071e7799373c8f8d9bbff4202856fc26af8c463cdc'},
 'worst_prediction_artifacts': [{'path': 'artifacts/results/stage6/error_analysis/stage6_worst_predictions.csv',
   'sha256': 'e6d7ddf9f26d4e9cfd2a3fce7f293545d699e9912f8fc854dadfbad79f3d0afc'},
  {'path': 'artifacts/results/stage6/error_analysis/stage6_worst_prediction_overlap.csv',
   'sha256': '353c5718e335817b42b380cfff6773be849bffb88a8117019d60611dc2e3632f'},
  {'path': 'artifacts/results/stage6/error_analysis/stage6_worst_prediction_union.csv',
   'sha256': 'f93a4ebe3d15aec369a11db7d55d1d6f0c337430d23b5e7b94f79e8de807691c'}]}

## 4. Fairness Scope and Approved-Only Limitation

Why: This section documents fairness scope and approved-only limitation from saved public or aggregate artifacts.

Conclusion: Approval and denial fairness are not assessed.

Limitation: The sample excludes denied and withdrawn applications.

In [5]:
print('Artifact-only section contract: PASS')

Artifact-only section contract: PASS

## 5. Frozen Candidates and Sensitive Fields

Why: This section documents frozen candidates and sensitive fields from saved public or aggregate artifacts.

Conclusion: Exactly three Candidates, eight sensitive fields, and one helper are frozen.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [6]:
print('Artifact-only section contract: PASS')

Artifact-only section contract: PASS

## 6. Protected File Baseline

Why: This section documents protected file baseline from saved public or aggregate artifacts.

Conclusion: The saved protected file baseline evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [7]:
show_json('artifacts/manifests/stage7/stage7_protected_hashes_before.json', keys=['status','protected_file_count','registry_prior_row_count'])

{'status': 'PASS',
 'protected_file_count': 756,
 'registry_prior_row_count': 370}

## 7. Pre-Fairness Freeze

Why: This section documents pre-fairness freeze from saved public or aggregate artifacts.

Conclusion: The saved pre-fairness freeze evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [8]:
show_json('artifacts/reports/stage7_prefairness_freeze.json', keys=['status','analysis_label','expected_test_row_count','sensitive_fields'])

{'status': 'PASS',
 'analysis_label': 'Post-Test Fairness and Sensitive Feature Analysis',
 'expected_test_row_count': 99948,
 'sensitive_fields': ['applicant_ethnicity_name',
  'co_applicant_ethnicity_name',
  'applicant_race_name_1',
  'co_applicant_race_name_1',
  'applicant_sex_name',
  'co_applicant_sex_name',
  'minority_population',
  'majority_minority_tract']}

## 8. Safe Sensitive-Row Loader

Why: This section documents safe sensitive-row loader from saved public or aggregate artifacts.

Conclusion: The parser-boundary sentinel passed before real access.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [9]:
show_json('artifacts/reports/stage7_safe_loader_sentinel.json')

{'checks': {'duplicate_ids_rejected': True,
  'excluded_sensitive_values_not_converted': True,
  'missing_ids_rejected': True,
  'only_allowed_ids_converted': True,
  'requested_order_preserved': True,
  'source_unchanged': True,
  'target_column_never_requested': True,
  'train_or_excluded_rows_not_materialized': True},
 'converter_call_counts': {'minority_population': 2},
 'created_at_utc': '2026-07-16T13:48:33.397358+00:00',
 'excluded_rows_converted': 0,
 'loader_path': 'stage5_safe_row_loader.py',
 'loader_sha256': 'f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0',
 'source_target_values_materialized': 0,
 'stage_id': 'stage7',
 'status': 'PASS',
 'synthetic_source_path': 'artifacts/reports/stage7_safe_loader_sentinel_source.csv'}

## 9. Sensitive Source Access Audit

Why: This section documents sensitive source access audit from saved public or aggregate artifacts.

Conclusion: One Test-only materialization produced zero Train rows and zero source targets.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [10]:
show_json('artifacts/reports/stage7_sensitive_source_access_audit.json', keys=['status','successful_source_materializations','test_rows_materialized','train_rows_materialized','source_target_values_materialized'])

{'status': 'PASS',
 'successful_source_materializations': 1,
 'test_rows_materialized': 99948,
 'train_rows_materialized': 0,
 'source_target_values_materialized': 0}

## 10. Group Label Policy and Coverage

Why: This section documents group label policy and coverage from saved public or aggregate artifacts.

Conclusion: Original categorical labels and frozen minority bins are retained with explicit evidence tiers.

Limitation: Administrative response labels are not inferred as identities.

In [11]:
show_csv('artifacts/results/stage7/fairness/stage7_group_coverage.csv', 12)

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason
0,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN
1,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN
2,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN
3,applicant_ethnicity_name,Not applicable,63,99948,0.000630,all_test_rows,True,suppressed_from_quantitative_comparison,True,n_below_100
4,co_applicant_ethnicity_name,__NO_CO_APPLICANT__,55455,99948,0.554839,coverage_only_has_co_applicant==0,True,primary,False,NaN
5,co_applicant_ethnicity_name,Hispanic or Latino,4427,44493,0.099499,has_co_applicant==1,False,primary,False,NaN
6,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,44493,0.162947,has_co_applicant==1,True,primary,False,NaN
7,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,44493,0.736161,has_co_applicant==1,False,primary,False,NaN
8,co_applicant_ethnicity_name,Not applicable,62,44493,0.001393,has_co_applicant==1,True,suppressed_from_quantitative_comparison,True,n_below_100
9,applicant_race_name_1,American Indian or Alaska Native,692,99948,0.006924,all_test_rows,False,primary,False,NaN
10,applicant_race_name_1,Asian,5683,99948,0.056860,all_test_rows,False,primary,False,NaN
11,applicant_race_name_1,Black or African American,7231,99948,0.072348,all_test_rows,False,primary,False,NaN

## 11. Prediction and Group Alignment

Why: This section documents prediction and group alignment from saved public or aggregate artifacts.

Conclusion: All three prediction files align to one sensitive record per Test row.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [12]:
show_json('artifacts/reports/stage7_group_prediction_alignment.json')

{'candidate_count': 3,
 'candidate_roles': {'stage4l__blend__without_sensitive': 'official_pre_registered_primary',
  'stage5c__realmlp__with_sensitive__test_evaluation': 'post_test_extension_accuracy_only',
  'stage5c__realmlp__without_sensitive__test_evaluation': 'post_test_extension'},
 'created_at_utc': '2026-07-16T13:48:35.189920+00:00',
 'every_test_row_has_one_sensitive_record': True,
 'exact_test_membership': True,
 'extra_source_rows': 0,
 'finite_predictions': True,
 'identical_targets': True,
 'original_target_scale': True,
 'prediction_file_count': 3,
 'prediction_hashes': {'stage4l__blend__without_sensitive': '9f9efa21d95a466b8271cd0db0a1e6b2c1ed2b5f1cabfbbb7e081137b9e4b7ed',
  'stage5c__realmlp__with_sensitive__test_evaluation': 'b4b11779a2d85209b2082c003ce79db2b657acd52c816c5e5345aaa6671f5e99',
  'stage5c__realmlp__without_sensitive__test_evaluation': '972eaa799c00eaa0ed486739636fb643f8f3e46e6890dc1964da542fd6108ee5'},
 'restricted_artifact_separate_from_predictions': True,
 'rows_per_candidate': 99948,
 'source_target_values_used': 0,
 'stage_id': 'stage7',
 'status': 'PASS',
 'target_hash': '889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a',
 'test_row_id_hash': 'e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e',
 'unique_row_ids': True}

## 12. Group Target Distribution

Why: This section documents group target distribution from saved public or aggregate artifacts.

Conclusion: The saved group target distribution evidence is present and follows the frozen Stage 7 contract.

Limitation: Different target mixes can explain part of a raw error gap.

In [13]:
show_csv('artifacts/results/stage7/fairness/stage7_group_target_distribution.csv', 10)

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason,mean_target,median_target,target_std,target_p10,target_p25,target_p75,target_p90,top_target_decile_share,top_five_percent_target_share,target_decile_counts_json
0,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,205.497174,176.0,153.158286,40.0,109.0,271.75,395.0,0.061805,0.019964,"{""1"": 1500, ""10"": 678, ""2"": 1158, ""3"": 1230, ""..."
1,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,269.096066,206.0,292.039664,65.0,124.0,331.00,504.0,0.127624,0.066314,"{""1"": 1463, ""10"": 1836, ""2"": 1414, ""3"": 1321, ..."
2,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,248.226717,199.0,231.118879,67.0,124.0,306.00,445.0,0.100136,0.051403,"{""1"": 7249, ""10"": 7463, ""2"": 7316, ""3"": 7396, ..."
3,applicant_ethnicity_name,Not applicable,63,99948,0.000630,all_test_rows,True,suppressed_from_quantitative_comparison,True,n_below_100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{}
4,co_applicant_ethnicity_name,Hispanic or Latino,4427,44493,0.099499,has_co_applicant==1,False,primary,False,NaN,239.789248,209.0,166.393031,71.0,130.5,317.00,432.0,0.092614,0.028010,"{""1"": 410, ""10"": 410, ""2"": 387, ""3"": 405, ""4"":..."
5,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,44493,0.162947,has_co_applicant==1,True,primary,False,NaN,305.937931,236.0,320.625262,77.0,148.0,376.00,572.0,0.166759,0.090207,"{""1"": 577, ""10"": 1209, ""2"": 523, ""3"": 545, ""4""..."
6,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,44493,0.736161,has_co_applicant==1,False,primary,False,NaN,283.344080,229.0,254.098616,80.0,145.0,350.00,517.0,0.134274,0.070739,"{""1"": 2534, ""10"": 4398, ""2"": 2414, ""3"": 2511, ..."
7,co_applicant_ethnicity_name,Not applicable,62,44493,0.001393,has_co_applicant==1,True,suppressed_from_quantitative_comparison,True,n_below_100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{}
8,applicant_race_name_1,American Indian or Alaska Native,692,99948,0.006924,all_test_rows,False,primary,False,NaN,194.011561,161.0,164.365023,31.1,100.0,245.00,371.9,0.067919,0.034682,"{""1"": 125, ""10"": 47, ""2"": 67, ""3"": 90, ""4"": 76..."
9,applicant_race_name_1,Asian,5683,99948,0.056860,all_test_rows,False,primary,False,NaN,347.255499,289.0,270.348754,120.0,188.0,424.00,613.0,0.216083,0.112265,"{""1"": 180, ""10"": 1228, ""2"": 271, ""3"": 320, ""4""..."

## 13. Single-Attribute Group Metrics

Why: This section documents single-attribute group metrics from saved public or aggregate artifacts.

Conclusion: Group error differences are reported with suppression and scope controls.

Limitation: A descriptive error gap does not identify its cause.

In [14]:
show_csv('artifacts/results/stage7/fairness/stage7_single_attribute_group_metrics.csv', 12)

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason,...,absolute_error_rate_above_50,absolute_error_rate_above_100,absolute_error_rate_above_200,top_target_decile_mae,top_five_percent_target_mae,prediction_to_actual_mean_ratio,mean_target,median_target,mean_prediction,median_prediction
0,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.277211,0.092160,0.018870,124.383672,204.209279,0.986844,205.497174,176.0,202.793592,177.729665
1,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.286418,0.095351,0.018687,122.433705,197.993782,0.996471,205.497174,176.0,204.772012,178.200945
2,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.286326,0.094531,0.018140,128.860431,211.329070,0.988009,205.497174,176.0,203.033077,179.661437
3,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.406715,0.180940,0.058251,212.443888,317.271201,0.954761,269.096066,206.0,256.922445,208.063715
4,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.413527,0.185319,0.059224,207.798313,307.509682,0.970938,269.096066,206.0,261.275525,207.624879
5,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.411511,0.184346,0.059502,210.162344,311.618480,0.975711,269.096066,206.0,262.559883,208.696561
6,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.388305,0.165117,0.046157,198.236628,284.052425,0.959582,248.226717,199.0,238.193875,199.263509
7,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.393941,0.166070,0.046599,194.440808,275.620080,0.968761,248.226717,199.0,240.472461,199.410003
8,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.392210,0.164661,0.046022,192.242694,272.124076,0.971846,248.226717,199.0,241.238252,200.506992
9,applicant_ethnicity_name,Not applicable,63,99948,0.000630,all_test_rows,True,suppressed_from_quantitative_comparison,True,n_below_100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,applicant_ethnicity_name,Not applicable,63,99948,0.000630,all_test_rows,True,suppressed_from_quantitative_comparison,True,n_below_100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,applicant_ethnicity_name,Not applicable,63,99948,0.000630,all_test_rows,True,suppressed_from_quantitative_comparison,True,n_below_100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 14. Applicant Identity Analysis

Why: This section documents applicant identity analysis from saved public or aggregate artifacts.

Conclusion: The saved applicant identity analysis evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [15]:
show_csv('artifacts/results/stage7/fairness/stage7_single_attribute_group_metrics.csv', 10, query="sensitive_field in ['applicant_race_name_1','applicant_ethnicity_name','applicant_sex_name'] and suppressed == False")

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason,...,absolute_error_rate_above_50,absolute_error_rate_above_100,absolute_error_rate_above_200,top_target_decile_mae,top_five_percent_target_mae,prediction_to_actual_mean_ratio,mean_target,median_target,mean_prediction,median_prediction
0,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.277211,0.092160,0.018870,124.383672,204.209279,0.986844,205.497174,176.0,202.793592,177.729665
1,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.286418,0.095351,0.018687,122.433705,197.993782,0.996471,205.497174,176.0,204.772012,178.200945
2,applicant_ethnicity_name,Hispanic or Latino,10970,99948,0.109757,all_test_rows,False,primary,False,NaN,...,0.286326,0.094531,0.018140,128.860431,211.329070,0.988009,205.497174,176.0,203.033077,179.661437
3,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.406715,0.180940,0.058251,212.443888,317.271201,0.954761,269.096066,206.0,256.922445,208.063715
4,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.413527,0.185319,0.059224,207.798313,307.509682,0.970938,269.096066,206.0,261.275525,207.624879
5,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,99948,0.143935,all_test_rows,True,primary,False,NaN,...,0.411511,0.184346,0.059502,210.162344,311.618480,0.975711,269.096066,206.0,262.559883,208.696561
6,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.388305,0.165117,0.046157,198.236628,284.052425,0.959582,248.226717,199.0,238.193875,199.263509
7,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.393941,0.166070,0.046599,194.440808,275.620080,0.968761,248.226717,199.0,240.472461,199.410003
8,applicant_ethnicity_name,Not Hispanic or Latino,74529,99948,0.745678,all_test_rows,False,primary,False,NaN,...,0.392210,0.164661,0.046022,192.242694,272.124076,0.971846,248.226717,199.0,241.238252,200.506992
24,applicant_race_name_1,American Indian or Alaska Native,692,99948,0.006924,all_test_rows,False,primary,False,NaN,...,0.287572,0.091040,0.024566,NaN,NaN,0.976918,194.011561,161.0,189.533476,168.813597

## 15. Co-Applicant Identity Analysis

Why: This section documents co-applicant identity analysis from saved public or aggregate artifacts.

Conclusion: The saved co-applicant identity analysis evidence is present and follows the frozen Stage 7 contract.

Limitation: Co-applicant identity metrics apply only when a co-applicant exists.

In [16]:
show_csv('artifacts/results/stage7/fairness/stage7_single_attribute_group_metrics.csv', 10, query="sensitive_field in ['co_applicant_race_name_1','co_applicant_ethnicity_name','co_applicant_sex_name'] and suppressed == False")

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason,...,absolute_error_rate_above_50,absolute_error_rate_above_100,absolute_error_rate_above_200,top_target_decile_mae,top_five_percent_target_mae,prediction_to_actual_mean_ratio,mean_target,median_target,mean_prediction,median_prediction
12,co_applicant_ethnicity_name,Hispanic or Latino,4427,44493,0.099499,has_co_applicant==1,False,primary,False,NaN,...,0.334086,0.119494,0.023492,119.624263,217.947106,0.991892,239.789248,209.0,237.845073,212.420987
13,co_applicant_ethnicity_name,Hispanic or Latino,4427,44493,0.099499,has_co_applicant==1,False,primary,False,NaN,...,0.350350,0.123560,0.023040,117.481261,208.538113,1.001952,239.789248,209.0,240.257359,214.199319
14,co_applicant_ethnicity_name,Hispanic or Latino,4427,44493,0.099499,has_co_applicant==1,False,primary,False,NaN,...,0.347414,0.120849,0.023492,123.249296,217.499335,0.986670,239.789248,209.0,236.592976,212.381160
15,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,44493,0.162947,has_co_applicant==1,True,primary,False,NaN,...,0.455724,0.222621,0.077379,212.576763,306.255029,0.948891,305.937931,236.0,290.301894,238.392001
16,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,44493,0.162947,has_co_applicant==1,True,primary,False,NaN,...,0.463310,0.226483,0.076966,208.467658,299.598791,0.964344,305.937931,236.0,295.029392,238.871088
17,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,44493,0.162947,has_co_applicant==1,True,primary,False,NaN,...,0.461379,0.223586,0.076414,209.040925,301.100534,0.972083,305.937931,236.0,297.396968,239.604217
18,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,44493,0.736161,has_co_applicant==1,False,primary,False,NaN,...,0.446022,0.206967,0.063626,197.788023,280.070739,0.956936,283.344080,229.0,271.142065,228.977652
19,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,44493,0.736161,has_co_applicant==1,False,primary,False,NaN,...,0.452433,0.208188,0.063443,195.148578,273.097355,0.965234,283.344080,229.0,273.493210,229.691614
20,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,44493,0.736161,has_co_applicant==1,False,primary,False,NaN,...,0.448922,0.205288,0.062801,193.194272,270.743694,0.968730,283.344080,229.0,274.483906,230.759040
45,co_applicant_race_name_1,American Indian or Alaska Native,239,44493,0.005372,has_co_applicant==1,False,limited_evidence,False,NaN,...,0.364017,0.129707,0.025105,NaN,NaN,0.974573,230.213389,187.0,224.359860,194.692520

## 16. Tract and Minority-Population Analysis

Why: This section documents tract and minority-population analysis from saved public or aggregate artifacts.

Conclusion: The saved tract and minority-population analysis evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [17]:
show_csv('artifacts/results/stage7/fairness/stage7_single_attribute_group_metrics.csv', 10, query="sensitive_field in ['minority_population','majority_minority_tract'] and suppressed == False")

,sensitive_field,group_label,n,scope_n,group_share,eligibility_scope,is_non_substantive,evidence_tier,suppressed,suppression_reason,...,absolute_error_rate_above_50,absolute_error_rate_above_100,absolute_error_rate_above_200,top_target_decile_mae,top_five_percent_target_mae,prediction_to_actual_mean_ratio,mean_target,median_target,mean_prediction,median_prediction
90,minority_population,"[0,20)",38360,99948,0.383800,all_test_rows,False,primary,False,NaN,...,0.384802,0.160401,0.045021,246.520871,334.984213,0.947118,234.723697,188.0,222.311096,188.802394
91,minority_population,"[0,20)",38360,99948,0.383800,all_test_rows,False,primary,False,NaN,...,0.391319,0.161496,0.046142,241.837467,326.349178,0.956102,234.723697,188.0,224.419700,188.239625
92,minority_population,"[0,20)",38360,99948,0.383800,all_test_rows,False,primary,False,NaN,...,0.389416,0.159411,0.044995,238.175243,320.520685,0.969509,234.723697,188.0,227.566684,191.345590
93,minority_population,"[20,40)",29053,99948,0.290681,all_test_rows,False,primary,False,NaN,...,0.397136,0.175128,0.054900,212.054602,295.966707,0.961065,266.461054,207.0,256.086481,209.256114
94,minority_population,"[20,40)",29053,99948,0.290681,all_test_rows,False,primary,False,NaN,...,0.401921,0.176058,0.053523,208.160298,287.843869,0.971875,266.461054,207.0,258.966725,209.179516
95,minority_population,"[20,40)",29053,99948,0.290681,all_test_rows,False,primary,False,NaN,...,0.400819,0.175885,0.054555,208.276012,287.357855,0.971382,266.461054,207.0,258.835471,208.512721
96,minority_population,"[40,50)",9180,99948,0.091848,all_test_rows,False,primary,False,NaN,...,0.389869,0.163290,0.043573,151.484389,221.633854,0.969370,262.908497,216.0,254.855646,215.913170
97,minority_population,"[40,50)",9180,99948,0.091848,all_test_rows,False,primary,False,NaN,...,0.394553,0.165686,0.046623,146.471764,207.846776,0.980506,262.908497,216.0,257.783437,216.097620
98,minority_population,"[40,50)",9180,99948,0.091848,all_test_rows,False,primary,False,NaN,...,0.395861,0.163072,0.045098,149.002644,214.364457,0.970291,262.908497,216.0,255.097736,215.055743
99,minority_population,"[50,60)",6167,99948,0.061702,all_test_rows,False,primary,False,NaN,...,0.376844,0.156964,0.042646,156.846827,222.739027,0.966119,254.967407,205.0,246.328975,204.449988

## 17. Target-Decile and Standardized Metrics

Why: This section documents target-decile and standardized metrics from saved public or aggregate artifacts.

Conclusion: Saved target deciles support descriptive target-mix standardization where every decile has at least 20 rows.

Limitation: Standardization adjusts observed target mix only; it is not causal.

In [18]:
show_csv('artifacts/results/stage7/fairness/stage7_target_standardized_metrics.csv', 10, query='standardized_eligible == True')

,sensitive_field,group_label,candidate_id,n,standardized_eligible,raw_mae,standardized_mae,standardized_minus_raw_mae,standardized_wape,decile_support_json,availability_status,standardization_weights
0,applicant_ethnicity_name,Hispanic or Latino,stage4l__blend__without_sensitive,10970,True,42.280136,47.022598,4.742463,NaN,"{""1"": 1500, ""10"": 678, ""2"": 1158, ""3"": 1230, ""...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
1,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__with_sensitive__test_evaluation,10970,True,42.838026,47.738876,4.900850,NaN,"{""1"": 1500, ""10"": 678, ""2"": 1158, ""3"": 1230, ""...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
2,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__without_sensitive__test_eval...,10970,True,42.991402,47.645792,4.654390,NaN,"{""1"": 1500, ""10"": 678, ""2"": 1158, ""3"": 1230, ""...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
6,applicant_ethnicity_name,Not Hispanic or Latino,stage4l__blend__without_sensitive,74529,True,62.681509,62.496229,-0.185279,NaN,"{""1"": 7249, ""10"": 7463, ""2"": 7316, ""3"": 7396, ...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
7,applicant_ethnicity_name,Not Hispanic or Latino,stage5c__realmlp__with_sensitive__test_evaluation,74529,True,62.846309,62.656389,-0.189920,NaN,"{""1"": 7249, ""10"": 7463, ""2"": 7316, ""3"": 7396, ...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
8,applicant_ethnicity_name,Not Hispanic or Latino,stage5c__realmlp__without_sensitive__test_eval...,74529,True,63.279471,63.088297,-0.191174,NaN,"{""1"": 7249, ""10"": 7463, ""2"": 7316, ""3"": 7396, ...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
12,applicant_race_name_1,American Indian or Alaska Native,stage4l__blend__without_sensitive,692,True,43.887797,50.744025,6.856228,NaN,"{""1"": 125, ""10"": 47, ""2"": 67, ""3"": 90, ""4"": 76...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
13,applicant_race_name_1,American Indian or Alaska Native,stage5c__realmlp__with_sensitive__test_evaluation,692,True,45.790615,53.100478,7.309864,NaN,"{""1"": 125, ""10"": 47, ""2"": 67, ""3"": 90, ""4"": 76...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
14,applicant_race_name_1,American Indian or Alaska Native,stage5c__realmlp__without_sensitive__test_eval...,692,True,45.278723,52.146052,6.867329,NaN,"{""1"": 125, ""10"": 47, ""2"": 67, ""3"": 90, ""4"": 76...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."
15,applicant_race_name_1,Asian,stage4l__blend__without_sensitive,5683,True,82.035091,64.171419,-17.863672,NaN,"{""1"": 180, ""10"": 1228, ""2"": 271, ""3"": 320, ""4""...",available,"{""1"": 0.10226317685196303, ""10"": 0.09986192820..."

## 18. Group Disparity Summary

Why: This section documents group disparity summary from saved public or aggregate artifacts.

Conclusion: The saved group disparity summary evidence is present and follows the frozen Stage 7 contract.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [19]:
show_csv('artifacts/results/stage7/fairness/stage7_group_disparity_summary.csv', 12)

,candidate_id,sensitive_field,eligible_group_count,largest_eligible_group,best_mae_group,worst_mae_group,worst_minus_best_mae_gap,worst_to_best_mae_ratio,maximum_group_minus_overall_mae,minimum_group_minus_overall_mae,worst_minus_best_wape_gap,worst_minus_best_p90_error_gap,maximum_absolute_mean_signed_error,mean_signed_error_spread,underprediction_rate_spread,target_standardized_mae_gap,data_coverage_percentage,reference_is_legally_privileged
0,stage4l__blend__without_sensitive,applicant_ethnicity_name,2,Not Hispanic or Latino,Hispanic or Latino,Not Hispanic or Latino,20.401373,1.482529,1.169877,-19.231495,0.046772,38.357173,10.032842,7.329260,0.005289,15.473631,85.543483,False
1,stage4l__blend__without_sensitive,co_applicant_ethnicity_name,2,Not Hispanic or Latino,Hispanic or Latino,Not Hispanic or Latino,23.281541,1.468088,11.507404,-11.774137,0.050283,47.050781,12.202015,10.257841,0.015811,17.017383,83.565954,False
2,stage4l__blend__without_sensitive,applicant_race_name_1,4,White,Black or African American,Asian,38.863224,1.900198,20.523460,-18.339764,0.032664,88.131638,18.543010,14.064926,0.060380,13.427394,84.210790,False
3,stage4l__blend__without_sensitive,co_applicant_race_name_1,3,White,Black or African American,Asian,39.687590,1.747230,31.288904,-8.398686,0.038817,89.170858,21.744706,12.409199,0.056755,13.444114,81.502708,False
4,stage4l__blend__without_sensitive,applicant_sex_name,2,Male,Female,Male,12.983290,1.251484,3.098265,-9.885025,0.003345,22.981300,12.584216,10.618643,0.032986,4.308058,90.810221,False
5,stage4l__blend__without_sensitive,co_applicant_sex_name,2,Female,Male,Female,6.431534,1.097922,10.600408,4.168873,0.004804,7.683243,14.338605,13.765328,0.050697,1.015788,89.438788,False
6,stage4l__blend__without_sensitive,minority_population,6,"[0,20)","[80,100]","[20,40)",22.001072,1.481991,6.135712,-15.865360,0.048964,34.783206,12.412601,11.387958,0.035773,19.112979,100.000000,False
7,stage4l__blend__without_sensitive,majority_minority_tract,2,Not majority minority,Majority minority,Not majority minority,11.986586,1.229075,2.800924,-9.185662,0.034188,17.423603,11.117008,6.688165,0.008298,12.432790,100.000000,False
8,stage5c__realmlp__without_sensitive__test_eval...,applicant_ethnicity_name,2,Not Hispanic or Latino,Hispanic or Latino,Not Hispanic or Latino,20.288069,1.471910,1.119726,-19.168343,0.045719,37.500179,7.754256,7.029094,0.003193,15.442504,85.543483,False
9,stage5c__realmlp__without_sensitive__test_eval...,co_applicant_ethnicity_name,2,Not Hispanic or Latino,Hispanic or Latino,Not Hispanic or Latino,23.253202,1.461315,11.499836,-11.753366,0.049754,46.484589,9.850870,10.318981,0.018282,17.152202,83.565954,False
10,stage5c__realmlp__without_sensitive__test_eval...,applicant_race_name_1,4,White,Black or African American,Asian,36.413154,1.826414,18.315067,-18.098087,0.031243,78.290706,15.793639,12.485017,0.065403,11.820177,84.210790,False
11,stage5c__realmlp__without_sensitive__test_eval...,co_applicant_race_name_1,3,White,Black or African American,Asian,36.917019,1.678082,29.200580,-7.716438,0.036090,80.717468,18.321742,12.489625,0.043231,12.093219,81.502708,False

## 19. Pairwise Group Comparisons

Why: This section documents pairwise group comparisons from saved public or aggregate artifacts.

Conclusion: The saved pairwise group comparisons evidence is present and follows the frozen Stage 7 contract.

Limitation: Candidate-pair differences do not select a model.

In [20]:
show_csv('artifacts/results/stage7/fairness/stage7_pairwise_group_differences.csv', 10)

,pair_id,first_candidate_id,second_candidate_id,sensitive_field,group_label,n,evidence_tier,is_non_substantive,model_selection_performed,mae_difference,...,wape_difference,p90_absolute_error_difference,mean_signed_error_raw_difference,absolute_signed_bias_difference,underprediction_rate_difference,first_candidate_lower_error_rate,second_candidate_lower_error_rate,tie_rate,mean_prediction_difference,median_prediction_difference
0,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_ethnicity_name,Hispanic or Latino,10970,primary,False,False,-0.153376,...,-0.000746,-0.251180,-1.738935,1.738935,0.000182,0.502552,0.497448,0.000000,-1.738935,1.460492
1,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_ethnicity_name,"Information not provided by applicant in mail,...",14386,primary,True,False,0.023719,...,0.000088,-0.846214,1.284358,-1.284358,-0.002989,0.503823,0.496107,0.000070,1.284358,1.071683
2,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_ethnicity_name,Not Hispanic or Latino,74529,primary,False,False,-0.433161,...,-0.001745,-1.268619,0.765791,-0.765791,-0.002885,0.507682,0.492265,0.000054,0.765791,1.096988
3,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,co_applicant_ethnicity_name,Hispanic or Latino,4427,primary,False,False,-0.389216,...,-0.001623,-0.272770,-3.664384,2.728161,0.015812,0.502146,0.497854,0.000000,-3.664384,-1.818158
4,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,co_applicant_ethnicity_name,"Information not provided by applicant in mail,...",7250,primary,True,False,-0.295741,...,-0.000967,1.039945,2.367576,-2.367576,-0.007310,0.513931,0.485931,0.000138,2.367576,0.733129
5,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,co_applicant_ethnicity_name,Not Hispanic or Latino,32754,primary,False,False,-0.428179,...,-0.001511,-0.637499,0.990696,-0.990696,-0.002412,0.505770,0.494230,0.000000,0.990696,1.067426
6,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_race_name_1,American Indian or Alaska Native,692,primary,False,False,0.511892,...,0.002638,0.589661,-1.840921,1.840921,0.010116,0.494220,0.505780,0.000000,-1.840921,-1.378446
7,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_race_name_1,Asian,5683,primary,False,False,-0.994308,...,-0.002863,-1.589441,9.017804,-9.017804,-0.051029,0.519972,0.480028,0.000000,9.017804,11.352770
8,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_race_name_1,Black or African American,7231,primary,False,False,-0.523167,...,-0.002664,-2.023292,1.003862,-1.003862,-0.004702,0.513484,0.486516,0.000000,1.003862,1.537456
9,stage7__deep_with_minus_deep_without,stage5c__realmlp__with_sensitive__test_evaluation,stage5c__realmlp__without_sensitive__test_eval...,applicant_race_name_1,"Information not provided by applicant in mail,...",15270,primary,True,False,-0.084719,...,-0.000315,-0.697338,1.055928,-1.055928,-0.001768,0.504715,0.495219,0.000065,1.055928,1.426686

## 20. Bootstrap Uncertainty

Why: This section documents bootstrap uncertainty from saved public or aggregate artifacts.

Conclusion: Paired descriptive intervals use 500 within-group resamples and seed 42.

Limitation: Intervals are descriptive and no p-values or multiple-testing claims are made.

In [21]:
show_csv('artifacts/results/stage7/fairness/stage7_group_bootstrap_intervals.csv', 10)

,sensitive_field,group_label,candidate_id,pair_id,interval_type,metric,n,point_estimate,ci_lower_95,ci_upper_95,bootstrap_repetitions,bootstrap_seed,paired_within_group,inferential_status
0,applicant_ethnicity_name,Hispanic or Latino,stage4l__blend__without_sensitive,NaN,candidate_metric,mae,10970,42.273438,41.327578,43.209587,500,42,True,descriptive_interval_no_p_value
1,applicant_ethnicity_name,Hispanic or Latino,stage4l__blend__without_sensitive,NaN,candidate_metric,signed_error,10970,-2.696822,-4.111295,-1.286040,500,42,True,descriptive_interval_no_p_value
2,applicant_ethnicity_name,Hispanic or Latino,stage4l__blend__without_sensitive,NaN,candidate_metric,underprediction_rate,10970,0.514101,0.505326,0.523206,500,42,True,descriptive_interval_no_p_value
3,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__without_sensitive__test_eval...,NaN,candidate_metric,mae,10970,42.986542,42.033402,43.931051,500,42,True,descriptive_interval_no_p_value
4,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__without_sensitive__test_eval...,NaN,candidate_metric,signed_error,10970,-0.704958,-2.067788,0.693577,500,42,True,descriptive_interval_no_p_value
5,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__without_sensitive__test_eval...,NaN,candidate_metric,underprediction_rate,10970,0.500921,0.491700,0.509711,500,42,True,descriptive_interval_no_p_value
6,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__with_sensitive__test_evaluation,NaN,candidate_metric,mae,10970,42.825475,41.827748,43.819404,500,42,True,descriptive_interval_no_p_value
7,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__with_sensitive__test_evaluation,NaN,candidate_metric,signed_error,10970,-2.443169,-3.938577,-1.068435,500,42,True,descriptive_interval_no_p_value
8,applicant_ethnicity_name,Hispanic or Latino,stage5c__realmlp__with_sensitive__test_evaluation,NaN,candidate_metric,underprediction_rate,10970,0.501149,0.491413,0.510349,500,42,True,descriptive_interval_no_p_value
9,applicant_ethnicity_name,Hispanic or Latino,NaN,stage7__deep_with_minus_deep_without,paired_candidate_difference,mae_difference,10970,-0.161067,-0.498567,0.162892,500,42,True,descriptive_interval_no_p_value

## 21. Intersectional Analysis

Why: This section documents intersectional analysis from saved public or aggregate artifacts.

Conclusion: Only the three frozen two-way intersections are reported.

Limitation: Sparse intersections are suppressed and cannot be ranked.

In [22]:
show_csv('artifacts/results/stage7/fairness/stage7_intersectional_metrics.csv', 12, query='suppressed == False')

,intersection_id,left_field,right_field,intersection_label,candidate_id,n,evidence_tier,is_non_substantive,suppressed,suppression_reason,mean_target,mae,rmse,wape,signed_error,absolute_mean_signed_error,underprediction_rate,p90_absolute_error
0,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,American Indian or Alaska Native x Female,stage4l__blend__without_sensitive,225,limited_evidence,False,False,NaN,177.155556,38.739581,63.243501,0.218676,0.293248,0.293248,0.493333,73.735245
2,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,American Indian or Alaska Native x Male,stage4l__blend__without_sensitive,455,limited_evidence,False,False,NaN,202.417582,45.877365,89.293725,0.226647,-7.656179,7.656179,0.501099,94.867996
3,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Asian x Female,stage4l__blend__without_sensitive,1766,primary,False,False,NaN,311.955266,78.903901,172.649505,0.252933,-13.785594,13.785594,0.537939,165.645964
5,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Asian x Male,stage4l__blend__without_sensitive,3900,primary,False,False,NaN,362.803590,83.238998,132.283018,0.229433,-20.315817,20.315817,0.563333,182.683894
6,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Black or African American x Female,stage4l__blend__without_sensitive,3175,primary,False,False,NaN,176.902362,38.462134,59.129422,0.217420,-0.368486,0.368486,0.488504,86.474210
8,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Black or African American x Male,stage4l__blend__without_sensitive,4025,primary,False,False,NaN,211.849441,46.984386,80.042954,0.221782,-9.681530,9.681530,0.517019,101.455241
9,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,"Information not provided by applicant in mail,...",stage4l__blend__without_sensitive,2068,primary,True,False,NaN,232.811412,54.330000,86.301155,0.233365,-0.605560,0.605560,0.471954,124.595160
10,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,"Information not provided by applicant in mail,...",stage4l__blend__without_sensitive,8848,primary,True,False,NaN,266.720502,70.572943,155.160945,0.264595,-11.594536,11.594536,0.503730,143.823725
11,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,"Information not provided by applicant in mail,...",stage4l__blend__without_sensitive,4349,primary,True,False,NaN,290.461255,71.834050,169.234970,0.247310,-14.985950,14.985950,0.527708,150.630477
13,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Native Hawaiian or Other Pacific Islander x Fe...,stage4l__blend__without_sensitive,175,limited_evidence,False,False,NaN,256.451429,54.251262,87.952360,0.211546,-4.379548,4.379548,0.520000,120.214186
15,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,Native Hawaiian or Other Pacific Islander x Male,stage4l__blend__without_sensitive,299,limited_evidence,False,False,NaN,297.762542,63.063714,126.022549,0.211792,-24.071187,24.071187,0.568562,134.687437
20,applicant_race_x_applicant_sex,applicant_race_name_1,applicant_sex_name,White x Female,stage4l__blend__without_sensitive,21056,primary,False,False,NaN,204.859138,51.175811,99.526942,0.249810,-1.345770,1.345770,0.483283,114.212948

## 22. Accuracy Versus Disparity Trade-Off

Why: This section documents accuracy versus disparity trade-off from saved public or aggregate artifacts.

Conclusion: Overall accuracy changes and group-disparity changes do not always move together.

Limitation: Adding sensitive Features can improve some groups and worsen others without proving causation.

In [23]:
show_csv('artifacts/results/stage7/fairness/stage7_accuracy_disparity_tradeoff.csv', 12)

,sensitive_field,overall_mae_change_with_minus_without,worst_group_mae_change,best_group_mae_change,raw_mae_gap_change,target_standardized_mae_gap_change,maximum_absolute_signed_bias_change,underprediction_rate_spread_change,primary_groups_improved,primary_groups_worsened,primary_groups_approximately_unchanged,test_rows_lower_absolute_error_percentage,test_rows_higher_absolute_error_percentage,test_rows_approximately_unchanged_percentage,interpretation
0,applicant_ethnicity_name,-0.338631,-0.433161,-0.153376,-0.279785,-0.524991,-0.765791,-0.003067,2,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
1,co_applicant_ethnicity_name,-0.338631,-0.428179,-0.389216,-0.038963,0.013008,-0.990696,-0.018224,2,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
2,applicant_race_name_1,-0.338631,-0.994308,-0.523167,-0.471141,1.658323,-8.949316,-0.051440,3,1,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
3,co_applicant_race_name_1,-0.338631,-0.665369,-0.240151,-0.425218,0.729360,-8.443158,-0.024688,3,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
4,applicant_sex_name,-0.338631,-0.368260,-0.297882,-0.070378,-0.330119,-2.590682,-0.024623,2,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
5,co_applicant_sex_name,-0.338631,-0.338657,-0.568832,0.230175,0.764162,-2.842448,-0.045050,2,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
6,minority_population,-0.338631,-0.185550,-0.702094,0.516544,0.397586,-2.493236,-0.021221,6,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...
7,majority_minority_tract,-0.338631,-0.245673,-0.643489,0.397816,0.404974,-1.204422,-0.015042,2,0,0,50.656341,49.338656,0.005003,Better overall MAE does not guarantee smaller ...

## 23. Proxy-Feature Limitations

Why: This section documents proxy-feature limitations from saved public or aggregate artifacts.

Conclusion: Removing named sensitive fields does not prove that proxy effects are absent.

Limitation: No protected-attribute prediction model was trained.

In [24]:
show_json('artifacts/results/stage7/fairness/stage7_proxy_feature_limitations.json')

{'assessment_label': 'descriptive_disparities_reported',
 'causal_proxy_conclusion': False,
 'fairness_certification': False,
 'feature_inventory': {'path': 'artifacts/data_contract/feature_inventory.csv',
  'sha256': '2a4f85d8862d9ea3d49b85665f0650a3094111d0b08849b5908afed00238ae0e',
  'size_bytes': 4735},
 'inspected_saved_schema_only': True,
 'interpretation': ['These saved-schema fields may be associated with sensitive attributes, but this Stage does not prove that they encode or reproduce a protected identity.',
  'Removing explicit sensitive Features does not guarantee absence of proxy effects.',
  'No protected-attribute prediction model was trained and no causal proxy conclusion was made.',
  'Feature deletion is not recommended from this descriptive evidence alone.'],
 'legal_or_compliance_certification': False,
 'potential_proxy_categories': ['state',
  'county',
  'MSA or MD area',
  'tract income level',
  'region',
  'applicant income',
  'area income',
  'lender or respondent identity',
  'property characteristics',
  'loan characteristics'],
 'protected_attribute_prediction_model_trained': False,
 'stage_id': 'stage7',
 'status': 'PASS'}

## 24. Fairness and Governance Risk Register

Why: This section documents fairness and governance risk register from saved public or aggregate artifacts.

Conclusion: Fourteen governance risks remain documented for later decision work.

Limitation: Governance severity is not a fairness certification.

In [25]:
show_csv('artifacts/results/stage7/fairness/stage7_fairness_risk_register.csv', 10)

,risk_id,risk_description,evidence,scope,severity,mitigation,remaining_limitation,owner_stage
0,stage7_risk_01,Approved-applications-only selection,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,high,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
1,stage7_risk_02,Target may reflect historical processes,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,high,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
2,stage7_risk_03,Missing or not-provided sensitive labels,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,medium,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
3,stage7_risk_04,Co-applicant availability differences,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,medium,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
4,stage7_risk_05,Small and sparse groups,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,medium,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
5,stage7_risk_06,Intersectional sparsity,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,medium,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
6,stage7_risk_07,Potential proxy Features,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,high,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
7,stage7_risk_08,Post-Test analysis status,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,high,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
8,stage7_risk_09,No deployment decision context,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,high,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance
9,stage7_risk_10,Unknown relative cost of underprediction and o...,Saved aggregate Stage 7 evidence and frozen go...,approved applications with observed Test outco...,medium,"Retain frozen suppression, privacy, scope, and...",Descriptive evidence cannot remove this govern...,Stage 8 or deployment governance

## 25. Stage 8 Representative Cases

Why: This section documents stage 8 representative cases from saved public or aggregate artifacts.

Conclusion: The saved stage 8 representative cases evidence is present and follows the frozen Stage 7 contract.

Limitation: Public cases contain no row-level sensitive labels.

In [26]:
show_csv('artifacts/results/stage7/fairness/stage7_representative_cases_public.csv', 8)

,case_type,case_rank,row_id,y_true,candidate_1_id,candidate_1_prediction,candidate_1_signed_error,candidate_1_absolute_error,candidate_2_id,candidate_2_prediction,...,candidate_3_prediction,candidate_3_signed_error,candidate_3_absolute_error,target_decile,top_decile_membership,top_five_percent_membership,future_use,analysis_label,stage7_use,sensitive_labels_in_public_file
0,common_large_error,1,436983,10000.0,stage4l__blend__without_sensitive,2754.858279,-7245.141721,7245.141721,stage5c__realmlp__without_sensitive__test_eval...,2550.619405,...,2628.611201,-7371.388799,7371.388799,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
1,common_large_error,2,215439,9000.0,stage4l__blend__without_sensitive,2657.226436,-6342.773564,6342.773564,stage5c__realmlp__without_sensitive__test_eval...,3446.075476,...,3258.375267,-5741.624733,5741.624733,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
2,common_large_error,3,19494,6500.0,stage4l__blend__without_sensitive,1042.941263,-5457.058737,5457.058737,stage5c__realmlp__without_sensitive__test_eval...,676.656731,...,575.005644,-5924.994356,5924.994356,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
3,common_large_error,4,353835,7000.0,stage4l__blend__without_sensitive,2023.554443,-4976.445557,4976.445557,stage5c__realmlp__without_sensitive__test_eval...,2451.559252,...,2125.988431,-4874.011569,4874.011569,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
4,common_large_error,5,170281,6000.0,stage4l__blend__without_sensitive,1523.649186,-4476.350814,4476.350814,stage5c__realmlp__without_sensitive__test_eval...,1635.680610,...,1327.067710,-4672.932290,4672.932290,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
5,deep_with_improves_over_without,1,299724,3000.0,stage4l__blend__without_sensitive,2053.769034,-946.230966,946.230966,stage5c__realmlp__without_sensitive__test_eval...,1808.759384,...,2699.837767,-300.162233,300.162233,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
6,deep_with_improves_over_without,2,196215,450.0,stage4l__blend__without_sensitive,1127.986234,677.986234,677.986234,stage5c__realmlp__without_sensitive__test_eval...,1548.822233,...,791.050196,341.050196,341.050196,10,True,False,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False
7,deep_with_improves_over_without,3,304158,3203.0,stage4l__blend__without_sensitive,1487.457714,-1715.542286,1715.542286,stage5c__realmlp__without_sensitive__test_eval...,1085.997572,...,1820.413021,-1382.586979,1382.586979,10,True,True,Stage 8 local explanation candidate,Post-Test Error Analysis,bounded_stage8_explanation_candidate,False

## 26. Stage 7 Visualizations

Why: This section documents stage 7 visualizations from saved public or aggregate artifacts.

Conclusion: The saved stage 7 visualizations evidence is present and follows the frozen Stage 7 contract.

Limitation: Figures display eligible aggregates only.

In [27]:
show_json('artifacts/manifests/stage7/stage7_visualization_manifest.json', keys=['status','figure_count'])

{'status': 'PASS', 'figure_count': 15}

## 27. Registry Update

Why: This section documents registry update from saved public or aggregate artifacts.

Conclusion: Eight deterministic Registry rows are present and the second action is REUSED.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [28]:
show_csv('artifacts/results/stage7/fairness/stage7_registry_rows.csv', 8)

,experiment_id,timestamp_utc,model_family,model_name,sensitive_mode,feature_set,target_mode,evaluation_stage,fold_number,training_row_count,...,wape_percent,mean_signed_error,p90_absolute_error,negative_prediction_rate,fit_time_seconds,prediction_time_seconds,status,notes,model_artifact_path,prediction_artifact_path
0,stage7__stage4l_primary__group_profile,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
1,stage7__realmlp_without_sensitive__group_profile,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
2,stage7__realmlp_with_sensitive__group_profile,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
3,stage7__deep_with_vs_without__group_comparison,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
4,stage7__deep_without_vs_stage4l__group_comparison,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
5,stage7__intersectional_summary,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
6,stage7__fairness_governance_summary,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN
7,stage7__stage8_handoff,2026-07-16T13:24:07.951142+00:00,frozen_prediction_fairness_analysis,descriptive_group_analysis,analysis_only,saved_predictions_and_restricted_sensitive_labels,original,stage7_post_test_fairness_analysis,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,success,Post-Test Fairness and Sensitive Feature Analy...,NaN,NaN

## 28. Stage 8 Handoff

Why: This section documents stage 8 handoff from saved public or aggregate artifacts.

Conclusion: Stage 8 may use saved artifacts but must not alter models or expose restricted labels.

Limitation: This evidence is descriptive and does not establish a causal or legal conclusion.

In [29]:
show_json('artifacts/manifests/stage7/stage7_stage8_handoff.json', keys=['stage7_status','fairness_assessment_status','stage4l_remains_official','model_selection_performed','next_stage'])

{'stage7_status': 'PASS',
 'fairness_assessment_status': 'descriptive_disparities_reported',
 'stage4l_remains_official': True,
 'model_selection_performed': False,
 'next_stage': 'Stage 8'}

## 29. Independent Review and Verification

Why: This section documents independent review and verification from saved public or aggregate artifacts.

Conclusion: Independent review, protected recheck, and final Verification are displayed directly.

Limitation: Review cannot turn this descriptive Stage into a legal assessment.

In [30]:
print(Path('artifacts/reports/stage7_reviewer.md').read_text(encoding='utf-8')); show_json('artifacts/reports/stage7_protected_recheck.json'); show_json('artifacts/reports/stage7_verification.json')

# Stage 7 Independent Reviewer

## Final Review Status

- Review cycle: 2 of 2
- Stage reviewed: Stage 7 — Fairness and Sensitive Feature Analysis
- Analysis label: `Post-Test Fairness and Sensitive Feature Analysis`
- Assessment status: `descriptive_disparities_reported`
- Final scientific recommendation: PASS
- Stage 4L official role unchanged: true
- Stage 8 started: false

This review assesses correct execution of descriptive approved-applications-only regression fairness analysis. It does not certify a model as fair, assess approval fairness, make a causal claim, or assess legal compliance.

## Reviewer Independence and Privacy Boundary

The independent Reviewer inspected the Stage 7 utility, aggregate results, reports, manifests, figures, plotting data, Notebook source and execution records, Registry evidence, protected hashes, and the complete attached Stage 7 specification.

The Reviewer did not open or print either restricted row-level sensitive CSV. Restricted evidence was checked only through paths, manifests, hashes, column manifests, row counts, access evidence, and aggregate outputs.

## Cycle History

### Cycle 1

Cycle 1 returned FAIL with three Critical, nine Major, three Minor, and zero Privacy findings. The main findings were recomputed target deciles, incorrect standardization weights, a Registry serialization rewrite, invalid final-review Notebook display, incomplete metric schemas, wrong Candidate-pair structure, incomplete paired Bootstrap and intersection evidence, incomplete governance summaries, and insufficient figures and Verification checks.

### Cycle 2 repair audit

Cycle 2 confirmed the accepted repairs and found three additional implementation defects before final closure:

1. The public label inventory initially exposed low-frequency raw `minority_population` values.
2. The suppression Boolean initially compared against the wrong tier string, so groups below 100 had detailed metrics.
3. The first restricted artifact had a pandas index-alignment error in the derived minority-population bins.

All three were repaired before this report. Public minority-population inventory now contains only the six frozen bins plus the zero-count missing bin. The derived restricted bin labels were repaired from the already-authorized restricted raw column without reopening the source; raw sensitive values were not changed. All groups below 100 retain label/count evidence while every detailed quantitative field is suppressed.

## Prerequisite and Frozen-Input Review

- Stage 4L Verification: PASS; `stage4l__blend__without_sensitive` remains `official_pre_registered_primary`.
- Stage 5A: `PASS_WITH_DOCUMENTED_GOVERNANCE_EXCEPTION`; the historical literal zero-Test-loading failure remains visible.
- Stage 5B: PASS; ensemble remains rejected and excluded.
- Stage 5C: PASS.
- Stage 6 Verification, Reviewer, protected recheck, and Stage 7 handoff: PASS.
- Stage 6 Notebook SHA-256: `c9b3d6eab7d3286e834fba15ada9683b64b3bc617d512a35b964cd8d2af65bbd`.
- Stage 6 Reviewer SHA-256: `d48e79295694a83394bb478fc237fd96d625a0f57dfdbf73bd328be5618e2c5c`.
- Stage 6 pre-analysis freeze SHA-256: `c9ed0df8eb14a9220c7f80d18167d2744a267f18c38a619bf539dfaade56432d`.
- Exactly three frozen prediction hashes match.
- Source SHA-256 matches `6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede`.
- Safe-loader SHA-256 matches `f981866b42351df1bae6d0a7b0148ccbc72ec9b49414eb706d524295fb86c4d0`.
- Test rows: 99,948; row-ID hash and target hash match the frozen values.

## Freeze Timing and Documentation Incident

The protected baseline and original freeze were created before first sensitive access. The original pre-access freeze SHA-256 is `473f3f37e69b663ad692c99a75aab277116395d71766f01bc44fd65051f49be4`; first sensitive access occurred later.

After cycle 1, the freeze file was expanded to state formulas already fixed by the attached ex-ante specification. The current amended freeze SHA-256 is `cba2b8d753ad3630f1c5acec368b3dbd6eb5a0c3933e2179ae3ec4e45f8e9d5d`. The access audit preserves both hashes and records that Candidate membership, sensitive/helper fields, thresholds, intersections, Bootstrap settings, privacy rules, and scientific selection did not change. This is accepted as a documentation-only repair, not a result-driven policy change.

## Sensitive Source, Alignment, and Privacy Review

- Physical real-source attempts: 1.
- Successful source materializations: 1.
- Test rows materialized: 99,948.
- Train rows materialized: 0.
- Excluded rows converted: 0.
- Source target columns requested: 0.
- Source target values materialized: 0.
- Exactly eight sensitive fields and one helper were authorized.
- `has_co_applicant` is binary and co-applicant identity metrics use only `has_co_applicant == 1`.
- Rows without a co-applicant remain in coverage evidence but do not enter identity metrics.
- Source and all three predictions remain hash-unchanged.
- Restricted sensitive-label artifact current SHA-256: `4a531f16edb1f2c82d5105c6083d25549a91b2ed484edca1b871572676bce3a1`.
- Derived minority-bin repair reopened the source: false.
- Restricted raw sensitive values changed by that repair: false.
- Public representative cases: 20 rows and zero raw sensitive columns.
- Notebook source contains no source, restricted-label, or prediction-file access.
- No public raw minority-population value remains in the label inventory.

Privacy review: PASS.

## Target Assignment and Standardization Review

- The utility uses saved Stage 5C `target_decile` and `is_top_five_percent_target` columns; the former rank-decile helper is not called.
- Saved target-decile counts are preserved: 10,221; 9,892; 9,951; 10,095; 9,892; 9,936; 10,012; 10,084; 9,884; 9,981.
- Standardization weights equal the observed frozen overall Test-decile shares and sum to one.
- Standardization requires a substantive primary group and at least 20 rows in every frozen decile.
- There are 69 available Candidate-group standardized rows, representing 23 substantive primary groups across three Candidates.
- The minimum decile support among available standardized rows is 39, proving that the separate 20-row standardization policy is used rather than the 50-row public group-decile display threshold.

## Group Metrics and Suppression Review

- Group coverage rows: 42.
- Coverage tiers: 32 primary, 3 limited-evidence, 7 suppressed-from-quantitative-comparison.
- Candidate-group metric rows: 114.
- Suppressed Candidate-group metric rows: 18.
- Every required detailed metric is null for all 18 suppressed rows.
- Limited groups retain basic metrics and are excluded from primary max/min and Bootstrap analysis.
- Group-decile rows: 1,140.
- Suppressed group-decile rows: 258, including group-level suppression and cells below 50.
- Every required metric is null for every suppressed group-decile row.
- Label inventory has original/canonical categorical labels, missing flags, substantive status, co-applicant flags, notes, and exactly seven public minority-bin rows.
- Group target distributions include required quantiles, frozen-decile composition, and target-tail shares.
- Single-attribute, disparity, largest-group reference, and target-standardized schemas match the specification.
- Mean Signed Error is `y_pred - y_true` and is interpreted by distance from zero.

## Candidate-Pair and Bootstrap Review

- Exactly three Candidate-pair IDs are present.
- Pairwise group rows: 96, exactly 32 per frozen Candidate pair.
- Minimum pairwise group size: 239; no suppressed group enters Candidate-pair metrics.
- Lower-error, second-lower-error, and tie rates sum to one within floating-point tolerance.
- Required MAE, RMSE, WAPE, P90, raw signed-error, absolute-bias, underprediction, win/loss/tie, and prediction-difference fields exist.
- Bootstrap eligible groups: 23 substantive primary single-attribute groups.
- Bootstrap rows: 414, exactly 18 rows per eligible group.
- Resamples: 500; seed: 42; identical within-group sampled indices are used across paired Candidates.
- All three Candidate pairs have paired MAE-difference, absolute-bias-difference, and first-Candidate-win-proportion intervals.
- Candidate MAE and Mean Signed Error intervals are present.
- P-values: none.
- Intersectional Bootstrap: none.

## Intersectional and Trade-Off Review

- Exactly three frozen intersections are present; triple intersections: 0.
- Intersection combinations: 16 ethnicity-by-sex, 24 race-by-sex, and 14 race-by-tract.
- Intersection metric rows: 162.
- Suppressed intersection metric rows: 60; every detailed suppressed value is null.
- With-sensitive-minus-without-sensitive MAE and lower-error-rate evidence is present; suppressed pairwise values are null.
- Accuracy-disparity table has exactly eight attribute rows and all required overall, worst/best-group, raw/standardized gap, signed-bias, underprediction-spread, improved/worsened/tied-group, and row-level win/loss fields.
- No comparison selects or promotes a model.

## Proxy, Risk, Figures, and Summary Review

- Proxy report is based on saved schema/inventory evidence only and lists the required potential proxy categories.
- No protected-attribute prediction model or causal proxy claim exists.
- Risk register has 14 rows and all required evidence, scope, governance severity, mitigation, remaining-limitation, and owner columns.
- Exactly 15 PNG figures and 15 plotting-data CSVs exist; every manifest hash matches.
- Applicant Race, Ethnicity, and Sex MAE plots use eligible paired-Bootstrap descriptive intervals.
- Majority-minority tract shows MAE and WAPE.
- Signed and change figures use zero references.
- The two required intersection figures are heatmaps.
- Sensitive-minus-without-sensitive group MAE plotting data contains substantive groups only.
- Disparity-gap-change plotting data uses attribute-level `raw_mae_gap_change`.
- The dashboard combines approved-only scope, accuracy-disparity change, and governance risk.
- Suppressed metrics are not plotted.
- Fairness summary includes protected/source/alignment/group-label hashes; coverage; disparity, standardized, pairwise, intersection, and trade-off summaries; proxy/risk paths; privacy controls; zero-access/fit/prediction counts; official-role status; and Stage 8 state.

## Registry Incident Adjudication

Cycle 1 rewrote the full Registry and changed the textual floating-point serialization of the prior block. Therefore the original raw byte prefix is not preserved. This incident is explicitly reported; it is not represented as byte preservation.

The incident is closed as serialization-only because:

- The frozen semantic canonical hash exactly matches the literal current 370-row prefix.
- All 370 prior Experiment IDs and values are unchanged.
- The Registry contains 378 unique IDs with exactly eight deterministic Stage 7 IDs.
- Current Stage 7 reruns return `REUSED` and do not rewrite the Registry.
- Registry file time and SHA-256 remain stable across repaired analysis reruns.
- Protected recheck records `registry_prior_raw_byte_prefix_preserved = false` and `registry_semantic_adjudication = PASS_no_prior_experiment_value_or_ID_change`.

This is an accepted transparent governance incident, not a model, metric, Candidate, or scientific-result change. Future Registry code should preserve literal prior bytes when appending.

## Notebook Review

- Sections 0–30 exist exactly once.
- Code cells: 31.
- Attempt 1 records a complete artifact-loading run with 31/31 executed code cells and zero errors.
- Attempt 2 records a cache-only run with 31/31 executed code cells and zero errors.
- Both runs used artifact-only code and performed zero source, restricted-file, model, bundle, fit, prediction-generation, Bootstrap-recomputation, figure-recreation, or Registry-duplication activity.
- Attempt 3 remains inside the maximum-three budget and is reserved only for the final mechanical refresh that displays this cycle-2 report, final protected recheck, and final Verification.
- No fourth execution is planned or recommended.

The required final mechanical refresh must remain gated by final Verification. Failure of attempt 3 would invalidate completion, but it is not an unresolved scientific, privacy, or implementation finding in this review.

## Protected Recheck

- Protected files checked: 756.
- Changed protected files: 0.
- Missing protected files: 0.
- Source hash unchanged: true.
- Prediction hashes unchanged: true.
- Prior Registry semantic rows unchanged: true.
- Prior Registry raw byte prefix preserved: false, transparently adjudicated above.

## Remaining Risks

- The analysis is Post-Test and cannot select a model.
- Only approved applications with observed outcomes are represented.
- Approval, denial, access-to-credit, and legal fairness are not assessed.
- The target may reflect historical or institutional processes.
- Error parity does not prove equitable outcomes.
- Sensitive labels may be incomplete or administrative.
- Small and intersectional groups remain less stable even with suppression.
- Removing explicit sensitive Features does not remove potential proxies.
- With-sensitive versus without-sensitive differences are observational, not causal.
- Future-data behavior and drift may differ.
- The Registry raw-byte serialization incident should inform stricter append-only handling in future Stages.

## Final Findings

Critical issues: 0

Major issues: 0

Minor issues: 0

Privacy issues: 0

Accepted fixes: all cycle-1 and cycle-2 scientific, suppression, privacy, governance, schema, visualization, and documentation fixes described above.

Rejected findings: none.

Unresolved Critical: 0

Unresolved Major: 0

Unresolved Minor: 0

Unresolved Privacy: 0

Final recommendation: PASS

{'changed_file_count': 0,
 'changed_paths': [],
 'checked_file_count': 756,
 'missing_file_count': 0,
 'missing_paths': [],
 'prediction_sha256_unchanged': True,
 'protected_file_count': 756,
 'registry_prior_raw_byte_prefix_preserved': False,
 'registry_prior_row_count': 370,
 'registry_prior_rows_unchanged': True,
 'registry_semantic_adjudication': 'PASS_no_prior_experiment_value_or_ID_change',
 'registry_serialization_incident': 'Cycle-1 full CSV rewrite changed floating-point text serialization only; the literal current 370-row prefix exactly matches the frozen semantic canonical hash.',
 'registry_stage7_row_count': 8,
 'source_sha256_unchanged': True,
 'stage_id': 'stage7',
 'status': 'PASS'}

{'analysis_label': 'Post-Test Fairness and Sensitive Feature Analysis',
 'approval_fairness_conclusion': False,
 'bundle_accesses': 0,
 'candidate_count': 3,
 'check_count': 32,
 'checks': {'access_audit': True,
  'alignment': True,
  'bootstrap_contract': True,
  'candidate_contract': True,
  'field_contract': True,
  'figures': True,
  'group_decile_schema': True,
  'group_metric_schema': True,
  'intersection_contract': True,
  'intersection_schema': True,
  'intersection_suppression': True,
  'inventory_schema': True,
  'notebook_artifact_only': True,
  'notebook_execution': True,
  'notebook_exists': True,
  'notebook_sections': True,
  'pairwise_contract': True,
  'protected_recheck': True,
  'registry': True,
  'required_result_csvs': True,
  'required_result_jsons': True,
  'restricted_files': True,
  'reviewer_no_unresolved_major': True,
  'reviewer_present': True,
  'risk_register_contract': True,
  'stage8_not_started': True,
  'standardization_schema': True,
  'suppression': True,
  'target_distribution_schema': True,
  'tier_suppression_consistency': True,
  'tradeoff_contract': True,
  'visualization_manifest': True},
 'fairness_assessment_status': 'descriptive_disparities_reported',
 'fit_calls': 0,
 'helper_field_count': 1,
 'legal_fairness_conclusion': False,
 'model_accesses': 0,
 'next_stage': 'Stage 8',
 'passed_check_count': 32,
 'prediction_generation_calls': 0,
 'sensitive_field_count': 8,
 'source_csv_successful_materializations': 1,
 'source_target_values': 0,
 'stage4l_official_unchanged': True,
 'stage8_started': False,
 'stage_id': 'stage7',
 'status': 'PASS',
 'test_rows': 99948,
 'train_rows_materialized': 0}

## 30. Stage 7 Completion Note

Why: This section documents stage 7 completion note from saved public or aggregate artifacts.

Conclusion: Stage 7 is complete; Stage 4L remains official and Stage 8 has not started.

Limitation: Another unbiased evaluation requires a new independent holdout.

In [31]:
show_json('artifacts/results/stage7/fairness/stage7_fairness_summary.json'); print({'candidate_count':3,'sensitive_field_count':8,'helper_field_count':1,'test_rows':99948,'source_csv_loads':1,'train_rows_materialized':0,'source_target_values':0,'model_accesses':0,'bundle_accesses':0,'fit_calls':0,'prediction_generation_calls':0,'legal_fairness_conclusion':False,'approval_fairness_conclusion':False,'stage4l_official_unchanged':True,'stage8_started':False})

{'accuracy_disparity_tradeoff_summary': {'attribute_rows': 8,
  'groups_improved': 22,
  'groups_worsened': 1,
  'overall_mae_change_with_minus_without': -0.3386313586895723},
 'alignment_report': {'path': 'artifacts/reports/stage7_group_prediction_alignment.json',
  'sha256': '55152c0e7b3fc2c2c5f900187148e224a9865834a3746503e3e2640078284856',
  'size_bytes': 1380},
 'analysis_label': 'Post-Test Fairness and Sensitive Feature Analysis',
 'approval_fairness_status': 'not assessed',
 'bundle_accesses': 0,
 'candidate_count': 3,
 'causal_fairness_status': 'not assessed',
 'causal_inference_performed': False,
 'fairness_assessment_status': 'descriptive_disparities_reported',
 'fairness_certification': False,
 'fairness_risk_register': {'path': 'artifacts/results/stage7/fairness/stage7_fairness_risk_register.csv',
  'sha256': '88693a620f866b635718806ed91e6f65dfe843ffee9f333fd3f97b8f5d54e222',
  'size_bytes': 4804},
 'fit_calls': 0,
 'group_coverage_summary': {'coverage_row_count': 42,
  'missing_label_count': 0,
  'non_substantive_label_count': 224961,
  'substantive_coverage_rows': 26},
 'helper_field_count': 1,
 'intersection_count': 3,
 'intersection_ids': ['applicant_ethnicity_x_applicant_sex',
  'applicant_race_x_applicant_sex',
  'applicant_race_x_majority_minority_tract'],
 'intersection_metric_row_count': 162,
 'intersection_summary': {'published_metric_rows': 102, 'suppressed_rows': 60},
 'legal_compliance_certification': False,
 'legal_status': 'not assessed',
 'limited_group_metric_rows': 0,
 'main_conclusion': 'Descriptive group error disparities are reported with bounded uncertainty. They do not establish causal, legal, approval-process, or population-wide fairness.',
 'maximum_primary_mae_gap': 39.68758995229648,
 'model_accesses': 0,
 'model_inference_performed': False,
 'model_selection_performed': False,
 'next_stage': 'Stage 8',
 'official_name': 'Stage 7 — Fairness and Sensitive Feature Analysis',
 'pair_ids': ['stage7__deep_with_minus_deep_without',
  'stage7__deep_with_minus_stage4l',
  'stage7__deep_without_minus_stage4l'],
 'pairwise_row_count': 96,
 'pairwise_summary': {'maximum_mae_difference': 3.659189294767529,
  'minimum_mae_difference': -2.554587185308762},
 'population_scope': 'approved applications with observed outcomes only',
 'pre_fairness_freeze': {'path': 'artifacts/reports/stage7_prefairness_freeze.json',
  'sha256': 'cba2b8d753ad3630f1c5acec368b3dbd6eb5a0c3933e2179ae3ec4e45f8e9d5d',
  'size_bytes': 11000},
 'prediction_generation_calls': 0,
 'primary_group_metric_rows': 69,
 'protected_baseline': {'path': 'artifacts/manifests/stage7/stage7_protected_hashes_before.json',
  'sha256': '6bb8532d34e69dee5daf3cf81d535f630fce56746877cd551993f238def1a873',
  'size_bytes': 165254},
 'proxy_feature_limitations': {'path': 'artifacts/results/stage7/fairness/stage7_proxy_feature_limitations.json',
  'sha256': 'c8bc4a199adb7e8b5fffa8d19fe9592bf5f0040df477c5dd8bba6c2b60428201',
  'size_bytes': 1268},
 'public_group_label_inventory': {'path': 'artifacts/results/stage7/fairness/stage7_group_label_inventory.csv',
  'sha256': '35ed920915c960fa58fce0bcd7ec7561cb1a6804efc3f99f317918a0fd986461',
  'size_bytes': 8422},
 'restricted_group_label_artifact': {'path': 'artifacts/sensitive/stage7/stage7_test_sensitive_group_labels.csv',
  'sha256': '4a531f16edb1f2c82d5105c6083d25549a91b2ed484edca1b871572676bce3a1',
  'size_bytes': 41872108},
 'row_id_hash': 'e58e4d078c761f60405e644d4dd7ba368f364daffb73b44abb39095938ece95e',
 'sensitive_data_handling': {'public_notebook_aggregate_only': True,
  'public_row_level_sensitive_files': 0,
  'row_level_labels_restricted': True,
  'stage8_public_exposure_prohibited': True},
 'sensitive_field_count': 8,
 'single_attribute_disparity_summary': {'attribute_candidate_rows': 24,
  'maximum_underprediction_rate_spread': 0.0654032053818354,
  'maximum_worst_minus_best_mae_gap': 39.68758995229648},
 'source_access_audit': {'path': 'artifacts/reports/stage7_sensitive_source_access_audit.json',
  'sha256': 'c9a4ef31326cdeba2eb29bbeae5d00ccf9879dae510f23300cb00b5fd0532539',
  'size_bytes': 2766},
 'source_hash': '6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede',
 'source_materializations': 1,
 'source_target_values': 0,
 'stage4l_remains_official': True,
 'stage8_started': False,
 'stage_id': 'stage7',
 'status': 'PASS',
 'suppressed_group_metric_rows': 18,
 'target_hash': '889e4253fb584c2a52a06d8b8e956beefad997ba18e4d736af0cd1738fb34a1a',
 'target_standardized_summary': {'available_rows': 69,
  'maximum_available_standardized_mae': 68.61232388420919},
 'test_row_count': 99948,
 'train_rows_materialized': 0}

{'candidate_count': 3, 'sensitive_field_count': 8, 'helper_field_count': 1, 'test_rows': 99948, 'source_csv_loads': 1, 'train_rows_materialized': 0, 'source_target_values': 0, 'model_accesses': 0, 'bundle_accesses': 0, 'fit_calls': 0, 'prediction_generation_calls': 0, 'legal_fairness_conclusion': False, 'approval_fairness_conclusion': False, 'stage4l_official_unchanged': True, 'stage8_started': False}