# Stage 8 — Final Explainability and Feature Interpretation

Saved-Decile Recovery under authorization `stage8_saved_decile_registry_recovery_20260716`. The invalid initial attempt remains preserved.

## 0. Stage Objective and Post-Test Disclosure

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [1]:
from pathlib import Path
import os, json
ROOT = Path.cwd()
MODE = os.environ.get('STAGE8_RECOVERY_NOTEBOOK_MODE', 'artifact_loading')
assert ROOT.name == 'regresionpart2'
display({'stage': 'Stage 8 Recovery', 'authorization_id': 'stage8_saved_decile_registry_recovery_20260716', 'mode': MODE, 'post_test': True, 'initial_attempt_invalidated': True, 'stage4l_official': True, 'stage9_started': False})

{'stage': 'Stage 8 Recovery',
 'authorization_id': 'stage8_saved_decile_registry_recovery_20260716',
 'mode': 'cache_only',
 'post_test': True,
 'initial_attempt_invalidated': True,
 'stage4l_official': True,
 'stage9_started': False}

## 1. Imports and Configuration

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display, Markdown, Image
RECOVERY_RESULTS = ROOT / 'artifacts/results/stage8/recovery'
RECOVERY_MANIFESTS = ROOT / 'artifacts/manifests/stage8/recovery'
REPORTS = ROOT / 'artifacts/reports'
assert MODE in {'artifact_loading', 'cache_only'}
display({'configuration': 'saved-artifact loading only', 'source_csv_loads': 0, 'model_loads': 0, 'inference_calls': 0, 'fit_calls': 0, 'registry_writes': 0})

{'configuration': 'saved-artifact loading only',
 'source_csv_loads': 0,
 'model_loads': 0,
 'inference_calls': 0,
 'fit_calls': 0,
 'registry_writes': 0}

## 2. State Reconstruction

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [3]:
data=json.loads((REPORTS/'stage8_recovery_notebook_preparation.json').read_text(encoding='utf-8'))
display(data)
display(Markdown('The initial Stage 8 sample and background were invalid. This Notebook loads only validated Recovery artifacts.'))

{'authorization_id': 'stage8_saved_decile_registry_recovery_20260716',
 'complete_local_dispersion_validated': True,
 'figures_validated': True,
 'notebook_artifact_loading_only_required': True,
 'registry_path_b_validated': True,
 'reviewer_finalization_occurs_after_two_notebook_runs': True,
 'scientific_artifacts_validated': True,
 'stage9_started': False,
 'status': 'PASS'}

The initial Stage 8 sample and background were invalid. This Notebook loads only validated Recovery artifacts.

## 3. Stage 7 Verification and Stage 8 Handoff

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [4]:
data=json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text(encoding='utf-8'))
display({'status': data['status'], 'authorization_id': data['authorization_id'], 'stage4l_official': data['candidate_ids'][0], 'stage5b_ensemble': 'rejected', 'stage9_started': data['stage9_started']})

{'status': 'PASS',
 'authorization_id': 'stage8_saved_decile_registry_recovery_20260716',
 'stage4l_official': 'stage4l__blend__without_sensitive',
 'stage5b_ensemble': 'rejected',
 'stage9_started': False}

## 4. Explainability Scope and Method Limitations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [5]:
text=(RECOVERY_RESULTS/'stage8_recovery_feature_interpretation_report.md').read_text(encoding='utf-8')
display(Markdown(text))

# Stage 8 Recovery Feature Interpretation Report

> This is Post-Test descriptive explainability. Stage 4L remains the official pre-registered primary.

## Scope
Exactly three frozen Candidate predictors and five frozen model identities are described. No model is selected or changed.

## Corrected sample
The Recovery uses exactly 2,000 Test rows sampled from saved Stage 5C target deciles, with 200 rows per decile. The 40-row background has four rows per saved decile.

## Global methods
Common grouped permutation uses original target units, seeds 42 and 43, and the same semantic-unit row permutations. Saved native Importance, saved native SHAP, and saved Stage 5A attribution are reuse-only.

## Official blend
The Stage 4L blend is explained by original-scale grouped permutation. Component SHAP values are not added because their output scales differ.

## RealMLP
Both RealMLP modes use the frozen Stage 5C models. The sensitive mode uses joint explicit-identity and sensitive-context blocks.

## Cross-model evidence
Applicant income and lien status are leading units across the three Candidates, while geography, income context, and occupancy ranks vary.

## Cross-method evidence
Rank agreement varies across native Importance, saved SHAP, saved Deep attribution, and grouped permutation. Disagreement is descriptive and is not model failure.

## Local evidence
The Recovery saved 64,800 reference effects for 20 cases, three Candidates, all semantic units, and 40 background rows. Standard deviation uses population ddof=0.

## Local stability
Four frozen visualization cases are compared across the first and second 20-row background halves. Background membership was not changed after results.

## Sensitive privacy
Public outputs include no raw sensitive identity or tract-context value. Joint replacement blocks are used rather than sums of one-at-a-time effects.

## Potential proxies
Geography, lender, income, property, loan-purpose, and lien categories are only potential-proxy warnings. They do not prove proxy behavior.

## Causal limitation
Permutation and reference substitution describe model behavior. They do not identify causes or realistic policy interventions.

## Fairness limitation
Sensitive importance neither proves nor disproves fairness, discrimination, or legal compliance. Stage 7 contains the descriptive subgroup analysis.

## Post-Test limitation
Test was consumed in Stage 4L. These explanations cannot promote a Candidate or provide another unbiased performance comparison.

## Initial attempt
The initial Stage 8 sample, background, affected explanations, figures, Registry rows, summary, and Handoff remain preserved as invalidated audit evidence.

## Stage 9
Stage 9 must reuse the final Recovery artifacts and must not rerun model inference or explainability.

## 5. Frozen Candidates and Model Identities

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [6]:
data=json.loads((REPORTS/'stage8_recovery_model_validation.json').read_text(encoding='utf-8'))
display(pd.DataFrame(data['models']))
display({'model_count': data['model_count'], 'fit_calls': data['model_fit_calls'], 'preprocessing_fit_calls': data['preprocessing_fit_calls']})

,bundle_path,bundle_sha256,family,model_id,physical_attempts,sensitive_mode,status,successful_outputs,target_mode,test_rows_in_fit,training_rows
0,artifacts/models/catboost/final/catboost_final...,57672c581ce91dfabb83a75ceaf074adaaab1b3ace7f94...,CatBoost,stage4l__catboost__without_sensitive,1,without_sensitive,PASS,1,log1p,0,399788
1,artifacts/models/lightgbm/final/lightgbm_final...,b1216ea51eafcd7b53289b23a53a594b67b1f5f3015e95...,LightGBM,stage4l__lightgbm__without_sensitive,1,without_sensitive,PASS,1,raw,0,399788
2,artifacts/models/xgboost/final/xgboost_final_w...,2a6bb80dacae81510592e9aea3477820cd3a7b66676d6e...,XGBoost,stage4l__xgboost__without_sensitive,1,without_sensitive,PASS,1,log1p,0,399788
3,artifacts/models/deep/core_final/stage5a2__rea...,0d2dc108578512022608fee31676ced4d3d65d178f3d77...,RealMLP,stage5c__realmlp__without_sensitive__test_eval...,1,without_sensitive,PASS,1,raw,0,399788
4,artifacts/models/deep/core_final/stage5a2__rea...,d8b74180385cae7c0cfb9570ef124e9061c4ee398a68a7...,RealMLP,stage5c__realmlp__with_sensitive__test_evaluation,1,with_sensitive,PASS,1,raw,0,399788

{'model_count': 5, 'fit_calls': 0, 'preprocessing_fit_calls': 0}

## 6. Protected File Baseline

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [7]:
data=json.loads((RECOVERY_MANIFESTS/'stage8_recovery_protected_baseline.json').read_text(encoding='utf-8'))
display({'status': data['status'], 'protected_file_count': data['protected_file_count'], 'registry': data['registry'], 'blocked_notebook': data['blocked_notebook']})

{'status': 'PASS',
 'protected_file_count': 917,
 'registry': {'experiment_ids': ['p2__ridge__without_sensitive__raw__development_scaler__fold-0__cfg-2f70ddab1e03',
   'p2__ridge__without_sensitive__log1p__development_scaler__fold-0__cfg-be6714210aca',
   'p2__ridge__without_sensitive__raw__development_scaler__fold-0__cfg-48378a298b48',
   'p2__ridge__without_sensitive__log1p__development_scaler__fold-0__cfg-498cb8cb26af',
   'p2__dummy_median__without_sensitive__raw__development_dummy_median__fold-0__cfg-8543c24384a2',
   'p2__linear_regression__without_sensitive__raw__development_linear_regression__fold-0__cfg-e153937e6bf2',
   'p2__linear_regression__without_sensitive__log1p__development_linear_regression__fold-0__cfg-0a554c89bf3a',
   'p2__ridge__without_sensitive__raw__development_ridge__fold-0__cfg-52f134e5ac5c',
   'p2__ridge__without_sensitive__raw__development_ridge__fold-0__cfg-f18559df5815',
   'p2__ridge__without_sensitive__raw__development_ridge__fold-0__cfg-2f70ddab1e03',
   'p2__ridge__without_sensitive__raw__development_ridge__fold-0__cfg-fb6db897bd3d',
   'p2__ridge__without_sensitive__raw__development_ridge__fold-0__cfg-8646efb5e2f8',
   'p2__ridge__without_sensitive__log1p__development_ridge__fold-0__cfg-4598655ffa1e',
   'p2__ridge__without_sensitive__log1p__development_ridge__fold-0__cfg-ee4b31610071',
   'p2__ridge__without_sensitive__log1p__development_ridge__fold-0__cfg-be6714210aca',
   'p2__ridge__without_sensitive__log1p__development_ridge__fold-0__cfg-a365573964c3',
   'p2__ridge__without_sensitive__log1p__development_ridge__fold-0__cfg-d2b87e6584cf',
   'p2__lasso__without_sensitive__raw__development_lasso__fold-0__cfg-997a88d64b67',
   'p2__lasso__without_sensitive__raw__development_lasso__fold-0__cfg-d1efebc879b5',
   'p2__lasso__without_sensitive__raw__development_lasso__fold-0__cfg-c4e9a8f625ad',
   'p2__lasso__without_sensitive__raw__development_lasso__fold-0__cfg-b925465f2768',
   'p2__lasso__without_sensitive__log1p__development_lasso__fold-0__cfg-47d890686b24',
   'p2__lasso__without_sensitive__log1p__development_lasso__fold-0__cfg-957304b0413f',
   'p2__lasso__without_sensitive__log1p__development_lasso__fold-0__cfg-1b0cef3e387b',
   'p2__lasso__without_sensitive__log1p__development_lasso__fold-0__cfg-fa859f1e0c85',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-853ae4ba30d6',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-3ae22ddb211f',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-d7b52c063c5f',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-b17caaddb077',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-0e993387453b',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-733ed81eccf9',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-e404584b637f',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-a4b8d42135ef',
   'p2__elastic_net__without_sensitive__raw__development_elastic_net__fold-0__cfg-48a41bd93ebd',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-204ef1a188df',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-62e4d0d360f6',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-325e9be2435a',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-479e8b555a2c',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-551ff418dccd',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-ca57e24c57a7',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-215418d5c1fb',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-2fd8c247f5d6',
   'p2__elastic_net__without_sensitive__log1p__development_elastic_net__fold-0__cfg-e86dd1814b45',
   'p2__gamma_regressor__without_sensitive__raw__development_gamma_regressor__fold-0__cfg-5830ed96b874',
   'p2__gamma_regressor__without_sensitive__raw__development_gamma_regressor__fold-0__cfg-03523a96ee23',
   'p2__gamma_regressor__without_sensitive__raw__development_gamma_regressor__fold-0__cfg-209ef135d61e',
   'p2__gamma_regressor__without_sensitive__raw__development_gamma_regressor__fold-0__cfg-d92489e5d2aa',
   'p2__dummy_median__without_sensitive__raw__cv_fold__fold-0__cfg-8543c24384a2',
   'p2__dummy_median__without_sensitive__raw__cv_fold__fold-1__cfg-8543c24384a2',
   'p2__dummy_median__without_sensitive__raw__cv_fold__fold-2__cfg-8543c24384a2',
   'p2__dummy_median__with_sensitive__raw__cv_fold__fold-0__cfg-8543c24384a2',
   'p2__dummy_median__with_sensitive__raw__cv_fold__fold-1__cfg-8543c24384a2',
   'p2__dummy_median__with_sensitive__raw__cv_fold__fold-2__cfg-8543c24384a2',
   'p2__linear_regression__without_sensitive__log1p__cv_fold__fold-0__cfg-0a554c89bf3a',
   'p2__linear_regression__without_sensitive__log1p__cv_fold__fold-1__cfg-0a554c89bf3a',
   'p2__linear_regression__without_sensitive__log1p__cv_fold__fold-2__cfg-0a554c89bf3a',
   'p2__linear_regression__with_sensitive__log1p__cv_fold__fold-0__cfg-0a554c89bf3a',
   'p2__linear_regression__with_sensitive__log1p__cv_fold__fold-1__cfg-0a554c89bf3a',
   'p2__linear_regression__with_sensitive__log1p__cv_fold__fold-2__cfg-0a554c89bf3a',
   'p2__ridge__without_sensitive__log1p__cv_fold__fold-0__cfg-d2b87e6584cf',
   'p2__ridge__without_sensitive__log1p__cv_fold__fold-1__cfg-d2b87e6584cf',
   'p2__ridge__without_sensitive__log1p__cv_fold__fold-2__cfg-d2b87e6584cf',
   'p2__ridge__with_sensitive__log1p__cv_fold__fold-0__cfg-d2b87e6584cf',
   'p2__ridge__with_sensitive__log1p__cv_fold__fold-1__cfg-d2b87e6584cf',
   'p2__ridge__with_sensitive__log1p__cv_fold__fold-2__cfg-d2b87e6584cf',
   'p2__lasso__without_sensitive__log1p__cv_fold__fold-0__cfg-957304b0413f',
   'p2__lasso__without_sensitive__log1p__cv_fold__fold-1__cfg-957304b0413f',
   'p2__lasso__without_sensitive__log1p__cv_fold__fold-2__cfg-957304b0413f',
   'p2__lasso__with_sensitive__log1p__cv_fold__fold-0__cfg-957304b0413f',
   'p2__lasso__with_sensitive__log1p__cv_fold__fold-1__cfg-957304b0413f',
   'p2__lasso__with_sensitive__log1p__cv_fold__fold-2__cfg-957304b0413f',
   'p2__elastic_net__without_sensitive__log1p__cv_fold__fold-0__cfg-215418d5c1fb',
   'p2__elastic_net__without_sensitive__log1p__cv_fold__fold-1__cfg-215418d5c1fb',
   'p2__elastic_net__without_sensitive__log1p__cv_fold__fold-2__cfg-215418d5c1fb',
   'p2__elastic_net__with_sensitive__log1p__cv_fold__fold-0__cfg-215418d5c1fb',
   'p2__elastic_net__with_sensitive__log1p__cv_fold__fold-1__cfg-215418d5c1fb',
   'p2__elastic_net__with_sensitive__log1p__cv_fold__fold-2__cfg-215418d5c1fb',
   'p2__gamma_regressor__without_sensitive__raw__cv_fold__fold-0__cfg-5830ed96b874',
   'p2__gamma_regressor__without_sensitive__raw__cv_fold__fold-1__cfg-5830ed96b874',
   'p2__gamma_regressor__without_sensitive__raw__cv_fold__fold-2__cfg-5830ed96b874',
   'p2__gamma_regressor__with_sensitive__raw__cv_fold__fold-0__cfg-5830ed96b874',
   'p2__gamma_regressor__with_sensitive__raw__cv_fold__fold-1__cfg-5830ed96b874',
   'p2__gamma_regressor__with_sensitive__raw__cv_fold__fold-2__cfg-5830ed96b874',
   'p2__dummy_median__without_sensitive__raw__oof_summary__fold-na__cfg-8543c24384a2',
   'p2__dummy_median__with_sensitive__raw__oof_summary__fold-na__cfg-8543c24384a2',
   'p2__linear_regression__without_sensitive__log1p__oof_summary__fold-na__cfg-0a554c89bf3a',
   'p2__linear_regression__with_sensitive__log1p__oof_summary__fold-na__cfg-0a554c89bf3a',
   'p2__ridge__without_sensitive__log1p__oof_summary__fold-na__cfg-d2b87e6584cf',
   'p2__ridge__with_sensitive__log1p__oof_summary__fold-na__cfg-d2b87e6584cf',
   'p2__lasso__without_sensitive__log1p__oof_summary__fold-na__cfg-957304b0413f',
   'p2__lasso__with_sensitive__log1p__oof_summary__fold-na__cfg-957304b0413f',
   'p2__elastic_net__without_sensitive__log1p__oof_summary__fold-na__cfg-215418d5c1fb',
   'p2__elastic_net__with_sensitive__log1p__oof_summary__fold-na__cfg-215418d5c1fb',
   'p2__gamma_regressor__without_sensitive__raw__oof_summary__fold-na__cfg-5830ed96b874',
   'p2__gamma_regressor__with_sensitive__raw__oof_summary__fold-na__cfg-5830ed96b874',
   'p2__dummy_median__without_sensitive__raw__final_train__fold-na__cfg-8543c24384a2',
   'p2__dummy_median__with_sensitive__raw__final_train__fold-na__cfg-8543c24384a2',
   'p2__linear_regression__without_sensitive__log1p__final_train__fold-na__cfg-0a554c89bf3a',
   'p2__linear_regression__with_sensitive__log1p__final_train__fold-na__cfg-0a554c89bf3a',
   'p2__ridge__without_sensitive__log1p__final_train__fold-na__cfg-d2b87e6584cf',
   'p2__ridge__with_sensitive__log1p__final_train__fold-na__cfg-d2b87e6584cf',
   'p2__lasso__without_sensitive__log1p__final_train__fold-na__cfg-957304b0413f',
   'p2__lasso__with_sensitive__log1p__final_train__fold-na__cfg-957304b0413f',
   'p2__elastic_net__without_sensitive__log1p__final_train__fold-na__cfg-215418d5c1fb',
   'p2__elastic_net__with_sensitive__log1p__final_train__fold-na__cfg-215418d5c1fb',
   'p2__gamma_regressor__without_sensitive__raw__final_train__fold-na__cfg-5830ed96b874',
   'p2__gamma_regressor__with_sensitive__raw__final_train__fold-na__cfg-5830ed96b874',
   'stage3__decision_tree__without_sensitive__raw__feature_screening__fold-0__cfg-a593f2ce765c',
   'stage3__decision_tree__without_sensitive__log1p__feature_screening__fold-0__cfg-f5b9d0c31556',
   'stage3__decision_tree__without_sensitive__raw__feature_screening__fold-0__cfg-b81b5f6af5aa',
   'stage3__decision_tree__without_sensitive__log1p__feature_screening__fold-0__cfg-74358ac9f382',
   'stage3__decision_tree__without_sensitive__raw__feature_screening__fold-0__cfg-9b4f4a475d51',
   'stage3__decision_tree__without_sensitive__log1p__feature_screening__fold-0__cfg-b8fee70412ff',
   'stage3__random_forest__without_sensitive__raw__feature_screening__fold-0__cfg-7efe5079d009',
   'stage3__random_forest__without_sensitive__log1p__feature_screening__fold-0__cfg-444e25c014ab',
   'stage3__random_forest__without_sensitive__raw__feature_screening__fold-0__cfg-d98a771d65c5',
   'stage3__random_forest__without_sensitive__log1p__feature_screening__fold-0__cfg-1373f41ca614',
   'stage3__random_forest__without_sensitive__raw__feature_screening__fold-0__cfg-10920e2262de',
   'stage3__random_forest__without_sensitive__log1p__feature_screening__fold-0__cfg-d5fd8d3afaf8',
   'stage3__extra_trees__without_sensitive__raw__feature_screening__fold-0__cfg-46aaabe3313d',
   'stage3__extra_trees__without_sensitive__log1p__feature_screening__fold-0__cfg-aafbc772bfb3',
   'stage3__extra_trees__without_sensitive__raw__feature_screening__fold-0__cfg-a34adfcab458',
   'stage3__extra_trees__without_sensitive__log1p__feature_screening__fold-0__cfg-2a71628f199a',
   'stage3__extra_trees__without_sensitive__raw__feature_screening__fold-0__cfg-a39ba2d0355e',
   'stage3__extra_trees__without_sensitive__log1p__feature_screening__fold-0__cfg-e8af3e8d9990',
   'stage3__hist_gradient_boosting__without_sensitive__raw__feature_screening__fold-0__cfg-ad9e194c1dea',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__feature_screening__fold-0__cfg-c2cbf9d62907',
   'stage3__hist_gradient_boosting__without_sensitive__raw__feature_screening__fold-0__cfg-ffe548393b7e',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__feature_screening__fold-0__cfg-e4974c8ca23c',
   'stage3__hist_gradient_boosting__without_sensitive__raw__feature_screening__fold-0__cfg-0ed0ef86cba7',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__feature_screening__fold-0__cfg-acac76569200',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-115bb7852d96',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-37ea218955eb',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-f333ab02d9b0',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-5992868aac5f',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-a593f2ce765c',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-f5b9d0c31556',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-3f318a39f069',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-030c5f9fce5c',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-092c1a9f1eb9',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-49636e57bced',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-e11a749163a1',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-3354b4dd70d9',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-bd55231f7640',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-92a051c4e49a',
   'stage3__decision_tree__without_sensitive__raw__model_screening__fold-0__cfg-c49f03b50cb4',
   'stage3__decision_tree__without_sensitive__log1p__model_screening__fold-0__cfg-76f94b9c6149',
   'stage3__random_forest__without_sensitive__raw__model_screening__fold-0__cfg-10920e2262de',
   'stage3__random_forest__without_sensitive__log1p__model_screening__fold-0__cfg-d5fd8d3afaf8',
   'stage3__random_forest__without_sensitive__raw__model_screening__fold-0__cfg-de9c0d97d663',
   'stage3__random_forest__without_sensitive__log1p__model_screening__fold-0__cfg-bbb76a602835',
   'stage3__random_forest__without_sensitive__raw__model_screening__fold-0__cfg-9414ec7c7fd0',
   'stage3__random_forest__without_sensitive__log1p__model_screening__fold-0__cfg-42525db2702a',
   'stage3__random_forest__without_sensitive__raw__model_screening__fold-0__cfg-1970189649ad',
   'stage3__random_forest__without_sensitive__log1p__model_screening__fold-0__cfg-7f1eaa1fdca9',
   'stage3__extra_trees__without_sensitive__raw__model_screening__fold-0__cfg-a39ba2d0355e',
   'stage3__extra_trees__without_sensitive__log1p__model_screening__fold-0__cfg-e8af3e8d9990',
   'stage3__extra_trees__without_sensitive__raw__model_screening__fold-0__cfg-537fe41851ac',
   'stage3__extra_trees__without_sensitive__log1p__model_screening__fold-0__cfg-57e7a38b9d19',
   'stage3__extra_trees__without_sensitive__raw__model_screening__fold-0__cfg-2d17202bf28a',
   'stage3__extra_trees__without_sensitive__log1p__model_screening__fold-0__cfg-e4a9b2702fcf',
   'stage3__extra_trees__without_sensitive__raw__model_screening__fold-0__cfg-9c55ceb45a23',
   'stage3__extra_trees__without_sensitive__log1p__model_screening__fold-0__cfg-b29987aae71e',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-3a0284e1edaa',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-2ebfb6537bc0',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-a58f9af51428',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-0ed0ef86cba7',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-acac76569200',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-fc1bb4ea3709',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-63eb1c0b0c24',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-0073611cb3e0',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-42b271e01075',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-16c843a325c0',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-e4ef9fd167c2',
   'stage3__hist_gradient_boosting__without_sensitive__raw__model_screening__fold-0__cfg-818cebf9a38f',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__model_screening__fold-0__cfg-7937b02f89ae',
   'stage3__random_forest__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-8a4ae8d203b8',
   'stage3__random_forest__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-6888a3aac3de',
   'stage3__random_forest__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-6cc8929e0963',
   'stage3__extra_trees__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-fd1559c538d3',
   'stage3__extra_trees__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-75f42bef864f',
   'stage3__extra_trees__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-52c1000435cf',
   'stage3__extra_trees__without_sensitive__log1p__runtime_repair_screening__fold-0__cfg-e2c2778f8aab',
   'stage3__random_forest__without_sensitive__log1p__full_fold_pilot__fold-0__cfg-6cc8929e0963',
   'stage3__decision_tree__without_sensitive__log1p__cv_fold__fold-0__cfg-030c5f9fce5c',
   'stage3__decision_tree__without_sensitive__log1p__cv_fold__fold-1__cfg-030c5f9fce5c',
   'stage3__decision_tree__without_sensitive__log1p__cv_fold__fold-2__cfg-030c5f9fce5c',
   'stage3__decision_tree__with_sensitive__log1p__cv_fold__fold-0__cfg-030c5f9fce5c',
   'stage3__decision_tree__with_sensitive__log1p__cv_fold__fold-1__cfg-030c5f9fce5c',
   'stage3__decision_tree__with_sensitive__log1p__cv_fold__fold-2__cfg-030c5f9fce5c',
   'stage3__random_forest__without_sensitive__log1p__cv_fold__fold-0__cfg-6cc8929e0963',
   'stage3__random_forest__without_sensitive__log1p__cv_fold__fold-1__cfg-6cc8929e0963',
   'stage3__random_forest__without_sensitive__log1p__cv_fold__fold-2__cfg-6cc8929e0963',
   'stage3__random_forest__with_sensitive__log1p__cv_fold__fold-0__cfg-6cc8929e0963',
   'stage3__random_forest__with_sensitive__log1p__cv_fold__fold-1__cfg-6cc8929e0963',
   'stage3__random_forest__with_sensitive__log1p__cv_fold__fold-2__cfg-6cc8929e0963',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__cv_fold__fold-0__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__cv_fold__fold-1__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__cv_fold__fold-2__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__with_sensitive__log1p__cv_fold__fold-0__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__with_sensitive__log1p__cv_fold__fold-1__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__with_sensitive__log1p__cv_fold__fold-2__cfg-4655ee7178b7',
   'stage3__decision_tree__without_sensitive__log1p__oof_summary__fold-na__cfg-030c5f9fce5c',
   'stage3__decision_tree__with_sensitive__log1p__oof_summary__fold-na__cfg-030c5f9fce5c',
   'stage3__random_forest__without_sensitive__log1p__oof_summary__fold-na__cfg-6cc8929e0963',
   'stage3__random_forest__with_sensitive__log1p__oof_summary__fold-na__cfg-6cc8929e0963',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__oof_summary__fold-na__cfg-4655ee7178b7',
   'stage3__hist_gradient_boosting__with_sensitive__log1p__oof_summary__fold-na__cfg-4655ee7178b7',
   'stage3__decision_tree__without_sensitive__log1p__final_training_fit__fold-na__cfg-030c5f9fce5c',
   'stage3__decision_tree__with_sensitive__log1p__final_training_fit__fold-na__cfg-030c5f9fce5c',
   'stage3__random_forest__without_sensitive__log1p__final_training_fit__fold-na__cfg-6cc8929e0963',
   'stage3__random_forest__with_sensitive__log1p__final_training_fit__fold-na__cfg-6cc8929e0963',
   'stage3__hist_gradient_boosting__without_sensitive__log1p__final_training_fit__fold-na__cfg-4655ee7178b7',

## 7. Pre-Explainability Freeze

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [8]:
data=json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text(encoding='utf-8'))
display({'freeze_status': data['status'], 'sample': data['sample'], 'background': data['background'], 'permutation_seeds': data['permutation_seeds'], 'blend_weights': data['blend_weights']})

{'freeze_status': 'PASS',
 'sample': {'counts': {'1': 200,
   '10': 200,
   '2': 200,
   '3': 200,
   '4': 200,
   '5': 200,
   '6': 200,
   '7': 200,
   '8': 200,
   '9': 200},
  'path': 'artifacts/manifests/stage8/recovery/stage8_recovery_global_sample_row_ids.csv',
  'row_count': 2000,
  'row_id_hash': 'd7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5ae2584d1b08c3a0358f',
  'sha256': '7d2bfd9b85887e203e176a2323e9ffe531d857907ad3c026e4f709c7b9ba84c9',
  'size_bytes': 19674,
  'target_hash': 'b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb6fe9ca57840336a8c0'},
 'background': {'counts': {'1': 4,
   '10': 4,
   '2': 4,
   '3': 4,
   '4': 4,
   '5': 4,
   '6': 4,
   '7': 4,
   '8': 4,
   '9': 4},
  'local_case_overlap': 0,
  'path': 'artifacts/manifests/stage8/recovery/stage8_recovery_local_background_row_ids.csv',
  'row_count': 40,
  'row_id_hash': '80a30da8f60aa3b5db6ec82847bfc0490359bc2412c3329ceb1f9915bfeb2efd',
  'sha256': 'de421e4fd18dbf68fa0e2cd04420b71e7fc3bf3cbf99abd36478ae4f426a8b13',
  'size_bytes': 407},
 'permutation_seeds': [42, 43],
 'blend_weights': {'catboost': 0.6, 'lightgbm': 0.2, 'xgboost': 0.2}}

## 8. Existing Explainability Artifact Inventory

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [9]:
data=json.loads((REPORTS/'stage8_recovery_existing_shap_provenance.json').read_text(encoding='utf-8'))
display(pd.DataFrame(data['artifacts']))
display({'global_shap_recomputations': data['global_shap_recomputations'], 'lineage_source': data['lineage_source']})

,additivity_evidence_presence,base_value_presence,feature_count,finite_value_status,metadata,metadata_status,model_identity,output_scale,row_ids,sample_role,sample_row_count,sensitive_mode,values
0,not_revalidated_without_recomputation,not_available_from_saved_artifact,4,True,{'path': 'artifacts/manifests/stage4/catboost/...,PASS,CatBoost,log1p model output,{'path': 'artifacts/results/stage4/catboost/fi...,Train-only validation,300,without_sensitive,{'path': 'artifacts/results/stage4/catboost/fi...
1,not_revalidated_without_recomputation,not_available_from_saved_artifact,4,True,{'path': 'artifacts/manifests/stage4/catboost/...,PASS,CatBoost,log1p model output,{'path': 'artifacts/results/stage4/catboost/fi...,Train-only validation,300,with_sensitive,{'path': 'artifacts/results/stage4/catboost/fi...
2,not_revalidated_without_recomputation,not_available_from_saved_artifact,35,True,{'path': 'artifacts/manifests/stage4/lightgbm/...,PASS,LightGBM,raw original target scale,{'path': 'artifacts/features/stage4/lightgbm/s...,Train-only validation,300,without_sensitive,{'path': 'artifacts/features/stage4/lightgbm/s...
3,not_revalidated_without_recomputation,not_available_from_saved_artifact,43,True,{'path': 'artifacts/manifests/stage4/lightgbm/...,PASS,LightGBM,raw original target scale,{'path': 'artifacts/features/stage4/lightgbm/s...,Train-only validation,300,with_sensitive,{'path': 'artifacts/features/stage4/lightgbm/s...
4,not_revalidated_without_recomputation,not_available_from_saved_artifact,1,True,{'path': 'artifacts/manifests/stage4/xgboost/s...,PASS,XGBoost,log1p model output,{'path': 'artifacts/manifests/stage4/xgboost/s...,Train-only validation,300,without_sensitive,{'path': 'artifacts/results/stage4/xgboost/fin...
5,not_revalidated_without_recomputation,not_available_from_saved_artifact,1,True,{'path': 'artifacts/manifests/stage4/xgboost/s...,PASS,XGBoost,log1p model output,{'path': 'artifacts/manifests/stage4/xgboost/s...,Train-only validation,300,with_sensitive,{'path': 'artifacts/results/stage4/xgboost/fin...

{'global_shap_recomputations': 0,
 'lineage_source': 'saved schemas and manifests only'}

## 9. Global Sample and Local Case Freeze

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [10]:
sample=pd.read_csv(RECOVERY_MANIFESTS/'stage8_recovery_global_sample_row_ids.csv')
background=pd.read_csv(RECOVERY_MANIFESTS/'stage8_recovery_local_background_row_ids.csv')
cases=pd.read_csv(ROOT/'artifacts/manifests/stage8/stage8_local_case_manifest.csv')
display(sample.groupby('target_decile').size().rename('sample_rows').to_frame())
display(background.groupby('target_decile').size().rename('background_rows').to_frame())
display({'sample_rows': len(sample), 'background_rows': len(background), 'local_cases': len(cases), 'sample_hash': json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text())['sample']['row_id_hash'], 'background_hash': json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text())['background']['row_id_hash']})

               sample_rows
target_decile
1                      200
2                      200
3                      200
4                      200
5                      200
6                      200
7                      200
8                      200
9                      200
10                     200

               background_rows
target_decile
1                            4
2                            4
3                            4
4                            4
5                            4
6                            4
7                            4
8                            4
9                            4
10                           4

{'sample_rows': 2000,
 'background_rows': 40,
 'local_cases': 20,
 'sample_hash': 'd7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5ae2584d1b08c3a0358f',
 'background_hash': '80a30da8f60aa3b5db6ec82847bfc0490359bc2412c3329ceb1f9915bfeb2efd'}

## 10. Safe Bounded Feature Loading

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [11]:
data=json.loads((REPORTS/'stage8_recovery_feature_access_audit.json').read_text(encoding='utf-8'))
display({'status': data['status'], 'access_attempts': data['access_attempts'], 'rows_materialized': data['rows_materialized'], 'train_rows': data['train_rows_materialized'], 'excluded_rows_converted': data['excluded_rows_converted'], 'source_targets': data['source_target_values_materialized'], 'source_hashes_after': data['source_hashes_after_access']})

{'status': 'PASS',
 'access_attempts': {'with_sensitive': 1, 'without_sensitive': 1},
 'rows_materialized': {'with_sensitive': 2019, 'without_sensitive': 2019},
 'train_rows': 0,
 'excluded_rows_converted': 0,
 'source_targets': 0,
 'source_hashes_after': {'with_sensitive': '6dc52dca5a8a7196a75213fab4a5a5c0a541f84390219459afb0b2be7b77aede',
  'without_sensitive': 'e90f7bb49cce5584c7ab250c1db6a107de5cf640c7839f318d7f3cb995edd93c'}}

## 11. Model and Bundle Validation

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [12]:
data=json.loads((REPORTS/'stage8_recovery_model_validation.json').read_text(encoding='utf-8'))
display(pd.DataFrame(data['models'])[['model_id','family','sensitive_mode','target_mode','physical_attempts','status']])

,model_id,family,sensitive_mode,target_mode,physical_attempts,status
0,stage4l__catboost__without_sensitive,CatBoost,without_sensitive,log1p,1,PASS
1,stage4l__lightgbm__without_sensitive,LightGBM,without_sensitive,raw,1,PASS
2,stage4l__xgboost__without_sensitive,XGBoost,without_sensitive,log1p,1,PASS
3,stage5c__realmlp__without_sensitive__test_eval...,RealMLP,without_sensitive,raw,1,PASS
4,stage5c__realmlp__with_sensitive__test_evaluation,RealMLP,with_sensitive,raw,1,PASS

## 12. Prediction Reconciliation

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [13]:
data=pd.read_csv(REPORTS/'stage8_recovery_prediction_reconciliation.csv')
display(data)
assert data.status.eq('PASS').all()

,model_or_candidate_id,row_count,saved_prediction_path,maximum_absolute_difference,mean_absolute_difference,tolerance,status
0,stage4l__catboost__without_sensitive,2000,artifacts/predictions/final_test/stage4l__catb...,2.273737e-13,5.559553e-15,0.00001,PASS
1,stage4l__lightgbm__without_sensitive,2000,artifacts/predictions/final_test/stage4l__ligh...,4.547474e-13,6.620537e-15,0.00001,PASS
2,stage4l__xgboost__without_sensitive,2000,artifacts/predictions/final_test/stage4l__xgbo...,2.273737e-13,5.464074e-15,0.00001,PASS
3,stage4l__blend__without_sensitive,2000,artifacts/predictions/final_test/stage4l__blen...,4.547474e-13,9.714007e-15,0.00001,PASS
4,stage5c__realmlp__without_sensitive__test_eval...,2000,artifacts/predictions/stage5/posttest_evaluati...,2.273737e-13,5.967948e-15,0.00100,PASS
5,stage5c__realmlp__with_sensitive__test_evaluation,2000,artifacts/predictions/stage5/posttest_evaluati...,2.273737e-13,5.641598e-15,0.00100,PASS

## 13. Existing Tree Feature Importance

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [14]:
data=pd.read_csv(ROOT/'artifacts/results/stage8/explainability/stage8_existing_importance_long.csv')
display(data.sort_values(['model_family','within_method_rank']).groupby(['model_family','method']).head(5))
display(Markdown('Reused native Importance. No value was recomputed.'))

,model_family,sensitive_mode,method,feature_name,raw_importance,artifact_path,canonical_feature,semantic_feature_unit,feature_family,absolute_importance,within_method_normalized_share,within_method_rank,component_id,sample_row_count,sample_role,output_scale,artifact_sha256,reused_status
0,CatBoost,without_sensitive,PredictionValuesChange,applicant_income_000s,2.546778e+01,artifacts/results/stage4/catboost/final/catboo...,applicant_income_000s,applicant_income,Applicant income,2.546778e+01,0.254678,1,stage4l__catboost__without_sensitive,0,native fitted-model importance,method-specific,2872739cfe20f5f54ddfbaf1f4aca60f99ba9584e9b094...,REUSED
216,CatBoost,with_sensitive,PredictionValuesChange,applicant_income_000s,2.535819e+01,artifacts/results/stage4/catboost/final/catboo...,applicant_income_000s,applicant_income,Applicant income,2.535819e+01,0.253582,1,stage4l__catboost__without_sensitive,0,native fitted-model importance,method-specific,05bb2dcd9df1812881d416dc801f78abcb41bd908848b3...,REUSED
1,CatBoost,without_sensitive,PredictionValuesChange,occupancy_lien_status_group,1.952644e+01,artifacts/results/stage4/catboost/final/catboo...,occupancy_lien_status_group,occupancy_lien_status_group,Loan structure and lien status,1.952644e+01,0.195264,2,stage4l__catboost__without_sensitive,0,native fitted-model importance,method-specific,2872739cfe20f5f54ddfbaf1f4aca60f99ba9584e9b094...,REUSED
217,CatBoost,with_sensitive,PredictionValuesChange,occupancy_lien_status_group,2.016342e+01,artifacts/results/stage4/catboost/final/catboo...,occupancy_lien_status_group,occupancy_lien_status_group,Loan structure and lien status,2.016342e+01,0.201634,2,stage4l__catboost__without_sensitive,0,native fitted-model importance,method-specific,05bb2dcd9df1812881d416dc801f78abcb41bd908848b3...,REUSED
2,CatBoost,without_sensitive,PredictionValuesChange,state_lien_status_group,1.015016e+01,artifacts/results/stage4/catboost/final/catboo...,state_lien_status_group,state_lien_status_group,Loan structure and lien status,1.015016e+01,0.101502,3,stage4l__catboost__without_sensitive,0,native fitted-model importance,method-specific,2872739cfe20f5f54ddfbaf1f4aca60f99ba9584e9b094...,REUSED
35,LightGBM,without_sensitive,gain,applicant_income_000s,9.757688e+05,artifacts/features/stage4/lightgbm/stage4h_imp...,applicant_income_000s,applicant_income,Applicant income,9.757688e+05,0.237479,1,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
36,LightGBM,without_sensitive,split,applicant_income_000s,4.494000e+03,artifacts/features/stage4/lightgbm/stage4h_imp...,applicant_income_000s,applicant_income,Applicant income,4.494000e+03,0.065130,1,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
259,LightGBM,with_sensitive,gain,applicant_income_000s,1.247895e+06,artifacts/features/stage4/lightgbm/stage4h_imp...,applicant_income_000s,applicant_income,Applicant income,1.247895e+06,0.301123,1,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,cddc270c9ee4d0968bb47244bb9034ab2c4ad613151929...,REUSED
260,LightGBM,with_sensitive,split,applicant_income_000s,4.219000e+03,artifacts/features/stage4/lightgbm/stage4h_imp...,applicant_income_000s,applicant_income,Applicant income,4.219000e+03,0.061145,1,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,cddc270c9ee4d0968bb47244bb9034ab2c4ad613151929...,REUSED
37,LightGBM,without_sensitive,gain,lien_status_name,5.062563e+05,artifacts/features/stage4/lightgbm/stage4h_imp...,lien_status_name,lien_status_name,Loan structure and lien status,5.062563e+05,0.123211,2,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
66,LightGBM,without_sensitive,split,respondent_id,4.342000e+03,artifacts/features/stage4/lightgbm/stage4h_imp...,respondent_id,respondent_id,"Lender, respondent, and agency",4.342000e+03,0.062928,2,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
261,LightGBM,with_sensitive,gain,lien_status_name,4.373124e+05,artifacts/features/stage4/lightgbm/stage4h_imp...,lien_status_name,lien_status_name,Loan structure and lien status,4.373124e+05,0.105526,2,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,cddc270c9ee4d0968bb47244bb9034ab2c4ad613151929...,REUSED
292,LightGBM,with_sensitive,split,respondent_id,4.013000e+03,artifacts/features/stage4/lightgbm/stage4h_imp...,respondent_id,respondent_id,"Lender, respondent, and agency",4.013000e+03,0.058159,2,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,cddc270c9ee4d0968bb47244bb9034ab2c4ad613151929...,REUSED
39,LightGBM,without_sensitive,gain,estimated_tract_family_income_000s,3.495274e+05,artifacts/features/stage4/lightgbm/stage4h_imp...,estimated_tract_family_income_000s,estimated_tract_family_income_000s,Tract and area income context,3.495274e+05,0.085067,3,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
78,LightGBM,without_sensitive,split,census_tract_number,3.868000e+03,artifacts/features/stage4/lightgbm/stage4h_imp...,census_tract_number,census_tract_number,Geography and region,3.868000e+03,0.056058,3,stage4l__lightgbm__without_sensitive,0,native fitted-model importance,method-specific,e3850a8e8ac4382a5253e1b3ee9df4c2621f61a41e7e6a...,REUSED
105,XGBoost,without_sensitive,gain,lien_status_name,1.072426e+04,artifacts/results/stage4/xgboost/final/stage4k...,lien_status_name,lien_status_name,Loan structure and lien status,1.072426e+04,0.630129,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
107,XGBoost,without_sensitive,total_gain,lien_status_name,1.043573e+06,artifacts/results/stage4/xgboost/final/stage4k...,lien_status_name,lien_status_name,Loan structure and lien status,1.043573e+06,0.448556,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
163,XGBoost,without_sensitive,weight,respondent_id,3.565000e+03,artifacts/results/stage4/xgboost/final/stage4k...,respondent_id,respondent_id,"Lender, respondent, and agency",3.565000e+03,0.071618,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
345,XGBoost,with_sensitive,gain,lien_status_name,9.821358e+03,artifacts/results/stage4/xgboost/final/stage4k...,lien_status_name,lien_status_name,Loan structure and lien status,9.821358e+03,0.447148,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
347,XGBoost,with_sensitive,total_gain,lien_status_name,1.029115e+06,artifacts/results/stage4/xgboost/final/stage4k...,lien_status_name,lien_status_name,Loan structure and lien status,1.029115e+06,0.441494,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
400,XGBoost,with_sensitive,weight,respondent_id,3.267000e+03,artifacts/results/stage4/xgboost/final/stage4k...,respondent_id,respondent_id,"Lender, respondent, and agency",3.267000e+03,0.065407,1,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
110,XGBoost,without_sensitive,total_gain,applicant_income_000s,4.665026e+05,artifacts/results/stage4/xgboost/final/stage4k...,applicant_income_000s,applicant_income,Applicant income,4.665026e+05,0.200516,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
117,XGBoost,without_sensitive,gain,purpose_lien_status_group,3.725659e+03,artifacts/results/stage4/xgboost/final/stage4k...,purpose_lien_status_group,purpose_lien_status_group,Loan structure and lien status,3.725659e+03,0.218910,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
145,XGBoost,without_sensitive,weight,state_name,2.724000e+03,artifacts/results/stage4/xgboost/final/stage4k...,state_name,state_name,Geography and region,2.724000e+03,0.054723,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
350,XGBoost,with_sensitive,total_gain,applicant_income_000s,4.887658e+05,artifacts/results/stage4/xgboost/final/stage4k...,applicant_income_000s,applicant_income,Applicant income,4.887658e+05,0.209682,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
357,XGBoost,with_sensitive,gain,purpose_lien_status_group,9.320403e+03,artifacts/results/stage4/xgboost/final/stage4k...,purpose_lien_status_group,purpose_lien_status_group,Loan structure and lien status,9.320403e+03,0.424341,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
379,XGBoost,with_sensitive,weight,state_name,2.610000e+03,artifacts/results/stage4/xgboost/final/stage4k...,state_name,state_name,Geography and region,2.610000e+03,0.052253,2,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,b870225b277f5703e1b44a9ef38318e6aaa6f08a55bfdd...,REUSED
109,XGBoost,without_sensitive,weight,applicant_income_000s,2.463000e+03,artifacts/results/stage4/xgboost/final/stage4k...,applicant_income_000s,applicant_income,Applicant income,2.463000e+03,0.049480,3,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
113,XGBoost,without_sensitive,total_gain,estimated_tract_family_income_000s,1.366535e+05,artifacts/results/stage4/xgboost/final/stage4k...,estimated_tract_family_income_000s,estimated_tract_family_income_000s,Tract and area income context,1.366535e+05,0.058737,3,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED
156,XGBoost,without_sensitive,gain,loan_type_lien_status_group,3.728820e+02,artifacts/results/stage4/xgboost/final/stage4k...,loan_type_lien_status_group,loan_type_lien_status_group,Loan structure and lien status,3.728820e+02,0.021910,3,stage4l__xgboost__without_sensitive,0,native fitted-model importance,method-specific,46d79e391728c27404d507a4951ecc6c9f999047a47c87...,REUSED

Reused native Importance. No value was recomputed.

## 14. Existing Tree SHAP

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Native SHAP output scales are declared and incompatible raw magnitudes are not combined.

In [15]:
data=pd.read_csv(ROOT/'artifacts/results/stage8/explainability/stage8_existing_shap_global.csv')
display(data.sort_values(['model_family','within_method_rank']).groupby('model_family').head(5))
display(Markdown('Reused saved SHAP. Native output scales differ; raw values are not combined. Base/additivity gaps remain reported honestly.'))

,model_family,sensitive_mode,feature_name,raw_importance,mean_signed_shap,artifact_path,output_scale,canonical_feature,semantic_feature_unit,feature_family,absolute_importance,within_method_normalized_share,within_method_rank,component_id,method,sample_row_count,sample_role,artifact_sha256,reused_status
0,CatBoost,without_sensitive,applicant_income_000s,0.158421,-0.007221,artifacts/results/stage4/catboost/final/catboo...,log1p model output,applicant_income_000s,applicant_income,Applicant income,0.158421,0.147957,1,stage4l__catboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,34454b8d0f2f86625a1e6d8ec44e0ab774c39c2180c01b...,REUSED
107,CatBoost,with_sensitive,applicant_income_000s,0.158729,0.002777,artifacts/results/stage4/catboost/final/catboo...,log1p model output,applicant_income_000s,applicant_income,Applicant income,0.158729,0.146030,1,stage4l__catboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,06454f2e523917cf0fa99aa827b7180f740def282d8b90...,REUSED
1,CatBoost,without_sensitive,occupancy_lien_status_group,0.129275,0.012786,artifacts/results/stage4/catboost/final/catboo...,log1p model output,occupancy_lien_status_group,occupancy_lien_status_group,Loan structure and lien status,0.129275,0.120736,2,stage4l__catboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,34454b8d0f2f86625a1e6d8ec44e0ab774c39c2180c01b...,REUSED
108,CatBoost,with_sensitive,occupancy_lien_status_group,0.142117,0.009638,artifacts/results/stage4/catboost/final/catboo...,log1p model output,occupancy_lien_status_group,occupancy_lien_status_group,Loan structure and lien status,0.142117,0.130747,2,stage4l__catboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,06454f2e523917cf0fa99aa827b7180f740def282d8b90...,REUSED
2,CatBoost,without_sensitive,state_lien_status_group,0.106637,0.002075,artifacts/results/stage4/catboost/final/catboo...,log1p model output,state_lien_status_group,state_lien_status_group,Loan structure and lien status,0.106637,0.099593,3,stage4l__catboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,34454b8d0f2f86625a1e6d8ec44e0ab774c39c2180c01b...,REUSED
37,LightGBM,without_sensitive,applicant_income_000s,57.897293,NaN,artifacts/features/stage4/lightgbm/stage4h_sha...,raw original target scale,applicant_income_000s,applicant_income,Applicant income,57.897293,0.219431,1,stage4l__lightgbm__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,fe855b846581d1591538c553f20139c660458103f03407...,REUSED
153,LightGBM,with_sensitive,applicant_income_000s,68.619496,NaN,artifacts/features/stage4/lightgbm/stage4h_sha...,raw original target scale,applicant_income_000s,applicant_income,Applicant income,68.619496,0.253536,1,stage4l__lightgbm__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,c0e30a7155a190fa9b7a4bf939ff2be84a690473ff0829...,REUSED
43,LightGBM,without_sensitive,estimated_tract_family_income_000s,34.542129,NaN,artifacts/features/stage4/lightgbm/stage4h_sha...,raw original target scale,estimated_tract_family_income_000s,estimated_tract_family_income_000s,Tract and area income context,34.542129,0.130915,2,stage4l__lightgbm__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,fe855b846581d1591538c553f20139c660458103f03407...,REUSED
164,LightGBM,with_sensitive,estimated_tract_family_income_000s,31.200717,NaN,artifacts/features/stage4/lightgbm/stage4h_sha...,raw original target scale,estimated_tract_family_income_000s,estimated_tract_family_income_000s,Tract and area income context,31.200717,0.115281,2,stage4l__lightgbm__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,c0e30a7155a190fa9b7a4bf939ff2be84a690473ff0829...,REUSED
69,LightGBM,without_sensitive,us_region,23.241945,NaN,artifacts/features/stage4/lightgbm/stage4h_sha...,raw original target scale,us_region,us_region,Geography and region,23.241945,0.088087,3,stage4l__lightgbm__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,fe855b846581d1591538c553f20139c660458103f03407...,REUSED
84,XGBoost,without_sensitive,lien_status_name,0.237359,NaN,artifacts/results/stage4/xgboost/final/stage4k...,log1p model output,lien_status_name,lien_status_name,Loan structure and lien status,0.237359,0.176097,1,stage4l__xgboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,606b84118c666637785504b639880017d815d2b1283ad6...,REUSED
213,XGBoost,with_sensitive,lien_status_name,0.242266,NaN,artifacts/results/stage4/xgboost/final/stage4k...,log1p model output,lien_status_name,lien_status_name,Loan structure and lien status,0.242266,0.171784,1,stage4l__xgboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,74e09485e5affae089175626869a5c3109961c4f736155...,REUSED
72,XGBoost,without_sensitive,applicant_income_000s,0.222693,NaN,artifacts/results/stage4/xgboost/final/stage4k...,log1p model output,applicant_income_000s,applicant_income,Applicant income,0.222693,0.165217,2,stage4l__xgboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,606b84118c666637785504b639880017d815d2b1283ad6...,REUSED
196,XGBoost,with_sensitive,applicant_income_000s,0.233393,NaN,artifacts/results/stage4/xgboost/final/stage4k...,log1p model output,applicant_income_000s,applicant_income,Applicant income,0.233393,0.165493,2,stage4l__xgboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,74e09485e5affae089175626869a5c3109961c4f736155...,REUSED
80,XGBoost,without_sensitive,estimated_tract_family_income_000s,0.119719,NaN,artifacts/results/stage4/xgboost/final/stage4k...,log1p model output,estimated_tract_family_income_000s,estimated_tract_family_income_000s,Tract and area income context,0.119719,0.088820,3,stage4l__xgboost__without_sensitive,mean_absolute_SHAP,300,Train-only Final Selection validation,606b84118c666637785504b639880017d815d2b1283ad6...,REUSED

Reused saved SHAP. Native output scales differ; raw values are not combined. Base/additivity gaps remain reported honestly.

## 15. Existing Deep Attribution

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [16]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_deep_attribution_comparison.csv')
display(data.sort_values('stage8_rank').head(15))
display(Markdown('Stage 5A uses a Train-only sample; Stage 8 Recovery uses a Post-Test saved-decile sample. Differences are not model drift.'))

,semantic_feature_unit,stage5a_rank,stage5a_mae_increase,stage5a_mean_absolute_prediction_change,stage8_rank,stage8_mae_increase,stage8_mean_absolute_prediction_change,rank_difference,shared_feature_flag,sample_role_difference,interpretation_limitation
1,applicant_income,1,43.368393,83.216891,1,41.819500,85.597430,0,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
8,lien_status_name,5,16.662079,21.557672,2,16.834421,20.480406,-3,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
12,msamd_name,3,6.288571,23.879792,3,10.032086,34.608858,0,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
14,owner_occupancy_name,9,5.094881,14.803575,4,8.825135,17.588797,-5,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
24,tract_income_ratio,2,7.080904,31.637100,5,8.508525,34.063558,3,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
25,us_region,11,1.552516,10.689792,6,6.505389,25.790261,-5,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
7,hud_median_family_income,10,2.601944,14.268793,7,5.102979,22.654342,-3,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
10,loan_purpose_name,8,2.950310,16.358201,8,3.141821,17.683265,0,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
21,respondent_id,4,3.588242,22.878633,9,2.364816,19.795483,5,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
11,loan_type_name,12,1.245836,8.149042,10,1.934077,9.058621,-2,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
4,county_name,6,4.847942,20.283566,11,1.888850,21.904610,5,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
15,owner_occupied_unit_ratio,13,1.056520,7.314823,12,1.396014,9.400414,-1,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
20,property_type_name,18,1.052592,1.968456,13,1.041745,2.010343,-5,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
5,family_units_per_1000_people,15,0.072906,4.774045,14,0.948759,7.813446,-1,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.
6,has_co_applicant,16,-0.188335,3.335042,15,0.718973,3.813120,-1,True,Stage 5A Train-only sample versus Stage 8 Post...,Rank differences are not model drift.

Stage 5A uses a Train-only sample; Stage 8 Recovery uses a Post-Test saved-decile sample. Differences are not model drift.

## 16. Common Global Permutation Importance

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Effects use original target units. Local reference substitution is not SHAP, additive, or causal.

In [17]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_common_permutation_importance.csv')
display(data.sort_values(['candidate_id','rank']).groupby('candidate_id').head(10))
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_permutation_repeat_stability.csv'))

,candidate_id,semantic_feature_unit,feature_family,baseline_mae,baseline_mean_prediction,permuted_mae_seed42,permuted_mae_seed43,mean_permuted_mae,std_permuted_mae,mae_increase,...,sample_row_count,row_id_hash,target_hash,seeds,original_target_scale_flag,sensitive_identity_flag,sensitive_context_flag,potential_proxy_category_flag,rank,positive_importance_normalized_share
0,stage4l__blend__without_sensitive,applicant_income,Applicant income,63.145543,238.397114,100.271059,99.876971,100.074015,0.197044,36.928472,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.373834
1,stage4l__blend__without_sensitive,lien_status_name,Loan structure and lien status,63.145543,238.397114,78.974577,78.786445,78.880511,0.094066,15.734968,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.159288
2,stage4l__blend__without_sensitive,owner_occupancy_name,Property and occupancy,63.145543,238.397114,71.596433,71.343908,71.470171,0.126262,8.324628,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.084272
3,stage4l__blend__without_sensitive,hud_median_family_income,Tract and area income context,63.145543,238.397114,69.448759,68.459435,68.954097,0.494662,5.808554,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.058801
4,stage4l__blend__without_sensitive,tract_income_ratio,Tract and area income context,63.145543,238.397114,68.719540,68.577233,68.648386,0.071153,5.502843,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.055706
5,stage4l__blend__without_sensitive,loan_purpose_name,Loan purpose and type,63.145543,238.397114,67.704456,68.277478,67.990967,0.286511,4.845424,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.049051
6,stage4l__blend__without_sensitive,state_name,Geography and region,63.145543,238.397114,66.876928,67.439748,67.158338,0.281410,4.012795,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.040622
7,stage4l__blend__without_sensitive,msamd_name,Geography and region,63.145543,238.397114,66.914169,67.015776,66.964973,0.050804,3.819430,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.038665
8,stage4l__blend__without_sensitive,county_name,Geography and region,63.145543,238.397114,66.147727,66.365306,66.256517,0.108790,3.110973,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,9,0.031493
9,stage4l__blend__without_sensitive,us_region,Geography and region,63.145543,238.397114,65.259907,65.827123,65.543515,0.283608,2.397972,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,10,0.024275
27,stage5c__realmlp__with_sensitive__test_evaluation,applicant_income,Applicant income,63.212974,240.887718,107.084631,106.179893,106.632262,0.452369,43.419288,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.382848
28,stage5c__realmlp__with_sensitive__test_evaluation,lien_status_name,Loan structure and lien status,63.212974,240.887718,79.766818,79.970542,79.868680,0.101862,16.655706,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.146861
29,stage5c__realmlp__with_sensitive__test_evaluation,owner_occupancy_name,Property and occupancy,63.212974,240.887718,72.026171,72.361523,72.193847,0.167676,8.980873,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.079189
30,stage5c__realmlp__with_sensitive__test_evaluation,msamd_name,Geography and region,63.212974,240.887718,71.689013,70.960080,71.324546,0.364467,8.111572,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.071524
31,stage5c__realmlp__with_sensitive__test_evaluation,tract_income_ratio,Tract and area income context,63.212974,240.887718,70.479018,69.903102,70.191060,0.287958,6.978086,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.061529
32,stage5c__realmlp__with_sensitive__test_evaluation,us_region,Geography and region,63.212974,240.887718,68.616078,69.622618,69.119348,0.503270,5.906374,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.052079
33,stage5c__realmlp__with_sensitive__test_evaluation,hud_median_family_income,Tract and area income context,63.212974,240.887718,67.439162,66.622578,67.030870,0.408292,3.817896,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.033664
34,stage5c__realmlp__with_sensitive__test_evaluation,loan_purpose_name,Loan purpose and type,63.212974,240.887718,66.178193,66.606811,66.392502,0.214309,3.179528,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.028035
35,stage5c__realmlp__with_sensitive__test_evaluation,respondent_id,"Lender, respondent, and agency",63.212974,240.887718,66.863747,65.708366,66.286056,0.577691,3.073082,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,9,0.027097
36,stage5c__realmlp__with_sensitive__test_evaluation,loan_type_name,Loan purpose and type,63.212974,240.887718,65.704513,65.242136,65.473325,0.231188,2.260351,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,10,0.019931
55,stage5c__realmlp__without_sensitive__test_eval...,applicant_income,Applicant income,64.962334,241.253136,107.282091,106.281577,106.781834,0.500257,41.819500,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.372210
56,stage5c__realmlp__without_sensitive__test_eval...,lien_status_name,Loan structure and lien status,64.962334,241.253136,81.746372,81.847139,81.796755,0.050384,16.834421,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.149833
57,stage5c__realmlp__without_sensitive__test_eval...,msamd_name,Geography and region,64.962334,241.253136,75.413455,74.575385,74.994420,0.419035,10.032086,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.089289
58,stage5c__realmlp__without_sensitive__test_eval...,owner_occupancy_name,Property and occupancy,64.962334,241.253136,73.933508,73.641430,73.787469,0.146039,8.825135,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.078547
59,stage5c__realmlp__without_sensitive__test_eval...,tract_income_ratio,Tract and area income context,64.962334,241.253136,73.653335,73.288383,73.470859,0.182476,8.508525,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.075729
60,stage5c__realmlp__without_sensitive__test_eval...,us_region,Geography and region,64.962334,241.253136,70.520643,72.414804,71.467724,0.947081,6.505389,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.057901
61,stage5c__realmlp__without_sensitive__test_eval...,hud_median_family_income,Tract and area income context,64.962334,241.253136,70.644345,69.486281,70.065313,0.579032,5.102979,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.045419
62,stage5c__realmlp__without_sensitive__test_eval...,loan_purpose_name,Loan purpose and type,64.962334,241.253136,68.231242,67.977068,68.104155,0.127087,3.141821,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.027963
63,stage5c__realmlp__without_sensitive__test_eval...,respondent_id,"Lender, respondent, and agency",64.962334,241.253136,67.918171,66.736128,67.327150,0.591021,2.364816,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,9,0.021048
64,stage5c__realmlp__without_sensitive__test_eval...,loan_type_name,Loan purpose and type,64.962334,241.253136,66.716202,67.076620,66.896411,0.180209,1.934077,...,2000,d7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5a...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,10,0.017214

,candidate_id,spearman_rank_correlation,top_10_overlap,top_20_overlap,maximum_rank_movement,median_rank_movement,repeat_count,seeds
0,stage4l__blend__without_sensitive,0.945055,9,18,8.0,1.0,2,42|43
1,stage5c__realmlp__without_sensitive__test_eval...,0.982906,9,19,3.0,1.0,2,42|43
2,stage5c__realmlp__with_sensitive__test_evaluation,0.977559,10,19,4.0,1.0,2,42|43

## 17. Semantic Feature Units and Families

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [18]:
data=pd.read_csv(ROOT/'artifacts/results/stage8/explainability/stage8_feature_unit_mapping.csv')
display(data.head(20))
display(Markdown('Lineage comes from saved schemas and deterministic names, not explanation outcomes.'))

,candidate_or_component_id,input_column,transformed_feature_name,canonical_raw_feature,semantic_feature_unit,feature_family,feature_type,derived_feature_flag,parent_features,sensitive_identity_flag,sensitive_context_flag,potential_proxy_category_flag,mapping_evidence,mapping_confidence
0,stage4l__catboost__without_sensitive,applicant_income_000s,applicant_income_000s,applicant_income_000s,applicant_income,Applicant income,numeric,False,applicant_income,False,False,True,frozen source schema and deterministic name li...,high
1,stage4l__catboost__without_sensitive,population,population,population,population,Engineered ratios and counts,numeric,False,NaN,False,False,False,frozen source schema and deterministic name li...,high
2,stage4l__catboost__without_sensitive,hud_median_family_income,hud_median_family_income,hud_median_family_income,hud_median_family_income,Tract and area income context,numeric,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
3,stage4l__catboost__without_sensitive,number_of_owner_occupied_units,number_of_owner_occupied_units,number_of_owner_occupied_units,owner_occupied_units,Property and occupancy,numeric,False,owner_occupied_units,False,False,True,frozen source schema and deterministic name li...,high
4,stage4l__catboost__without_sensitive,number_of_1_to_4_family_units,number_of_1_to_4_family_units,number_of_1_to_4_family_units,one_to_four_family_units,Other documented Features,numeric,False,one_to_four_family_units,False,False,False,frozen source schema and deterministic name li...,high
5,stage4l__catboost__without_sensitive,applicant_income_to_area_income,applicant_income_to_area_income,applicant_income_to_area_income,applicant_income_to_area_income,Tract and area income context,numeric,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
6,stage4l__catboost__without_sensitive,tract_income_ratio,tract_income_ratio,tract_income_ratio,tract_income_ratio,Tract and area income context,numeric,True,NaN,False,False,True,frozen source schema and deterministic name li...,high
7,stage4l__catboost__without_sensitive,owner_occupied_unit_ratio,owner_occupied_unit_ratio,owner_occupied_unit_ratio,owner_occupied_unit_ratio,Property and occupancy,numeric,True,NaN,False,False,True,frozen source schema and deterministic name li...,high
8,stage4l__catboost__without_sensitive,family_units_per_1000_people,family_units_per_1000_people,family_units_per_1000_people,family_units_per_1000_people,Engineered ratios and counts,numeric,True,NaN,False,False,False,frozen source schema and deterministic name li...,high
9,stage4l__catboost__without_sensitive,owner_occupied_units_per_1000_people,owner_occupied_units_per_1000_people,owner_occupied_units_per_1000_people,owner_occupied_units_per_1000_people,Property and occupancy,numeric,True,NaN,False,False,True,frozen source schema and deterministic name li...,high
10,stage4l__catboost__without_sensitive,has_co_applicant,has_co_applicant,has_co_applicant,has_co_applicant,Engineered ratios and counts,numeric,False,NaN,False,False,False,frozen source schema and deterministic name li...,high
11,stage4l__catboost__without_sensitive,agency_name,agency_name,agency_name,agency_name,"Lender, respondent, and agency",categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
12,stage4l__catboost__without_sensitive,loan_type_name,loan_type_name,loan_type_name,loan_type_name,Loan purpose and type,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
13,stage4l__catboost__without_sensitive,property_type_name,property_type_name,property_type_name,property_type_name,Property and occupancy,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
14,stage4l__catboost__without_sensitive,loan_purpose_name,loan_purpose_name,loan_purpose_name,loan_purpose_name,Loan purpose and type,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
15,stage4l__catboost__without_sensitive,owner_occupancy_name,owner_occupancy_name,owner_occupancy_name,owner_occupancy_name,Property and occupancy,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
16,stage4l__catboost__without_sensitive,preapproval_name,preapproval_name,preapproval_name,preapproval_name,Other documented Features,categorical,False,NaN,False,False,False,frozen source schema and deterministic name li...,high
17,stage4l__catboost__without_sensitive,state_name,state_name,state_name,state_name,Geography and region,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
18,stage4l__catboost__without_sensitive,lien_status_name,lien_status_name,lien_status_name,lien_status_name,Loan structure and lien status,categorical,False,NaN,False,False,True,frozen source schema and deterministic name li...,high
19,stage4l__catboost__without_sensitive,loan_program_group,loan_program_group,loan_program_group,loan_program_group,Loan structure and lien status,categorical,True,NaN,False,False,True,frozen source schema and deterministic name li...,high

Lineage comes from saved schemas and deterministic names, not explanation outcomes.

## 18. Cross-Model Feature Comparison

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [19]:
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_cross_model_agreement.csv'))
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_cross_model_feature_comparison.csv').sort_values('official_blend_rank').head(20))

,model_a,model_b,shared_feature_count,spearman_rank_correlation,kendall_rank_correlation,top_10_intersection,top_10_jaccard,top_20_intersection,top_20_jaccard
0,stage4l__blend__without_sensitive,stage5c__realmlp__without_sensitive__test_eval...,26,0.870085,0.710769,8,0.666667,17,0.739130
1,stage4l__blend__without_sensitive,stage5c__realmlp__with_sensitive__test_evaluation,26,0.928889,0.784615,8,0.666667,18,0.818182
2,stage5c__realmlp__without_sensitive__test_eval...,stage5c__realmlp__with_sensitive__test_evaluation,26,0.932308,0.815385,10,1.000000,18,0.818182

,semantic_feature_unit,official_blend_rank,official_blend_importance,realmlp_without_rank,realmlp_without_importance,realmlp_with_rank,realmlp_with_importance,shared_across_all_flag,present_in_blend_flag,present_in_deep_without_flag,present_in_deep_with_flag,maximum_rank_difference,minimum_rank_difference,rank_range,consensus_top_10_flag,consensus_top_20_flag,feature_family,sensitive_identity_flag,sensitive_context_flag,potential_proxy_category_flag
1,applicant_income,1.0,36.928472,1.0,41.819500,1.0,43.419288,True,True,True,True,0.0,1.0,0.0,True,True,Applicant income,False,False,True
10,lien_status_name,2.0,15.734968,2.0,16.834421,2.0,16.655706,True,True,True,True,0.0,2.0,0.0,True,True,Loan structure and lien status,False,False,True
16,owner_occupancy_name,3.0,8.324628,4.0,8.825135,3.0,8.980873,True,True,True,True,1.0,3.0,1.0,True,True,Property and occupancy,False,False,True
9,hud_median_family_income,4.0,5.808554,7.0,5.102979,7.0,3.817896,True,True,True,True,3.0,4.0,3.0,True,True,Tract and area income context,False,False,True
27,tract_income_ratio,5.0,5.502843,5.0,8.508525,5.0,6.978086,True,True,True,True,0.0,5.0,0.0,True,True,Tract and area income context,False,False,True
12,loan_purpose_name,6.0,4.845424,8.0,3.141821,8.0,3.179528,True,True,True,True,2.0,6.0,2.0,True,True,Loan purpose and type,False,False,True
25,state_name,7.0,4.012795,19.0,0.076901,14.0,1.592012,True,True,True,True,12.0,7.0,12.0,False,True,Geography and region,False,False,True
14,msamd_name,8.0,3.819430,3.0,10.032086,4.0,8.111572,True,True,True,True,5.0,3.0,5.0,True,True,Geography and region,False,False,True
5,county_name,9.0,3.110973,11.0,1.888850,13.0,1.608985,True,True,True,True,4.0,9.0,4.0,False,True,Geography and region,False,False,True
28,us_region,10.0,2.397972,6.0,6.505389,6.0,5.906374,True,True,True,True,4.0,6.0,4.0,True,True,Geography and region,False,False,True
13,loan_type_name,11.0,2.280650,10.0,1.934077,10.0,2.260351,True,True,True,True,1.0,10.0,1.0,False,True,Loan purpose and type,False,False,True
22,property_type_name,12.0,1.237809,13.0,1.041745,15.0,1.143450,True,True,True,True,3.0,12.0,3.0,False,True,Property and occupancy,False,False,True
23,respondent_id,13.0,1.077078,9.0,2.364816,9.0,3.073082,True,True,True,True,4.0,9.0,4.0,False,True,"Lender, respondent, and agency",False,False,True
17,owner_occupied_unit_ratio,14.0,0.765329,12.0,1.396014,12.0,1.632515,True,True,True,True,2.0,12.0,2.0,False,True,Property and occupancy,False,False,True
4,census_tract_number,15.0,0.647585,NaN,NaN,NaN,NaN,False,True,False,False,0.0,15.0,0.0,False,False,Geography and region,False,False,True
0,agency_name,16.0,0.645593,16.0,0.710642,17.0,0.654321,True,True,True,True,1.0,16.0,1.0,False,True,"Lender, respondent, and agency",False,False,True
8,has_co_applicant,17.0,0.346130,15.0,0.718973,18.0,0.479605,True,True,True,True,3.0,15.0,3.0,False,True,Engineered ratios and counts,False,False,False
7,family_units_per_1000_people,18.0,0.262770,14.0,0.948759,16.0,0.713094,True,True,True,True,4.0,14.0,4.0,False,True,Engineered ratios and counts,False,False,False
3,applicant_income_to_area_income,19.0,0.224559,21.0,0.009230,26.0,-0.012800,True,True,True,True,7.0,19.0,7.0,False,False,Tract and area income context,False,False,True
19,owner_occupied_units_per_1000_people,20.0,0.189806,25.0,-0.126411,23.0,0.111402,True,True,True,True,5.0,20.0,5.0,False,False,Property and occupancy,False,False,True

## 19. Cross-Method Agreement

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Native SHAP output scales are declared and incompatible raw magnitudes are not combined.

In [20]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_cross_method_agreement.csv')
display(data)
display(Markdown('Rank-only comparison is used when native explanation scales differ.'))

,model_family,sensitive_mode,method_a,method_b,shared_feature_count,spearman_correlation,top_10_overlap,top_20_overlap,largest_disagreements,output_scale_compatibility,interpretation
0,CatBoost,without_sensitive,PredictionValuesChange,mean_absolute_SHAP,37,0.933266,8,18,lien_status_name|census_tract_number|purpose_l...,ranks only,Method disagreement is expected and is not a m...
1,LightGBM,without_sensitive,gain,mean_absolute_SHAP,37,0.924017,8,18,has_co_applicant|agency_lien_status_group|fami...,ranks only,Method disagreement is expected and is not a m...
2,LightGBM,without_sensitive,split,mean_absolute_SHAP,37,0.332720,3,12,census_tract_number|owner_occupancy_name|lien_...,ranks only,Method disagreement is expected and is not a m...
3,XGBoost,without_sensitive,gain,mean_absolute_SHAP,39,0.647473,6,16,applicant_income_area_group|loan_program_group...,ranks only,Method disagreement is expected and is not a m...
4,XGBoost,without_sensitive,total_gain,mean_absolute_SHAP,39,0.895473,8,18,purpose_lien_status_group|has_co_applicant|loa...,ranks only,Method disagreement is expected and is not a m...
5,RealMLP,without_sensitive,Stage 5A saved permutation attribution,Stage 8 Recovery grouped permutation,26,0.829060,8,18,state_name|loan_program_group|owner_occupied_u...,"both original target scale, different samples",Differences may reflect sample role and groupi...

Rank-only comparison is used when native explanation scales differ.

## 20. Sensitive Feature Dependence and Proxy Limitations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [21]:
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_sensitive_feature_dependence.csv')[['semantic_feature_unit','mae_increase','mean_absolute_prediction_change','positive_importance_normalized_share','rank']])
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_potential_proxy_overlap.csv').sort_values(['candidate_id','rank']).groupby('candidate_id').head(8))
display(Markdown('Sensitive importance is aggregate-only. It does not prove discrimination, fairness, causality, or legal compliance.'))

,semantic_feature_unit,mae_increase,mean_absolute_prediction_change,positive_importance_normalized_share,rank
0,sensitive_context_block,1.785733,12.511228,0.015746,11
1,explicit_sensitive_identity_block,0.445498,8.158598,0.003928,19

,candidate_id,semantic_feature_unit,feature_family,baseline_mae,baseline_mean_prediction,permuted_mae_seed42,permuted_mae_seed43,mean_permuted_mae,std_permuted_mae,mae_increase,...,target_hash,seeds,original_target_scale_flag,sensitive_identity_flag,sensitive_context_flag,potential_proxy_category_flag,rank,positive_importance_normalized_share,potential_proxy_wording,evidence_source
0,stage4l__blend__without_sensitive,applicant_income,Applicant income,63.145543,238.397114,100.271059,99.876971,100.074015,0.197044,36.928472,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.373834,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
1,stage4l__blend__without_sensitive,lien_status_name,Loan structure and lien status,63.145543,238.397114,78.974577,78.786445,78.880511,0.094066,15.734968,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.159288,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
2,stage4l__blend__without_sensitive,owner_occupancy_name,Property and occupancy,63.145543,238.397114,71.596433,71.343908,71.470171,0.126262,8.324628,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.084272,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
3,stage4l__blend__without_sensitive,hud_median_family_income,Tract and area income context,63.145543,238.397114,69.448759,68.459435,68.954097,0.494662,5.808554,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.058801,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
4,stage4l__blend__without_sensitive,tract_income_ratio,Tract and area income context,63.145543,238.397114,68.719540,68.577233,68.648386,0.071153,5.502843,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.055706,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
5,stage4l__blend__without_sensitive,loan_purpose_name,Loan purpose and type,63.145543,238.397114,67.704456,68.277478,67.990967,0.286511,4.845424,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.049051,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
6,stage4l__blend__without_sensitive,state_name,Geography and region,63.145543,238.397114,66.876928,67.439748,67.158338,0.281410,4.012795,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.040622,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
7,stage4l__blend__without_sensitive,msamd_name,Geography and region,63.145543,238.397114,66.914169,67.015776,66.964973,0.050804,3.819430,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.038665,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
21,stage5c__realmlp__with_sensitive__test_evaluation,applicant_income,Applicant income,63.212974,240.887718,107.084631,106.179893,106.632262,0.452369,43.419288,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.382848,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
22,stage5c__realmlp__with_sensitive__test_evaluation,lien_status_name,Loan structure and lien status,63.212974,240.887718,79.766818,79.970542,79.868680,0.101862,16.655706,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.146861,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
23,stage5c__realmlp__with_sensitive__test_evaluation,owner_occupancy_name,Property and occupancy,63.212974,240.887718,72.026171,72.361523,72.193847,0.167676,8.980873,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.079189,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
24,stage5c__realmlp__with_sensitive__test_evaluation,msamd_name,Geography and region,63.212974,240.887718,71.689013,70.960080,71.324546,0.364467,8.111572,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.071524,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
25,stage5c__realmlp__with_sensitive__test_evaluation,tract_income_ratio,Tract and area income context,63.212974,240.887718,70.479018,69.903102,70.191060,0.287958,6.978086,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.061529,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
26,stage5c__realmlp__with_sensitive__test_evaluation,us_region,Geography and region,63.212974,240.887718,68.616078,69.622618,69.119348,0.503270,5.906374,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.052079,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
27,stage5c__realmlp__with_sensitive__test_evaluation,hud_median_family_income,Tract and area income context,63.212974,240.887718,67.439162,66.622578,67.030870,0.408292,3.817896,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.033664,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
28,stage5c__realmlp__with_sensitive__test_evaluation,loan_purpose_name,Loan purpose and type,63.212974,240.887718,66.178193,66.606811,66.392502,0.214309,3.179528,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.028035,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
41,stage5c__realmlp__without_sensitive__test_eval...,applicant_income,Applicant income,64.962334,241.253136,107.282091,106.281577,106.781834,0.500257,41.819500,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,1,0.372210,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
42,stage5c__realmlp__without_sensitive__test_eval...,lien_status_name,Loan structure and lien status,64.962334,241.253136,81.746372,81.847139,81.796755,0.050384,16.834421,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,2,0.149833,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
43,stage5c__realmlp__without_sensitive__test_eval...,msamd_name,Geography and region,64.962334,241.253136,75.413455,74.575385,74.994420,0.419035,10.032086,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,3,0.089289,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
44,stage5c__realmlp__without_sensitive__test_eval...,owner_occupancy_name,Property and occupancy,64.962334,241.253136,73.933508,73.641430,73.787469,0.146039,8.825135,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,4,0.078547,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
45,stage5c__realmlp__without_sensitive__test_eval...,tract_income_ratio,Tract and area income context,64.962334,241.253136,73.653335,73.288383,73.470859,0.182476,8.508525,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,5,0.075729,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
46,stage5c__realmlp__without_sensitive__test_eval...,us_region,Geography and region,64.962334,241.253136,70.520643,72.414804,71.467724,0.947081,6.505389,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,6,0.057901,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
47,stage5c__realmlp__without_sensitive__test_eval...,hud_median_family_income,Tract and area income context,64.962334,241.253136,70.644345,69.486281,70.065313,0.579032,5.102979,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,7,0.045419,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...
48,stage5c__realmlp__without_sensitive__test_eval...,loan_purpose_name,Loan purpose and type,64.962334,241.253136,68.231242,67.977068,68.104155,0.127087,3.141821,...,b67a34138a7f7f956f5573a090132acf2ec44d87ac34cb...,42|43,True,False,False,True,8,0.027963,Potential proxy category only; this is not pro...,Stage 8 Recovery grouped permutation and Stage...

Sensitive importance is aggregate-only. It does not prove discrimination, fairness, causality, or legal compliance.

## 21. Local Attribution Method

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Effects use original target units. Local reference substitution is not SHAP, additive, or causal.

In [22]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_local_attributions_public.csv')
required=['effect_standard_deviation','effect_minimum','effect_maximum','mean_absolute_effect']
assert data[required].notna().all().all()
display(data.sort_values(['case_public_id','candidate_id','absolute_effect_rank']).head(20))
display({'public_rows': len(data), 'dispersion_complete': True, 'raw_sensitive_values': 0, 'method': 'reference substitution, not SHAP'})

,case_public_id,case_type,case_rank,row_id,candidate_id,semantic_feature_unit,feature_family,sensitive_block_flag,potential_proxy_category_flag,background_rows,...,effect_minimum,effect_maximum,mean_absolute_effect,absolute_effect_rank,direction,method,is_shap,is_causal,raw_sensitive_value_public,dispersion_standard_deviation_ddof
1,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,applicant_income,Applicant income,False,True,40,...,847.308088,2413.526920,2020.905320,1,raises prediction,local reference substitution,False,False,False,0
25,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,tract_income_ratio,Tract and area income context,False,True,40,...,386.621983,1612.160489,1240.327099,2,raises prediction,local reference substitution,False,False,False,0
0,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,agency_name,"Lender, respondent, and agency",False,True,40,...,0.000000,1044.391974,528.145435,3,raises prediction,local reference substitution,False,False,False,0
5,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,county_name,Geography and region,False,True,40,...,174.253103,828.934516,528.108191,4,raises prediction,local reference substitution,False,False,False,0
13,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,msamd_name,Geography and region,False,True,40,...,77.266890,588.880811,374.427550,5,raises prediction,local reference substitution,False,False,False,0
3,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,applicant_income_to_area_income,Tract and area income context,False,True,40,...,96.810020,689.158967,321.142488,6,raises prediction,local reference substitution,False,False,False,0
8,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,hud_median_family_income,Tract and area income context,False,True,40,...,-303.358847,793.794580,243.446991,7,lowers prediction,local reference substitution,False,False,False,0
9,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,lien_status_name,Loan structure and lien status,False,True,40,...,0.000000,2105.737528,196.420331,8,raises prediction,local reference substitution,False,False,False,0
6,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,family_units_per_1000_people,Engineered ratios and counts,False,False,40,...,-24.628009,235.424600,180.022673,9,raises prediction,local reference substitution,False,False,False,0
2,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,applicant_income_area_group,Other documented Features,False,False,40,...,0.000000,565.346472,139.973118,10,raises prediction,local reference substitution,False,False,False,0
11,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,loan_purpose_name,Loan purpose and type,False,True,40,...,0.000000,344.773260,125.478554,11,raises prediction,local reference substitution,False,False,False,0
12,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,loan_type_name,Loan purpose and type,False,True,40,...,0.000000,747.885861,121.055922,12,raises prediction,local reference substitution,False,False,False,0
19,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,population,Engineered ratios and counts,False,False,40,...,-1.680752,283.738074,120.978045,13,raises prediction,local reference substitution,False,False,False,0
22,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,respondent_id,"Lender, respondent, and agency",False,True,40,...,-308.261070,231.670385,99.743493,14,raises prediction,local reference substitution,False,False,False,0
15,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,owner_occupancy_name,Property and occupancy,False,True,40,...,0.000000,760.037774,95.004722,15,raises prediction,local reference substitution,False,False,False,0
17,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,owner_occupied_units,Property and occupancy,False,True,40,...,-83.877102,133.516137,84.780626,16,raises prediction,local reference substitution,False,False,False,0
26,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,us_region,Geography and region,False,True,40,...,0.000000,158.314976,76.233669,17,raises prediction,local reference substitution,False,False,False,0
4,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,census_tract_number,Geography and region,False,True,40,...,-212.446768,75.097562,68.783491,18,lowers prediction,local reference substitution,False,False,False,0
23,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,state_name,Geography and region,False,True,40,...,-233.556242,167.461028,57.360237,19,lowers prediction,local reference substitution,False,False,False,0
7,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,has_co_applicant,Engineered ratios and counts,False,False,40,...,-90.401259,0.000000,47.460661,20,lowers prediction,local reference substitution,False,False,False,0

{'public_rows': 1620,
 'dispersion_complete': True,
 'raw_sensitive_values': 0,
 'method': 'reference substitution, not SHAP'}

## 22. Official Blend Local Explanations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Effects use original target units. Local reference substitution is not SHAP, additive, or causal.

In [23]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_local_attributions_public.csv')
display(data[data.candidate_id=='stage4l__blend__without_sensitive'].sort_values(['case_public_id','absolute_effect_rank']).groupby('case_public_id').head(5))

,case_public_id,case_type,case_rank,row_id,candidate_id,semantic_feature_unit,feature_family,sensitive_block_flag,potential_proxy_category_flag,background_rows,...,effect_minimum,effect_maximum,mean_absolute_effect,absolute_effect_rank,direction,method,is_shap,is_causal,raw_sensitive_value_public,dispersion_standard_deviation_ddof
1,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,applicant_income,Applicant income,False,True,40,...,847.308088,2413.526920,2020.905320,1,raises prediction,local reference substitution,False,False,False,0
25,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,tract_income_ratio,Tract and area income context,False,True,40,...,386.621983,1612.160489,1240.327099,2,raises prediction,local reference substitution,False,False,False,0
0,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,agency_name,"Lender, respondent, and agency",False,True,40,...,0.000000,1044.391974,528.145435,3,raises prediction,local reference substitution,False,False,False,0
5,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,county_name,Geography and region,False,True,40,...,174.253103,828.934516,528.108191,4,raises prediction,local reference substitution,False,False,False,0
13,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,msamd_name,Geography and region,False,True,40,...,77.266890,588.880811,374.427550,5,raises prediction,local reference substitution,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1540,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage4l__blend__without_sensitive,applicant_income,Applicant income,False,True,40,...,328.230806,1176.980027,888.185533,1,raises prediction,local reference substitution,False,False,False,0
1564,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage4l__blend__without_sensitive,tract_income_ratio,Tract and area income context,False,True,40,...,-1158.844301,-41.564662,419.654337,2,lowers prediction,local reference substitution,False,False,False,0
1544,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage4l__blend__without_sensitive,county_name,Geography and region,False,True,40,...,138.526976,544.825932,377.928734,3,raises prediction,local reference substitution,False,False,False,0
1552,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage4l__blend__without_sensitive,msamd_name,Geography and region,False,True,40,...,0.000000,536.869089,337.696323,4,raises prediction,local reference substitution,False,False,False,0
1539,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage4l__blend__without_sensitive,agency_name,"Lender, respondent, and agency",False,True,40,...,0.000000,510.503441,270.884802,5,raises prediction,local reference substitution,False,False,False,0

## 23. RealMLP Local Explanations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Effects use original target units. Local reference substitution is not SHAP, additive, or causal.

In [24]:
data=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_local_attributions_public.csv')
display(data[data.candidate_id.str.startswith('stage5c__realmlp')].sort_values(['case_public_id','candidate_id','absolute_effect_rank']).groupby(['case_public_id','candidate_id']).head(5))
display(Markdown('Explicit identity and sensitive context are replaced as joint blocks. No raw sensitive value is published.'))

,case_public_id,case_type,case_rank,row_id,candidate_id,semantic_feature_unit,feature_family,sensitive_block_flag,potential_proxy_category_flag,background_rows,...,effect_minimum,effect_maximum,mean_absolute_effect,absolute_effect_rank,direction,method,is_shap,is_causal,raw_sensitive_value_public,dispersion_standard_deviation_ddof
28,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,applicant_income,Applicant income,False,True,40,...,936.439996,2480.842520,2056.082889,1,raises prediction,local reference substitution,False,False,False,0
53,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,tract_income_ratio,Tract and area income context,False,True,40,...,162.326431,1121.034236,743.932427,2,raises prediction,local reference substitution,False,False,False,0
40,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,msamd_name,Geography and region,False,True,40,...,18.627335,754.907942,463.649809,3,raises prediction,local reference substitution,False,False,False,0
46,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,population,Engineered ratios and counts,False,False,40,...,5.502298,490.892018,245.002271,4,raises prediction,local reference substitution,False,False,False,0
49,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,respondent_id,"Lender, respondent, and agency",False,True,40,...,-717.626304,575.788882,237.407678,5,lowers prediction,local reference substitution,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage5c__realmlp__without_sensitive__test_eval...,applicant_income,Applicant income,False,True,40,...,648.363827,1956.678751,1571.088909,1,raises prediction,local reference substitution,False,False,False,0
1598,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage5c__realmlp__without_sensitive__test_eval...,county_name,Geography and region,False,True,40,...,804.789809,1617.897341,1230.015700,2,raises prediction,local reference substitution,False,False,False,0
1618,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage5c__realmlp__without_sensitive__test_eval...,tract_income_ratio,Tract and area income context,False,True,40,...,-843.358620,-64.228324,447.828217,3,lowers prediction,local reference substitution,False,False,False,0
1594,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage5c__realmlp__without_sensitive__test_eval...,agency_name,"Lender, respondent, and agency",False,True,40,...,0.000000,636.222805,373.070616,4,raises prediction,local reference substitution,False,False,False,0
1606,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,stage5c__realmlp__without_sensitive__test_eval...,msamd_name,Geography and region,False,True,40,...,0.000000,713.644494,366.167938,5,raises prediction,local reference substitution,False,False,False,0

Explicit identity and sensitive context are replaced as joint blocks. No raw sensitive value is published.

## 24. Case Synthesis and Explanation Stability

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values. Effects use original target units. Local reference substitution is not SHAP, additive, or causal.

In [25]:
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_case_explanation_synthesis.csv'))
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_local_explanation_stability.csv'))
display(pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_local_prediction_reconciliation.csv').groupby(['candidate_id','status']).size().rename('case_count').to_frame())

,case_public_id,case_type,case_rank,row_id,stage4l_top_feature_units,realmlp_without_top_feature_units,realmlp_with_top_feature_units,top5_consensus_feature_units,top5_disagreement_feature_units,non_causal_warning
0,common_large_error__1,common_large_error,1,436983,applicant_income|tract_income_ratio|agency_nam...,applicant_income|tract_income_ratio|population...,applicant_income|tract_income_ratio|msamd_name...,applicant_income|msamd_name|tract_income_ratio,agency_name|county_name|population|respondent_id,"Reference substitution is not SHAP, additive, ..."
1,common_large_error__2,common_large_error,2,215439,applicant_income|tract_income_ratio|msamd_name...,applicant_income|tract_income_ratio|respondent...,applicant_income|tract_income_ratio|respondent...,applicant_income|msamd_name|tract_income_ratio,agency_name|county_name|population|respondent_id,"Reference substitution is not SHAP, additive, ..."
2,common_large_error__3,common_large_error,3,19494,applicant_income|msamd_name|agency_name|county...,applicant_income|respondent_id|msamd_name|agen...,msamd_name|respondent_id|applicant_income|coun...,applicant_income|msamd_name,agency_name|county_name|respondent_id|sensitiv...,"Reference substitution is not SHAP, additive, ..."
3,common_large_error__4,common_large_error,4,353835,applicant_income|tract_income_ratio|msamd_name...,applicant_income|tract_income_ratio|respondent...,applicant_income|respondent_id|tract_income_ra...,applicant_income|msamd_name|tract_income_ratio,agency_name|county_name|explicit_sensitive_ide...,"Reference substitution is not SHAP, additive, ..."
4,common_large_error__5,common_large_error,5,170281,applicant_income|hud_median_family_income|fami...,applicant_income|family_units_per_1000_people|...,applicant_income|family_units_per_1000_people|...,applicant_income|family_units_per_1000_people|...,agency_name|explicit_sensitive_identity_block|...,"Reference substitution is not SHAP, additive, ..."
5,sensitive_improvement__1,deep_with_improves_over_without,1,299724,applicant_income|county_name|tract_income_rati...,applicant_income|county_name|loan_purpose_name...,applicant_income|county_name|respondent_id|msa...,applicant_income|county_name,agency_name|applicant_income_to_area_income|fa...,"Reference substitution is not SHAP, additive, ..."
6,sensitive_improvement__2,deep_with_improves_over_without,2,196215,applicant_income|agency_name|hud_median_family...,applicant_income|county_name|hud_median_family...,explicit_sensitive_identity_block|applicant_in...,agency_name|applicant_income,county_name|explicit_sensitive_identity_block|...,"Reference substitution is not SHAP, additive, ..."
7,sensitive_improvement__3,deep_with_improves_over_without,3,304158,applicant_income|tract_income_ratio|agency_nam...,applicant_income|msamd_name|loan_purpose_name|...,applicant_income|respondent_id|msamd_name|trac...,applicant_income|msamd_name,agency_name|applicant_income_to_area_income|lo...,"Reference substitution is not SHAP, additive, ..."
8,sensitive_improvement__4,deep_with_improves_over_without,4,195484,applicant_income|tract_income_ratio|county_nam...,applicant_income|county_name|respondent_id|tra...,applicant_income|respondent_id|county_name|msa...,applicant_income|county_name|tract_income_ratio,agency_name|applicant_income_to_area_income|ms...,"Reference substitution is not SHAP, additive, ..."
9,sensitive_improvement__5,deep_with_improves_over_without,5,343560,applicant_income|tract_income_ratio|hud_median...,applicant_income|tract_income_ratio|hud_median...,applicant_income|explicit_sensitive_identity_b...,applicant_income|hud_median_family_income|trac...,agency_name|county_name|explicit_sensitive_ide...,"Reference substitution is not SHAP, additive, ..."
10,realmlp_without_beats_stage4l__1,deep_without_beats_stage4l,1,303221,applicant_income|tract_income_ratio|county_nam...,applicant_income|county_name|tract_income_rati...,applicant_income|county_name|tract_income_rati...,applicant_income|county_name|tract_income_ratio,agency_name|applicant_income_to_area_income|ms...,"Reference substitution is not SHAP, additive, ..."
11,realmlp_without_beats_stage4l__2,deep_without_beats_stage4l,2,312109,applicant_income|tract_income_ratio|owner_occu...,applicant_income|tract_income_ratio|county_nam...,applicant_income|tract_income_ratio|owner_occu...,applicant_income|county_name|owner_occupancy_n...,msamd_name|respondent_id,"Reference substitution is not SHAP, additive, ..."
12,realmlp_without_beats_stage4l__3,deep_without_beats_stage4l,3,274138,applicant_income|tract_income_ratio|agency_nam...,respondent_id|applicant_income|tract_income_ra...,applicant_income|tract_income_ratio|msamd_name...,agency_name|applicant_income|msamd_name|tract_...,county_name|respondent_id,"Reference substitution is not SHAP, additive, ..."
13,realmlp_without_beats_stage4l__4,deep_without_beats_stage4l,4,317807,applicant_income|tract_income_ratio|county_nam...,applicant_income|county_name|respondent_id|tra...,applicant_income|county_name|respondent_id|msa...,applicant_income|county_name|tract_income_ratio,agency_name|applicant_income_to_area_income|ms...,"Reference substitution is not SHAP, additive, ..."
14,realmlp_without_beats_stage4l__5,deep_without_beats_stage4l,5,360147,applicant_income|family_units_per_1000_people|...,applicant_income|family_units_per_1000_people|...,applicant_income|family_units_per_1000_people|...,applicant_income|family_units_per_1000_people|...,agency_name|population|respondent_id,"Reference substitution is not SHAP, additive, ..."
15,stage4l_beats_realmlp_without__1,stage4l_beats_deep_without,1,273781,applicant_income|hud_median_family_income|owne...,applicant_income|respondent_id|county_name|tra...,applicant_income|respondent_id|owner_occupancy...,applicant_income|owner_occupancy_name|tract_in...,agency_name|county_name|hud_median_family_inco...,"Reference substitution is not SHAP, additive, ..."
16,stage4l_beats_realmlp_without__2,stage4l_beats_deep_without,2,234600,applicant_income|tract_income_ratio|hud_median...,respondent_id|applicant_income|tract_income_ra...,applicant_income|respondent_id|tract_income_ra...,agency_name|applicant_income|tract_income_ratio,applicant_income_to_area_income|hud_median_fam...,"Reference substitution is not SHAP, additive, ..."
17,stage4l_beats_realmlp_without__3,stage4l_beats_deep_without,3,251605,applicant_income|family_units_per_1000_people|...,applicant_income|respondent_id|family_units_pe...,applicant_income|respondent_id|family_units_pe...,applicant_income|family_units_per_1000_people|...,agency_name|county_name|owner_occupancy_name|o...,"Reference substitution is not SHAP, additive, ..."
18,stage4l_beats_realmlp_without__4,stage4l_beats_deep_without,4,381977,applicant_income|owner_occupancy_name|msamd_na...,applicant_income|county_name|owner_occupancy_n...,applicant_income|county_name|msamd_name|owner_...,applicant_income|county_name|owner_occupancy_name,family_units_per_1000_people|msamd_name|sensit...,"Reference substitution is not SHAP, additive, ..."
19,stage4l_beats_realmlp_without__5,stage4l_beats_deep_without,5,380475,applicant_income|tract_income_ratio|county_nam...,applicant_income|county_name|tract_income_rati...,applicant_income|county_name|msamd_name|respon...,applicant_income|county_name|msamd_name,agency_name|respondent_id|sensitive_context_bl...,"Reference substitution is not SHAP, additive, ..."

,case_public_id,case_type,case_rank,row_id,candidate_id,background_first_rows,background_second_rows,spearman_rank_correlation,top_5_overlap,top_10_overlap,median_absolute_effect_difference,maximum_absolute_effect_difference,low_stability_flag
0,common_large_error__1,common_large_error,1,436983,stage4l__blend__without_sensitive,20,20,0.924298,5,9,12.678558,127.380036,False
1,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__without_sensitive__test_eval...,20,20,0.937778,5,9,10.943900,149.726974,False
2,common_large_error__1,common_large_error,1,436983,stage5c__realmlp__with_sensitive__test_evaluation,20,20,0.910783,4,8,13.996416,109.485673,False
3,sensitive_improvement__1,deep_with_improves_over_without,1,299724,stage4l__blend__without_sensitive,20,20,0.938950,4,9,15.361203,115.415563,False
4,sensitive_improvement__1,deep_with_improves_over_without,1,299724,stage5c__realmlp__without_sensitive__test_eval...,20,20,0.865299,5,9,10.962886,153.554318,False
5,sensitive_improvement__1,deep_with_improves_over_without,1,299724,stage5c__realmlp__with_sensitive__test_evaluation,20,20,0.970991,5,9,7.914440,119.518595,False
6,realmlp_without_beats_stage4l__1,deep_without_beats_stage4l,1,303221,stage4l__blend__without_sensitive,20,20,0.921245,5,9,19.603067,97.313640,False
7,realmlp_without_beats_stage4l__1,deep_without_beats_stage4l,1,303221,stage5c__realmlp__without_sensitive__test_eval...,20,20,0.911795,4,9,8.425763,163.775818,False
8,realmlp_without_beats_stage4l__1,deep_without_beats_stage4l,1,303221,stage5c__realmlp__with_sensitive__test_evaluation,20,20,0.955665,5,9,12.130834,115.310863,False
9,stage4l_beats_realmlp_without__1,stage4l_beats_deep_without,1,273781,stage4l__blend__without_sensitive,20,20,0.959707,5,10,11.539646,101.161897,False
10,stage4l_beats_realmlp_without__1,stage4l_beats_deep_without,1,273781,stage5c__realmlp__without_sensitive__test_eval...,20,20,0.976752,4,10,11.183332,171.515328,False
11,stage4l_beats_realmlp_without__1,stage4l_beats_deep_without,1,273781,stage5c__realmlp__with_sensitive__test_evaluation,20,20,0.978106,4,10,13.530547,97.437219,False

                                                           case_count
candidate_id                                       status
stage4l__blend__without_sensitive                  PASS            20
stage5c__realmlp__with_sensitive__test_evaluation  PASS            20
stage5c__realmlp__without_sensitive__test_evalu... PASS            20

## 25. Explainability Limitations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [26]:
text=(RECOVERY_RESULTS/'stage8_recovery_feature_interpretation_report.md').read_text(encoding='utf-8')
display(Markdown(text))

# Stage 8 Recovery Feature Interpretation Report

> This is Post-Test descriptive explainability. Stage 4L remains the official pre-registered primary.

## Scope
Exactly three frozen Candidate predictors and five frozen model identities are described. No model is selected or changed.

## Corrected sample
The Recovery uses exactly 2,000 Test rows sampled from saved Stage 5C target deciles, with 200 rows per decile. The 40-row background has four rows per saved decile.

## Global methods
Common grouped permutation uses original target units, seeds 42 and 43, and the same semantic-unit row permutations. Saved native Importance, saved native SHAP, and saved Stage 5A attribution are reuse-only.

## Official blend
The Stage 4L blend is explained by original-scale grouped permutation. Component SHAP values are not added because their output scales differ.

## RealMLP
Both RealMLP modes use the frozen Stage 5C models. The sensitive mode uses joint explicit-identity and sensitive-context blocks.

## Cross-model evidence
Applicant income and lien status are leading units across the three Candidates, while geography, income context, and occupancy ranks vary.

## Cross-method evidence
Rank agreement varies across native Importance, saved SHAP, saved Deep attribution, and grouped permutation. Disagreement is descriptive and is not model failure.

## Local evidence
The Recovery saved 64,800 reference effects for 20 cases, three Candidates, all semantic units, and 40 background rows. Standard deviation uses population ddof=0.

## Local stability
Four frozen visualization cases are compared across the first and second 20-row background halves. Background membership was not changed after results.

## Sensitive privacy
Public outputs include no raw sensitive identity or tract-context value. Joint replacement blocks are used rather than sums of one-at-a-time effects.

## Potential proxies
Geography, lender, income, property, loan-purpose, and lien categories are only potential-proxy warnings. They do not prove proxy behavior.

## Causal limitation
Permutation and reference substitution describe model behavior. They do not identify causes or realistic policy interventions.

## Fairness limitation
Sensitive importance neither proves nor disproves fairness, discrimination, or legal compliance. Stage 7 contains the descriptive subgroup analysis.

## Post-Test limitation
Test was consumed in Stage 4L. These explanations cannot promote a Candidate or provide another unbiased performance comparison.

## Initial attempt
The initial Stage 8 sample, background, affected explanations, figures, Registry rows, summary, and Handoff remain preserved as invalidated audit evidence.

## Stage 9
Stage 9 must reuse the final Recovery artifacts and must not rerun model inference or explainability.

## 26. Stage 8 Visualizations

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [27]:
data=json.loads((RECOVERY_MANIFESTS/'stage8_recovery_visualization_manifest.json').read_text(encoding='utf-8'))
display({'status': data['status'], 'figure_count': data['figure_count'], 'plotting_data_count': data['plotting_data_count'], 'invalid_initial_figures_counted': data['invalid_initial_figures_counted'], 'public_raw_sensitive_values': data['public_raw_sensitive_values']})
display(pd.DataFrame(data['figures'])[['figure_id','title','method','sample_role','sample_row_count','privacy_status']])

{'status': 'PASS',
 'figure_count': 15,
 'plotting_data_count': 15,
 'invalid_initial_figures_counted': 0,
 'public_raw_sensitive_values': 0}

,figure_id,title,method,sample_role,sample_row_count,privacy_status
0,1,Explainability artifact coverage and provenance,saved SHAP provenance,saved Train-only SHAP samples,300,PASS — aggregate or public-case identifiers on...
1,2,Official Stage 4L blend grouped permutation Im...,grouped permutation,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
2,3,RealMLP without-sensitive grouped permutation ...,grouped permutation,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
3,4,RealMLP with-sensitive grouped permutation Imp...,grouped permutation,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
4,5,Cross-model Feature-rank heatmap,cross-model rank comparison,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
5,6,Feature-family importance-share comparison,grouped permutation feature-family share,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
6,7,CatBoost native Importance versus SHAP rank ag...,native importance versus saved SHAP rank,saved Train-only SHAP sample,300,PASS — aggregate or public-case identifiers on...
7,8,LightGBM native Importance versus SHAP rank ag...,native importance versus saved SHAP rank,saved Train-only SHAP sample,300,PASS — aggregate or public-case identifiers on...
8,9,XGBoost native Importance versus SHAP rank agr...,native importance versus saved SHAP rank,saved Train-only SHAP sample,300,PASS — aggregate or public-case identifiers on...
9,10,Saved Deep attribution versus Stage 8 Deep per...,saved Deep attribution versus Recovery grouped...,Stage 5A Train-only plus corrected saved-decil...,2000,PASS — aggregate or public-case identifiers on...
10,11,Explicit-sensitive and contextual-sensitive ag...,aggregate grouped permutation sensitive blocks,corrected saved-decile Test sample,2000,PASS — aggregate or public-case identifiers on...
11,12,Local effects for one frozen common-large-erro...,local reference substitution,frozen public cases and corrected background,40,PASS — aggregate or public-case identifiers on...
12,13,Local effects for one frozen Stage 4L-versus-R...,local reference substitution,frozen public cases and corrected background,40,PASS — aggregate or public-case identifiers on...
13,14,Local effects and background stability for the...,local reference substitution and background-ha...,frozen public cases and corrected background,40,PASS — aggregate or public-case identifiers on...
14,15,Stage 8 global and local explainability dashboard,Recovery evidence dashboard,Recovery summary,2000,PASS — aggregate or public-case identifiers on...

## 27. Registry Update

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [28]:
rows=pd.read_csv(RECOVERY_RESULTS/'stage8_recovery_registry_rows.csv')
adjudication=json.loads((REPORTS/'stage8_registry_governance_adjudication.json').read_text(encoding='utf-8'))
display(rows[['experiment_id','status','notes']])
display({'path': adjudication['registry_resolution_path'], 'status': adjudication['status'], 'exact_old_bytes_found': adjudication['exact_pre_stage8_bytes_found'], 'first_378_semantic_rows_validated': adjudication['first_378_semantic_rows_validated'], 'existing_386_bytes_modified': adjudication['existing_386_bytes_modified'], 'recovery_rows_appended': adjudication['recovery_rows_appended'], 'second_action': adjudication['second_action'], 'raw_prefix_preservation_claimed': adjudication['raw_prefix_preservation_claimed']})

,experiment_id,status,notes
0,stage8r1__stage4l_official__global_explanation,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
1,stage8r1__realmlp_without_sensitive__global_ex...,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
2,stage8r1__realmlp_with_sensitive__global_expla...,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
3,stage8r1__tree_shap__synthesis,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
4,stage8r1__cross_model__feature_comparison,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
5,stage8r1__local_cases__explanations,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
6,stage8r1__explainability_summary,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...
7,stage8r1__stage9_handoff,PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEP...,Stage 8 saved-decile Recovery; supersedes inva...

{'path': 'Path B',
 'status': 'PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEPTION',
 'exact_old_bytes_found': False,
 'first_378_semantic_rows_validated': True,
 'existing_386_bytes_modified': False,
 'recovery_rows_appended': 8,
 'second_action': 'REUSED',
 'raw_prefix_preservation_claimed': False}

## 28. Stage 9 Handoff

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [29]:
data=json.loads((RECOVERY_MANIFESTS/'stage8_recovery_stage9_handoff.json').read_text(encoding='utf-8'))
display(data)
display(Markdown('Stage 9 is not started. Final handoff activation waits for Recovery Reviewer and Verification closure.'))

{'artifacts': {'corrected_local_public_summary': {'path': 'artifacts/results/stage8/recovery/stage8_recovery_local_attributions_public.csv',
   'sha256': 'a06d244e3d5ea2b4ac53c66a102df58df5411743f1d60206bab9751845129dd5',
   'size_bytes': 526735},
  'corrected_local_reference_effects': {'path': 'artifacts/results/stage8/recovery/stage8_recovery_local_reference_effects.csv.gz',
   'sha256': '77db6a7bcdbc670976ba7720a504e8e8250093fe066d74213fa8e82eb5cf5ca4',
   'size_bytes': 1104854},
  'corrected_permutation': {'path': 'artifacts/results/stage8/recovery/stage8_recovery_common_permutation_importance.csv',
   'sha256': 'f020e8f9839b11db2def0813b025341e8d41915ac4d394e06ae0ae3601963b1e',
   'size_bytes': 37429},
  'global_summary': {'path': 'artifacts/results/stage8/recovery/stage8_recovery_global_explanation_summary.json',
   'sha256': '17a8c5f6fb178c75b6fa1ced9fb19a7804f6a718bf3f5857dca2c1b4e48930b6',
   'size_bytes': 8721},
  'interpretation_report': {'path': 'artifacts/results/stage8/recovery/stage8_recovery_feature_interpretation_report.md',
   'sha256': '8b03d228c201b006a260473deecab6ee69ad7664479d92f87886ca05372c3c3b',
   'size_bytes': 2860},
  'recovery_figures': {'path': 'artifacts/manifests/stage8/recovery/stage8_recovery_visualization_manifest.json',
   'sha256': '1cc8cf6778c32dcf3dd3fa2eaaee72826121db4c1614a4847d7cfefdfc17d8e8',
   'size_bytes': 18462},
  'registry_adjudication': {'path': 'artifacts/reports/stage8_registry_governance_adjudication.json',
   'sha256': '8bea517f8e0baa3809e63d8efc82a94de78748e98a028b1f3bd6c40ebfea0d9c',
   'size_bytes': 4778},
  'valid_reused_native_importance': {'path': 'artifacts/results/stage8/explainability/stage8_existing_importance_long.csv',
   'sha256': '38c315433c1339a74676ff00de6f1c10e50221831930abd8d25d2bb43b39f5f9',
   'size_bytes': 205091},
  'valid_reused_saved_shap': {'path': 'artifacts/reports/stage8_recovery_existing_shap_provenance.json',
   'sha256': 'b199942745dea9e873562d6aea60fbe81a209562155c3f2f3fecb13711538e12',
   'size_bytes': 7371},
  'valid_stage5a_attribution': {'path': 'artifacts/results/stage5/deep_core/summary/stage5a2_feature_attribution.csv',
   'sha256': 'e75e7ce1d85ea7d0b5d817a199a67a18c9cd63d0d952821c106df4faa9ed6c88',
   'size_bytes': 3776}},
 'authorization_id': 'stage8_saved_decile_registry_recovery_20260716',
 'candidate_ids': ['stage4l__blend__without_sensitive',
  'stage5c__realmlp__without_sensitive__test_evaluation',
  'stage5c__realmlp__with_sensitive__test_evaluation'],
 'causal_conclusion': 'none',
 'global_shap_recomputations': 0,
 'initial_stage8_explanation_inference_invalidated': True,
 'model_fit_calls': 0,
 'model_ids': ['stage4l__catboost__without_sensitive',
  'stage4l__lightgbm__without_sensitive',
  'stage4l__xgboost__without_sensitive',
  'stage5c__realmlp__without_sensitive__test_evaluation',
  'stage5c__realmlp__with_sensitive__test_evaluation'],
 'model_selection_performed': False,
 'new_evaluation_prediction_files': 0,
 'next_stage': 'Blocked until final Recovery Reviewer and Verification closure',
 'preprocessing_fit_calls': 0,
 'public_raw_sensitive_values': 0,
 'recovery_reviewer_path': 'artifacts/reports/stage8_reviewer.md',
 'recovery_verification_path': 'artifacts/reports/stage8_verification.json',
 'registry_status': 'PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEPTION',
 'stage4l_remains_official': True,
 'stage9_must_not_rerun_explainability': True,
 'stage9_must_preserve_registry_governance_disclosure': True,
 'stage9_started': False,
 'stage_id': 'stage8',
 'status': 'PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEPTION_PENDING_NOTEBOOK_AND_REVIEW',
 'summary_status': 'PASS_PENDING_REGISTRY_NOTEBOOK_REVIEW'}

Stage 9 is not started. Final handoff activation waits for Recovery Reviewer and Verification closure.

## 29. Independent Review and Verification

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [30]:
preparation=json.loads((REPORTS/'stage8_recovery_notebook_preparation.json').read_text(encoding='utf-8'))
invalidation=json.loads((RECOVERY_MANIFESTS/'stage8_initial_attempt_invalidation_manifest.json').read_text(encoding='utf-8'))
display(preparation)
display({'initial_attempt_status': invalidation['status'], 'invalidated_artifact_count': invalidation['entry_count'], 'final_independent_review_occurs_after_both_notebook_runs': True})

{'authorization_id': 'stage8_saved_decile_registry_recovery_20260716',
 'complete_local_dispersion_validated': True,
 'figures_validated': True,
 'notebook_artifact_loading_only_required': True,
 'registry_path_b_validated': True,
 'reviewer_finalization_occurs_after_two_notebook_runs': True,
 'scientific_artifacts_validated': True,
 'stage9_started': False,
 'status': 'PASS'}

{'initial_attempt_status': 'invalidated_by_stage8_saved_decile_recovery',
 'invalidated_artifact_count': 53,
 'final_independent_review_occurs_after_both_notebook_runs': True}

## 30. Stage 8 Completion Note

This section loads compact saved evidence. It does not train, tune, select, recompute SHAP, or expose raw sensitive values.

In [31]:
summary=json.loads((RECOVERY_RESULTS/'stage8_recovery_global_explanation_summary.json').read_text(encoding='utf-8'))
coverage=json.loads((REPORTS/'stage8_recovery_local_coverage.json').read_text(encoding='utf-8'))
adjudication=json.loads((REPORTS/'stage8_registry_governance_adjudication.json').read_text(encoding='utf-8'))
display({'stage': 'Stage 8 Recovery', 'current_execution_gate': 'PASS_PENDING_FINAL_INDEPENDENT_REVIEW', 'registry_status': adjudication['status'], 'sample_hash': json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text())['sample']['row_id_hash'], 'background_hash': json.loads((REPORTS/'stage8_recovery_sample_freeze.json').read_text())['background']['row_id_hash'], 'local_reference_rows': coverage['actual_cartesian_rows'], 'dispersion_complete': coverage['dispersion_complete'], 'model_fit_calls': summary['model_fit_calls'], 'preprocessing_fit_calls': summary['preprocessing_fit_calls'], 'global_shap_recomputations': summary['global_shap_recomputations'], 'new_evaluation_prediction_files': summary['new_evaluation_prediction_files'], 'stage4l_official': summary['stage4l_remains_official'], 'initial_invalid_attempt_disclosed': True, 'stage9_started': False})

{'stage': 'Stage 8 Recovery',
 'current_execution_gate': 'PASS_PENDING_FINAL_INDEPENDENT_REVIEW',
 'registry_status': 'PASS_WITH_DOCUMENTED_REGISTRY_GOVERNANCE_EXCEPTION',
 'sample_hash': 'd7791b5e12cae7d6069419efdb1e4a9bc28c586cb1bc5ae2584d1b08c3a0358f',
 'background_hash': '80a30da8f60aa3b5db6ec82847bfc0490359bc2412c3329ceb1f9915bfeb2efd',
 'local_reference_rows': 64800,
 'dispersion_complete': True,
 'model_fit_calls': 0,
 'preprocessing_fit_calls': 0,
 'global_shap_recomputations': 0,
 'new_evaluation_prediction_files': 0,
 'stage4l_official': True,
 'initial_invalid_attempt_disclosed': True,
 'stage9_started': False}