# Data Cleaning for Main Data

## Overview

This notebook cleans the 2017 HMDA loan data and prepares final datasets for modeling. The original file is very large, so most steps read and write the data in chunks. The work includes column cleaning, row filtering, target creation, invalid value checks, feature checks, final column selection, and sampling for classification and regression.

## Step 1: Drop Unneeded Columns

In this step, the code removes columns that are not useful for modeling. Some columns have too many missing values, some are administrative fields, and some can create data leakage because they are known only after the loan decision. The file is read in chunks to save memory. After this step, the dataset has 51 columns and 14,285,496 rows.

In [3]:
import pandas as pd
from pathlib import Path

# Input and output paths
DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_nationwide_all-records_labels\hmda_2017_nationwide_all-records_labels.csv")
OUTPUT_PATH = Path("hmda_2017_cleaned_columns_only.csv")

CHUNK_SIZE = 200_000

# Columns to drop based on high missingness, leakage risk, or useless administrative meaning
columns_to_drop = [
    # Administrative / data quality columns
    "edit_status_name",
    "edit_status",
    "sequence_number",
    "application_date_indicator",

    # Applicant race detail columns with extremely high missingness
    "applicant_race_name_2",
    "applicant_race_2",
    "applicant_race_name_3",
    "applicant_race_3",
    "applicant_race_name_4",
    "applicant_race_4",
    "applicant_race_name_5",
    "applicant_race_5",

    # Co-applicant race detail columns with extremely high missingness
    "co_applicant_race_name_2",
    "co_applicant_race_2",
    "co_applicant_race_name_3",
    "co_applicant_race_3",
    "co_applicant_race_name_4",
    "co_applicant_race_4",
    "co_applicant_race_name_5",
    "co_applicant_race_5",

    # Denial reason columns are post-decision information and cause data leakage
    "denial_reason_name_1",
    "denial_reason_1",
    "denial_reason_name_2",
    "denial_reason_2",
    "denial_reason_name_3",
    "denial_reason_3",

    # Rate spread is mostly missing and related to loan pricing after the decision
    "rate_spread"
]

# --------------------------------------------------
# 1. Read only the header to check original columns
# --------------------------------------------------
header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False
)

original_columns = header_df.columns.tolist()
original_column_count = len(original_columns)

existing_columns_to_drop = [
    col for col in columns_to_drop
    if col in original_columns
]

columns_not_found = [
    col for col in columns_to_drop
    if col not in original_columns
]

remaining_columns = [
    col for col in original_columns
    if col not in existing_columns_to_drop
]

print("Original column count:", original_column_count)
print("Columns selected for dropping:", len(existing_columns_to_drop))
print("Expected final column count:", len(remaining_columns))

print("\nColumns that will be dropped:")
for col in existing_columns_to_drop:
    print("-", col)

if columns_not_found:
    print("\nColumns requested for dropping but not found:")
    for col in columns_not_found:
        print("-", col)

# --------------------------------------------------
# 2. Process the full dataset in chunks
# --------------------------------------------------
first_chunk = True
processed_rows = 0

for chunk in pd.read_csv(
    DATA_PATH,
    dtype=str,
    keep_default_na=False,
    na_filter=False,
    chunksize=CHUNK_SIZE
):
    # Drop selected columns
    chunk = chunk.drop(columns=existing_columns_to_drop)

    # Write the first chunk with header, then append the rest without header
    chunk.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False
    processed_rows += len(chunk)

    print(f"Processed rows: {processed_rows:,} | Current column count: {chunk.shape[1]}")

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())

# --------------------------------------------------
# 3. Check output file column count
# --------------------------------------------------
output_header_df = pd.read_csv(
    OUTPUT_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False
)

output_columns = output_header_df.columns.tolist()

print("\nFinal check:")
print("Original column count:", original_column_count)
print("Dropped column count:", len(existing_columns_to_drop))
print("Output column count:", len(output_columns))

if len(output_columns) == len(remaining_columns):
    print("Column count check: PASSED")
else:
    print("Column count check: FAILED")

# --------------------------------------------------
# 4. Optional: check row count of output file
# --------------------------------------------------
output_row_count = 0

for chunk in pd.read_csv(
    OUTPUT_PATH,
    dtype=str,
    keep_default_na=False,
    na_filter=False,
    chunksize=CHUNK_SIZE
):
    output_row_count += len(chunk)

print("\nOutput row count:", f"{output_row_count:,}")

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:5: SyntaxWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1484\1853778600.py:5: SyntaxWarning: invalid escape sequence '\S'
  DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_nationwide_all-records_labels\hmda_2017_nationwide_all-records_labels.csv")

Original column count: 78
Columns selected for dropping: 27
Expected final column count: 51

Columns that will be dropped:
- edit_status_name
- edit_status
- sequence_number
- application_date_indicator
- applicant_race_name_2
- applicant_race_2
- applicant_race_name_3
- applicant_race_3
- applicant_race_name_4
- applicant_race_4
- applicant_race_name_5
- applicant_race_5
- co_applicant_race_name_2
- co_applicant_race_2
- co_applicant_race_name_3
- co_applicant_race_3
- co_applicant_race_name_4
- co_applicant_race_4
- co_applicant_race_name_5
- co_applicant_race_5
- denial_reason_name_1
- denial_reason_1
- denial_reason_name_2
- denial_reason_2
- denial_reason_name_3
- denial_reason_3
- rate_spread
Processed rows: 200,000 | Current column count: 51
Processed rows: 400,000 | Current column count: 51
Processed rows: 600,000 | Current column count: 51
Processed rows: 800,000 | Current column count: 51
Processed rows: 1,000,000 | Current column count: 51
Processed rows: 1,200,000 | Current column count: 51
Processed rows: 1,400,000 | Current column count: 51
Processed rows: 1,600,000 | Current column count: 51
Processed rows: 1,800,000 | Current column count: 51
Processed rows: 2,000,000 | Current column count: 51
Processed rows: 2,200,000 | Current column count: 51
Processed rows: 2,400,000 | Current column count: 51
Processed rows: 2,600,000 | Current column count: 51
Processed rows: 2,800,000 | Current column count: 51
Processed rows: 3,000,000 | Current column count: 51
Processed rows: 3,200,000 | Current column count: 51
Processed rows: 3,400,000 | Current column count: 51
Processed rows: 3,600,000 | Current column count: 51
Processed rows: 3,800,000 | Current column count: 51
Processed rows: 4,000,000 | Current column count: 51
Processed rows: 4,200,000 | Current column count: 51
Processed rows: 4,400,000 | Current column count: 51
Processed rows: 4,600,000 | Current column count: 51
Processed rows: 4,800,000 | Current column count: 51
Processed rows: 5,000,000 | Current column count: 51
Processed rows: 5,200,000 | Current column count: 51
Processed rows: 5,400,000 | Current column count: 51
Processed rows: 5,600,000 | Current column count: 51
Processed rows: 5,800,000 | Current column count: 51
Processed rows: 6,000,000 | Current column count: 51
Processed rows: 6,200,000 | Current column count: 51
Processed rows: 6,400,000 | Current column count: 51
Processed rows: 6,600,000 | Current column count: 51
Processed rows: 6,800,000 | Current column count: 51
Processed rows: 7,000,000 | Current column count: 51
Processed rows: 7,200,000 | Current column count: 51
Processed rows: 7,400,000 | Current column count: 51
Processed rows: 7,600,000 | Current column count: 51
Processed rows: 7,800,000 | Current column count: 51
Processed rows: 8,000,000 | Current column count: 51
Processed rows: 8,200,000 | Current column count: 51
Processed rows: 8,400,000 | Current column count: 51
Processed rows: 8,600,000 | Current column count: 51
Processed rows: 8,800,000 | Current column count: 51
Processed rows: 9,000,000 | Current column count: 51
Processed rows: 9,200,000 | Current column count: 51
Processed rows: 9,400,000 | Current column count: 51
Processed rows: 9,600,000 | Current column count: 51
Processed rows: 9,800,000 | Current column count: 51
Processed rows: 10,000,000 | Current column count: 51
Processed rows: 10,200,000 | Current column count: 51
Processed rows: 10,400,000 | Current column count: 51
Processed rows: 10,600,000 | Current column count: 51
Processed rows: 10,800,000 | Current column count: 51
Processed rows: 11,000,000 | Current column count: 51
Processed rows: 11,200,000 | Current column count: 51
Processed rows: 11,400,000 | Current column count: 51
Processed rows: 11,600,000 | Current column count: 51
Processed rows: 11,800,000 | Current column count: 51
Processed rows: 12,000,000 | Current column count: 51
Processed rows: 12,200,000 | Current column count: 51
Processed rows: 12,400,000 | Current column count: 51
Processed rows: 12,600,000 | Current column count: 51
Processed rows: 12,800,000 | Current column count: 51
Processed rows: 13,000,000 | Current column count: 51
Processed rows: 13,200,000 | Current column count: 51
Processed rows: 13,400,000 | Current column count: 51
Processed rows: 13,600,000 | Current column count: 51
Processed rows: 13,800,000 | Current column count: 51
Processed rows: 14,000,000 | Current column count: 51
Processed rows: 14,200,000 | Current column count: 51
Processed rows: 14,285,496 | Current column count: 51

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_only.csv

Final check:
Original column count: 78
Dropped column count: 27
Output column count: 51
Column count check: PASSED

Output row count: 14,285,496

## Step 2: Remove Rows with Missing Important Values

This step removes rows that have missing or invalid values in important columns. These columns include income, loan amount, location, tract information, and population information. The code also treats values like empty strings, `NA`, `null`, `.`, and `-` as missing. After this step, 10,799,874 rows remain.

In [4]:
import pandas as pd
from pathlib import Path

# Input and output paths
DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_only.csv")
OUTPUT_PATH = Path("hmda_2017_cleaned_columns_and_rows.csv")

CHUNK_SIZE = 200_000

# Rows with missing values in these columns will be dropped
required_non_missing_columns = [
    "applicant_income_000s",
    "msamd_name",
    "msamd",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units",
    "census_tract_number",
    "population",
    "minority_population",
    "hud_median_family_income",
    "county_name",
    "county_code",
    "state_name",
    "state_abbr",
    "state_code",
    "loan_amount_000s"
]

# Values that should be treated as missing
missing_like_values = {
    "",
    " ",
    "nan", "NaN", "NAN",
    "none", "None", "NONE",
    "null", "Null", "NULL",
    "na", "NA", "N/A", "n/a",
    ".", "-", "--"
}

# --------------------------------------------------
# 1. Check available columns
# --------------------------------------------------
header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

available_columns = header_df.columns.tolist()

existing_required_columns = [
    col for col in required_non_missing_columns
    if col in available_columns
]

missing_required_columns = [
    col for col in required_non_missing_columns
    if col not in available_columns
]

print("Required columns found:", len(existing_required_columns))
print(existing_required_columns)

if missing_required_columns:
    print("\nRequired columns not found in file:")
    for col in missing_required_columns:
        print("-", col)

# --------------------------------------------------
# 2. Process full dataset chunk by chunk
# --------------------------------------------------
first_chunk = True
total_rows_before = 0
total_rows_after = 0
removed_rows_total = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    rows_before = len(chunk)
    total_rows_before += rows_before

    # Strip whitespace in required columns only
    for col in existing_required_columns:
        chunk[col] = chunk[col].astype(str).str.strip()

    # Build mask for rows that have missing-like values in any required column
    missing_mask = pd.Series(False, index=chunk.index)

    for col in existing_required_columns:
        missing_mask = missing_mask | chunk[col].isin(missing_like_values)

    # Keep only rows without missing values in required columns
    chunk_clean = chunk.loc[~missing_mask].copy()

    rows_after = len(chunk_clean)
    removed_rows = rows_before - rows_after

    total_rows_after += rows_after
    removed_rows_total += removed_rows

    # Write clean chunk to output file
    chunk_clean.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    print(
        f"Chunk {chunk_id} | "
        f"Before: {rows_before:,} | "
        f"After: {rows_after:,} | "
        f"Removed: {removed_rows:,} | "
        f"Total kept: {total_rows_after:,}"
    )

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())
print("Total rows before:", f"{total_rows_before:,}")
print("Total rows after:", f"{total_rows_after:,}")
print("Total rows removed:", f"{removed_rows_total:,}")
print("Removed percent:", round(removed_rows_total / total_rows_before * 100, 2), "%")

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:5: SyntaxWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1484\2502209208.py:5: SyntaxWarning: invalid escape sequence '\S'
  DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_only.csv")

Required columns found: 16
['applicant_income_000s', 'msamd_name', 'msamd', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units', 'census_tract_number', 'population', 'minority_population', 'hud_median_family_income', 'county_name', 'county_code', 'state_name', 'state_abbr', 'state_code', 'loan_amount_000s']
Chunk 1 | Before: 200,000 | After: 160,867 | Removed: 39,133 | Total kept: 160,867
Chunk 2 | Before: 200,000 | After: 153,765 | Removed: 46,235 | Total kept: 314,632
Chunk 3 | Before: 200,000 | After: 162,444 | Removed: 37,556 | Total kept: 477,076
Chunk 4 | Before: 200,000 | After: 153,688 | Removed: 46,312 | Total kept: 630,764
Chunk 5 | Before: 200,000 | After: 154,524 | Removed: 45,476 | Total kept: 785,288
Chunk 6 | Before: 200,000 | After: 154,805 | Removed: 45,195 | Total kept: 940,093
Chunk 7 | Before: 200,000 | After: 152,257 | Removed: 47,743 | Total kept: 1,092,350
Chunk 8 | Before: 200,000 | After: 151,019 | Removed: 48,981 | Total kept: 1,243,369
Chunk 9 | Before: 200,000 | After: 150,468 | Removed: 49,532 | Total kept: 1,393,837
Chunk 10 | Before: 200,000 | After: 155,022 | Removed: 44,978 | Total kept: 1,548,859
Chunk 11 | Before: 200,000 | After: 153,953 | Removed: 46,047 | Total kept: 1,702,812
Chunk 12 | Before: 200,000 | After: 151,931 | Removed: 48,069 | Total kept: 1,854,743
Chunk 13 | Before: 200,000 | After: 148,245 | Removed: 51,755 | Total kept: 2,002,988
Chunk 14 | Before: 200,000 | After: 148,635 | Removed: 51,365 | Total kept: 2,151,623
Chunk 15 | Before: 200,000 | After: 156,816 | Removed: 43,184 | Total kept: 2,308,439
Chunk 16 | Before: 200,000 | After: 153,550 | Removed: 46,450 | Total kept: 2,461,989
Chunk 17 | Before: 200,000 | After: 150,103 | Removed: 49,897 | Total kept: 2,612,092
Chunk 18 | Before: 200,000 | After: 151,461 | Removed: 48,539 | Total kept: 2,763,553
Chunk 19 | Before: 200,000 | After: 145,981 | Removed: 54,019 | Total kept: 2,909,534
Chunk 20 | Before: 200,000 | After: 153,319 | Removed: 46,681 | Total kept: 3,062,853
Chunk 21 | Before: 200,000 | After: 155,201 | Removed: 44,799 | Total kept: 3,218,054
Chunk 22 | Before: 200,000 | After: 151,717 | Removed: 48,283 | Total kept: 3,369,771
Chunk 23 | Before: 200,000 | After: 148,984 | Removed: 51,016 | Total kept: 3,518,755
Chunk 24 | Before: 200,000 | After: 150,353 | Removed: 49,647 | Total kept: 3,669,108
Chunk 25 | Before: 200,000 | After: 151,876 | Removed: 48,124 | Total kept: 3,820,984
Chunk 26 | Before: 200,000 | After: 149,958 | Removed: 50,042 | Total kept: 3,970,942
Chunk 27 | Before: 200,000 | After: 151,100 | Removed: 48,900 | Total kept: 4,122,042
Chunk 28 | Before: 200,000 | After: 153,422 | Removed: 46,578 | Total kept: 4,275,464
Chunk 29 | Before: 200,000 | After: 150,112 | Removed: 49,888 | Total kept: 4,425,576
Chunk 30 | Before: 200,000 | After: 150,203 | Removed: 49,797 | Total kept: 4,575,779
Chunk 31 | Before: 200,000 | After: 154,195 | Removed: 45,805 | Total kept: 4,729,974
Chunk 32 | Before: 200,000 | After: 152,994 | Removed: 47,006 | Total kept: 4,882,968
Chunk 33 | Before: 200,000 | After: 152,407 | Removed: 47,593 | Total kept: 5,035,375
Chunk 34 | Before: 200,000 | After: 156,559 | Removed: 43,441 | Total kept: 5,191,934
Chunk 35 | Before: 200,000 | After: 152,125 | Removed: 47,875 | Total kept: 5,344,059
Chunk 36 | Before: 200,000 | After: 158,057 | Removed: 41,943 | Total kept: 5,502,116
Chunk 37 | Before: 200,000 | After: 153,394 | Removed: 46,606 | Total kept: 5,655,510
Chunk 38 | Before: 200,000 | After: 157,093 | Removed: 42,907 | Total kept: 5,812,603
Chunk 39 | Before: 200,000 | After: 155,256 | Removed: 44,744 | Total kept: 5,967,859
Chunk 40 | Before: 200,000 | After: 156,015 | Removed: 43,985 | Total kept: 6,123,874
Chunk 41 | Before: 200,000 | After: 153,305 | Removed: 46,695 | Total kept: 6,277,179
Chunk 42 | Before: 200,000 | After: 152,528 | Removed: 47,472 | Total kept: 6,429,707
Chunk 43 | Before: 200,000 | After: 153,014 | Removed: 46,986 | Total kept: 6,582,721
Chunk 44 | Before: 200,000 | After: 153,384 | Removed: 46,616 | Total kept: 6,736,105
Chunk 45 | Before: 200,000 | After: 148,517 | Removed: 51,483 | Total kept: 6,884,622
Chunk 46 | Before: 200,000 | After: 152,274 | Removed: 47,726 | Total kept: 7,036,896
Chunk 47 | Before: 200,000 | After: 146,843 | Removed: 53,157 | Total kept: 7,183,739
Chunk 48 | Before: 200,000 | After: 147,068 | Removed: 52,932 | Total kept: 7,330,807
Chunk 49 | Before: 200,000 | After: 142,989 | Removed: 57,011 | Total kept: 7,473,796
Chunk 50 | Before: 200,000 | After: 145,637 | Removed: 54,363 | Total kept: 7,619,433
Chunk 51 | Before: 200,000 | After: 148,207 | Removed: 51,793 | Total kept: 7,767,640
Chunk 52 | Before: 200,000 | After: 141,644 | Removed: 58,356 | Total kept: 7,909,284
Chunk 53 | Before: 200,000 | After: 139,416 | Removed: 60,584 | Total kept: 8,048,700
Chunk 54 | Before: 200,000 | After: 136,577 | Removed: 63,423 | Total kept: 8,185,277
Chunk 55 | Before: 200,000 | After: 144,994 | Removed: 55,006 | Total kept: 8,330,271
Chunk 56 | Before: 200,000 | After: 143,033 | Removed: 56,967 | Total kept: 8,473,304
Chunk 57 | Before: 200,000 | After: 135,650 | Removed: 64,350 | Total kept: 8,608,954
Chunk 58 | Before: 200,000 | After: 148,930 | Removed: 51,070 | Total kept: 8,757,884
Chunk 59 | Before: 200,000 | After: 146,992 | Removed: 53,008 | Total kept: 8,904,876
Chunk 60 | Before: 200,000 | After: 139,573 | Removed: 60,427 | Total kept: 9,044,449
Chunk 61 | Before: 200,000 | After: 145,947 | Removed: 54,053 | Total kept: 9,190,396
Chunk 62 | Before: 200,000 | After: 148,417 | Removed: 51,583 | Total kept: 9,338,813
Chunk 63 | Before: 200,000 | After: 148,815 | Removed: 51,185 | Total kept: 9,487,628
Chunk 64 | Before: 200,000 | After: 152,676 | Removed: 47,324 | Total kept: 9,640,304
Chunk 65 | Before: 200,000 | After: 153,277 | Removed: 46,723 | Total kept: 9,793,581
Chunk 66 | Before: 200,000 | After: 150,171 | Removed: 49,829 | Total kept: 9,943,752
Chunk 67 | Before: 200,000 | After: 155,547 | Removed: 44,453 | Total kept: 10,099,299
Chunk 68 | Before: 200,000 | After: 154,647 | Removed: 45,353 | Total kept: 10,253,946
Chunk 69 | Before: 200,000 | After: 160,370 | Removed: 39,630 | Total kept: 10,414,316
Chunk 70 | Before: 200,000 | After: 154,918 | Removed: 45,082 | Total kept: 10,569,234
Chunk 71 | Before: 200,000 | After: 162,568 | Removed: 37,432 | Total kept: 10,731,802
Chunk 72 | Before: 85,496 | After: 68,072 | Removed: 17,424 | Total kept: 10,799,874

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_and_rows.csv
Total rows before: 14,285,496
Total rows after: 10,799,874
Total rows removed: 3,485,622
Removed percent: 24.4 %

## Step 3: Create the Classification Target

This step keeps only loan actions that can be used for binary classification. Actions `1`, `2`, and `8` are treated as approved loans, and actions `3` and `7` are treated as rejected loans. A new column named `loan_approved` is created, where `1` means approved and `0` means rejected. After this step, 8,074,536 rows remain.

In [5]:
import pandas as pd
from pathlib import Path

# Input and output paths
DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_and_rows.csv")
OUTPUT_PATH = Path("hmda_2017_classification_ready.csv")

CHUNK_SIZE = 200_000

# Action values to keep
approved_actions = {"1", "2", "8"}
rejected_actions = {"3", "7"}
valid_actions = approved_actions | rejected_actions

# --------------------------------------------------
# Process full dataset chunk by chunk
# --------------------------------------------------
first_chunk = True
total_rows_before = 0
total_rows_after = 0
removed_rows_total = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    rows_before = len(chunk)
    total_rows_before += rows_before

    # Clean action_taken values
    chunk["action_taken"] = chunk["action_taken"].astype(str).str.strip()

    # Keep only action_taken values 1, 2, 3, 7, 8
    chunk = chunk[chunk["action_taken"].isin(valid_actions)].copy()

    # Create binary target column
    chunk["loan_approved"] = chunk["action_taken"].map(
        {
            "1": 1,
            "2": 1,
            "8": 1,
            "3": 0,
            "7": 0
        }
    )

    rows_after = len(chunk)
    removed_rows = rows_before - rows_after

    total_rows_after += rows_after
    removed_rows_total += removed_rows

    # Write cleaned chunk to output file
    chunk.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    print(
        f"Chunk {chunk_id} | "
        f"Before: {rows_before:,} | "
        f"After: {rows_after:,} | "
        f"Removed: {removed_rows:,} | "
        f"Total kept: {total_rows_after:,}"
    )

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())
print("Total rows before:", f"{total_rows_before:,}")
print("Total rows after:", f"{total_rows_after:,}")
print("Total rows removed:", f"{removed_rows_total:,}")
print("Removed percent:", round(removed_rows_total / total_rows_before * 100, 2), "%")

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:5: SyntaxWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1484\3598466782.py:5: SyntaxWarning: invalid escape sequence '\S'
  DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaned_columns_and_rows.csv")

Chunk 1 | Before: 200,000 | After: 149,006 | Removed: 50,994 | Total kept: 149,006
Chunk 2 | Before: 200,000 | After: 149,961 | Removed: 50,039 | Total kept: 298,967
Chunk 3 | Before: 200,000 | After: 150,901 | Removed: 49,099 | Total kept: 449,868
Chunk 4 | Before: 200,000 | After: 151,802 | Removed: 48,198 | Total kept: 601,670
Chunk 5 | Before: 200,000 | After: 151,945 | Removed: 48,055 | Total kept: 753,615
Chunk 6 | Before: 200,000 | After: 152,005 | Removed: 47,995 | Total kept: 905,620
Chunk 7 | Before: 200,000 | After: 151,269 | Removed: 48,731 | Total kept: 1,056,889
Chunk 8 | Before: 200,000 | After: 151,677 | Removed: 48,323 | Total kept: 1,208,566
Chunk 9 | Before: 200,000 | After: 150,850 | Removed: 49,150 | Total kept: 1,359,416
Chunk 10 | Before: 200,000 | After: 150,469 | Removed: 49,531 | Total kept: 1,509,885
Chunk 11 | Before: 200,000 | After: 148,618 | Removed: 51,382 | Total kept: 1,658,503
Chunk 12 | Before: 200,000 | After: 148,547 | Removed: 51,453 | Total kept: 1,807,050
Chunk 13 | Before: 200,000 | After: 150,129 | Removed: 49,871 | Total kept: 1,957,179
Chunk 14 | Before: 200,000 | After: 150,841 | Removed: 49,159 | Total kept: 2,108,020
Chunk 15 | Before: 200,000 | After: 150,021 | Removed: 49,979 | Total kept: 2,258,041
Chunk 16 | Before: 200,000 | After: 150,439 | Removed: 49,561 | Total kept: 2,408,480
Chunk 17 | Before: 200,000 | After: 148,698 | Removed: 51,302 | Total kept: 2,557,178
Chunk 18 | Before: 200,000 | After: 149,249 | Removed: 50,751 | Total kept: 2,706,427
Chunk 19 | Before: 200,000 | After: 149,554 | Removed: 50,446 | Total kept: 2,855,981
Chunk 20 | Before: 200,000 | After: 147,910 | Removed: 52,090 | Total kept: 3,003,891
Chunk 21 | Before: 200,000 | After: 147,394 | Removed: 52,606 | Total kept: 3,151,285
Chunk 22 | Before: 200,000 | After: 147,876 | Removed: 52,124 | Total kept: 3,299,161
Chunk 23 | Before: 200,000 | After: 147,730 | Removed: 52,270 | Total kept: 3,446,891
Chunk 24 | Before: 200,000 | After: 147,215 | Removed: 52,785 | Total kept: 3,594,106
Chunk 25 | Before: 200,000 | After: 147,771 | Removed: 52,229 | Total kept: 3,741,877
Chunk 26 | Before: 200,000 | After: 148,047 | Removed: 51,953 | Total kept: 3,889,924
Chunk 27 | Before: 200,000 | After: 147,033 | Removed: 52,967 | Total kept: 4,036,957
Chunk 28 | Before: 200,000 | After: 148,009 | Removed: 51,991 | Total kept: 4,184,966
Chunk 29 | Before: 200,000 | After: 147,985 | Removed: 52,015 | Total kept: 4,332,951
Chunk 30 | Before: 200,000 | After: 148,255 | Removed: 51,745 | Total kept: 4,481,206
Chunk 31 | Before: 200,000 | After: 148,544 | Removed: 51,456 | Total kept: 4,629,750
Chunk 32 | Before: 200,000 | After: 148,701 | Removed: 51,299 | Total kept: 4,778,451
Chunk 33 | Before: 200,000 | After: 149,002 | Removed: 50,998 | Total kept: 4,927,453
Chunk 34 | Before: 200,000 | After: 149,821 | Removed: 50,179 | Total kept: 5,077,274
Chunk 35 | Before: 200,000 | After: 149,525 | Removed: 50,475 | Total kept: 5,226,799
Chunk 36 | Before: 200,000 | After: 150,141 | Removed: 49,859 | Total kept: 5,376,940
Chunk 37 | Before: 200,000 | After: 150,157 | Removed: 49,843 | Total kept: 5,527,097
Chunk 38 | Before: 200,000 | After: 149,722 | Removed: 50,278 | Total kept: 5,676,819
Chunk 39 | Before: 200,000 | After: 150,400 | Removed: 49,600 | Total kept: 5,827,219
Chunk 40 | Before: 200,000 | After: 149,721 | Removed: 50,279 | Total kept: 5,976,940
Chunk 41 | Before: 200,000 | After: 150,346 | Removed: 49,654 | Total kept: 6,127,286
Chunk 42 | Before: 200,000 | After: 150,952 | Removed: 49,048 | Total kept: 6,278,238
Chunk 43 | Before: 200,000 | After: 150,383 | Removed: 49,617 | Total kept: 6,428,621
Chunk 44 | Before: 200,000 | After: 148,598 | Removed: 51,402 | Total kept: 6,577,219
Chunk 45 | Before: 200,000 | After: 150,091 | Removed: 49,909 | Total kept: 6,727,310
Chunk 46 | Before: 200,000 | After: 151,661 | Removed: 48,339 | Total kept: 6,878,971
Chunk 47 | Before: 200,000 | After: 150,509 | Removed: 49,491 | Total kept: 7,029,480
Chunk 48 | Before: 200,000 | After: 149,099 | Removed: 50,901 | Total kept: 7,178,579
Chunk 49 | Before: 200,000 | After: 150,017 | Removed: 49,983 | Total kept: 7,328,596
Chunk 50 | Before: 200,000 | After: 150,790 | Removed: 49,210 | Total kept: 7,479,386
Chunk 51 | Before: 200,000 | After: 149,540 | Removed: 50,460 | Total kept: 7,628,926
Chunk 52 | Before: 200,000 | After: 148,933 | Removed: 51,067 | Total kept: 7,777,859
Chunk 53 | Before: 200,000 | After: 149,950 | Removed: 50,050 | Total kept: 7,927,809
Chunk 54 | Before: 199,874 | After: 146,727 | Removed: 53,147 | Total kept: 8,074,536

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready.csv
Total rows before: 10,799,874
Total rows after: 8,074,536
Total rows removed: 2,725,338
Removed percent: 25.23 %

## Step 4: Remove Duplicate Rows

This step removes duplicate rows from the classification-ready file. Before checking duplicates, the code strips extra spaces from text values. Then it creates a hash for each row and keeps only rows that appear for the first time. After this step, 8,063,000 unique rows remain.

In [6]:
import pandas as pd
from pathlib import Path

# Input and output paths
DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready.csv")
OUTPUT_PATH = Path("hmda_2017_no_duplicates.csv")

CHUNK_SIZE = 200_000

# This set stores hashes of rows that have already been seen
seen_hashes = set()

first_chunk = True
total_rows_before = 0
total_rows_after = 0
total_duplicates_removed = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    rows_before = len(chunk)
    total_rows_before += rows_before

    # Normalize string values before hashing
    # This helps avoid treating " value " and "value" as different rows
    chunk = chunk.astype(str)
    chunk = chunk.apply(lambda col: col.str.strip())

    # Create a stable row hash based on all remaining columns
    row_hashes = pd.util.hash_pandas_object(
        chunk,
        index=False
    ).astype("uint64")

    # Keep rows whose hash has not been seen before
    keep_mask = []

    for h in row_hashes:
        h_int = int(h)

        if h_int in seen_hashes:
            keep_mask.append(False)
        else:
            keep_mask.append(True)
            seen_hashes.add(h_int)

    chunk_unique = chunk.loc[keep_mask].copy()

    rows_after = len(chunk_unique)
    duplicates_removed = rows_before - rows_after

    total_rows_after += rows_after
    total_duplicates_removed += duplicates_removed

    # Write unique rows to output file
    chunk_unique.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    print(
        f"Chunk {chunk_id} | "
        f"Before: {rows_before:,} | "
        f"After: {rows_after:,} | "
        f"Removed duplicates: {duplicates_removed:,} | "
        f"Total kept: {total_rows_after:,}"
    )

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())
print("Total rows before:", f"{total_rows_before:,}")
print("Total rows after:", f"{total_rows_after:,}")
print("Total duplicates removed:", f"{total_duplicates_removed:,}")
print("Removed percent:", round(total_duplicates_removed / total_rows_before * 100, 4), "%")
print("Unique hashes stored:", f"{len(seen_hashes):,}")

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:5: SyntaxWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1484\2698032949.py:5: SyntaxWarning: invalid escape sequence '\S'
  DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready.csv")

Chunk 1 | Before: 200,000 | After: 199,921 | Removed duplicates: 79 | Total kept: 199,921
Chunk 2 | Before: 200,000 | After: 199,873 | Removed duplicates: 127 | Total kept: 399,794
Chunk 3 | Before: 200,000 | After: 199,811 | Removed duplicates: 189 | Total kept: 599,605
Chunk 4 | Before: 200,000 | After: 199,792 | Removed duplicates: 208 | Total kept: 799,397
Chunk 5 | Before: 200,000 | After: 199,767 | Removed duplicates: 233 | Total kept: 999,164
Chunk 6 | Before: 200,000 | After: 199,784 | Removed duplicates: 216 | Total kept: 1,198,948
Chunk 7 | Before: 200,000 | After: 199,729 | Removed duplicates: 271 | Total kept: 1,398,677
Chunk 8 | Before: 200,000 | After: 199,736 | Removed duplicates: 264 | Total kept: 1,598,413
Chunk 9 | Before: 200,000 | After: 199,733 | Removed duplicates: 267 | Total kept: 1,798,146
Chunk 10 | Before: 200,000 | After: 199,684 | Removed duplicates: 316 | Total kept: 1,997,830
Chunk 11 | Before: 200,000 | After: 199,726 | Removed duplicates: 274 | Total kept: 2,197,556
Chunk 12 | Before: 200,000 | After: 199,687 | Removed duplicates: 313 | Total kept: 2,397,243
Chunk 13 | Before: 200,000 | After: 199,674 | Removed duplicates: 326 | Total kept: 2,596,917
Chunk 14 | Before: 200,000 | After: 199,697 | Removed duplicates: 303 | Total kept: 2,796,614
Chunk 15 | Before: 200,000 | After: 199,718 | Removed duplicates: 282 | Total kept: 2,996,332
Chunk 16 | Before: 200,000 | After: 199,707 | Removed duplicates: 293 | Total kept: 3,196,039
Chunk 17 | Before: 200,000 | After: 199,750 | Removed duplicates: 250 | Total kept: 3,395,789
Chunk 18 | Before: 200,000 | After: 199,715 | Removed duplicates: 285 | Total kept: 3,595,504
Chunk 19 | Before: 200,000 | After: 199,728 | Removed duplicates: 272 | Total kept: 3,795,232
Chunk 20 | Before: 200,000 | After: 199,755 | Removed duplicates: 245 | Total kept: 3,994,987
Chunk 21 | Before: 200,000 | After: 199,754 | Removed duplicates: 246 | Total kept: 4,194,741
Chunk 22 | Before: 200,000 | After: 199,732 | Removed duplicates: 268 | Total kept: 4,394,473
Chunk 23 | Before: 200,000 | After: 199,740 | Removed duplicates: 260 | Total kept: 4,594,213
Chunk 24 | Before: 200,000 | After: 199,736 | Removed duplicates: 264 | Total kept: 4,793,949
Chunk 25 | Before: 200,000 | After: 199,762 | Removed duplicates: 238 | Total kept: 4,993,711
Chunk 26 | Before: 200,000 | After: 199,736 | Removed duplicates: 264 | Total kept: 5,193,447
Chunk 27 | Before: 200,000 | After: 199,759 | Removed duplicates: 241 | Total kept: 5,393,206
Chunk 28 | Before: 200,000 | After: 199,772 | Removed duplicates: 228 | Total kept: 5,592,978
Chunk 29 | Before: 200,000 | After: 199,759 | Removed duplicates: 241 | Total kept: 5,792,737
Chunk 30 | Before: 200,000 | After: 199,722 | Removed duplicates: 278 | Total kept: 5,992,459
Chunk 31 | Before: 200,000 | After: 199,730 | Removed duplicates: 270 | Total kept: 6,192,189
Chunk 32 | Before: 200,000 | After: 199,772 | Removed duplicates: 228 | Total kept: 6,391,961
Chunk 33 | Before: 200,000 | After: 199,676 | Removed duplicates: 324 | Total kept: 6,591,637
Chunk 34 | Before: 200,000 | After: 199,711 | Removed duplicates: 289 | Total kept: 6,791,348
Chunk 35 | Before: 200,000 | After: 199,679 | Removed duplicates: 321 | Total kept: 6,991,027
Chunk 36 | Before: 200,000 | After: 199,662 | Removed duplicates: 338 | Total kept: 7,190,689
Chunk 37 | Before: 200,000 | After: 199,633 | Removed duplicates: 367 | Total kept: 7,390,322
Chunk 38 | Before: 200,000 | After: 199,498 | Removed duplicates: 502 | Total kept: 7,589,820
Chunk 39 | Before: 200,000 | After: 199,478 | Removed duplicates: 522 | Total kept: 7,789,298
Chunk 40 | Before: 200,000 | After: 199,419 | Removed duplicates: 581 | Total kept: 7,988,717
Chunk 41 | Before: 74,536 | After: 74,283 | Removed duplicates: 253 | Total kept: 8,063,000

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_no_duplicates.csv
Total rows before: 8,074,536
Total rows after: 8,063,000
Total duplicates removed: 11,536
Removed percent: 0.1429 %
Unique hashes stored: 8,063,000

## Step 5: Check Numeric Columns

This step studies the main numeric columns, such as loan amount, applicant income, population, and income-related tract values. The code converts these columns to numbers and creates a summary table with missing counts, minimum, maximum, mean, median, quartiles, and standard deviation. This helps us understand the scale and possible outliers before modeling.

In [1]:
import pandas as pd
from pathlib import Path

# Input file
DATA_PATH = Path("hmda_2017_classification_ready.csv")

CHUNK_SIZE = 200_000

# Continuous / semi-continuous numeric columns
continuous_numeric_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "minority_population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# --------------------------------------------------
# 1. Check which columns exist in the file
# --------------------------------------------------
header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

existing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col in header_df.columns
]

missing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col not in header_df.columns
]

print("Existing numeric columns:")
print(existing_numeric_cols)

if missing_numeric_cols:
    print("\nColumns not found:")
    print(missing_numeric_cols)

# --------------------------------------------------
# 2. Read the file chunk by chunk
#    Store only numeric columns, then make one final summary
# --------------------------------------------------
numeric_chunks = []

total_rows = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows += len(chunk)

    # Convert selected columns to numeric
    numeric_chunk = chunk[existing_numeric_cols].apply(
        pd.to_numeric,
        errors="coerce"
    )

    numeric_chunks.append(numeric_chunk)

    print(f"Processed chunk {chunk_id} | Total rows processed: {total_rows:,}")

# --------------------------------------------------
# 3. Combine numeric chunks and create one final summary
# --------------------------------------------------
df_numeric_all = pd.concat(numeric_chunks, ignore_index=True)

numeric_summary = df_numeric_all.describe(
    percentiles=[0.25, 0.5, 0.75]
).T

numeric_summary = numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
].rename(columns={
    "count": "non_missing_count",
    "mean": "mean",
    "std": "std",
    "min": "min",
    "25%": "q1_25%",
    "50%": "median_50%",
    "75%": "q3_75%",
    "max": "max"
})

# Add missing counts
numeric_summary["missing_count"] = df_numeric_all.isna().sum()
numeric_summary["missing_percent"] = (
    df_numeric_all.isna().mean() * 100
).round(2)

# Reorder columns
numeric_summary = numeric_summary[
    [
        "non_missing_count",
        "missing_count",
        "missing_percent",
        "min",
        "q1_25%",
        "median_50%",
        "mean",
        "q3_75%",
        "max",
        "std"
    ]
]

# Optional: round values for readability
numeric_summary = numeric_summary.round(3)

print("\nTotal rows processed:", f"{total_rows:,}")
display(numeric_summary)

Existing numeric columns:
['loan_amount_000s', 'applicant_income_000s', 'population', 'minority_population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units']
Processed chunk 1 | Total rows processed: 200,000
Processed chunk 2 | Total rows processed: 400,000
Processed chunk 3 | Total rows processed: 600,000
Processed chunk 4 | Total rows processed: 800,000
Processed chunk 5 | Total rows processed: 1,000,000
Processed chunk 6 | Total rows processed: 1,200,000
Processed chunk 7 | Total rows processed: 1,400,000
Processed chunk 8 | Total rows processed: 1,600,000
Processed chunk 9 | Total rows processed: 1,800,000
Processed chunk 10 | Total rows processed: 2,000,000
Processed chunk 11 | Total rows processed: 2,200,000
Processed chunk 12 | Total rows processed: 2,400,000
Processed chunk 13 | Total rows processed: 2,600,000
Processed chunk 14 | Total rows processed: 2,800,000
Processed chunk 15 | Total rows processed: 3,000,000
Processed chunk 16 | Total rows processed: 3,200,000
Processed chunk 17 | Total rows processed: 3,400,000
Processed chunk 18 | Total rows processed: 3,600,000
Processed chunk 19 | Total rows processed: 3,800,000
Processed chunk 20 | Total rows processed: 4,000,000
Processed chunk 21 | Total rows processed: 4,200,000
Processed chunk 22 | Total rows processed: 4,400,000
Processed chunk 23 | Total rows processed: 4,600,000
Processed chunk 24 | Total rows processed: 4,800,000
Processed chunk 25 | Total rows processed: 5,000,000
Processed chunk 26 | Total rows processed: 5,200,000
Processed chunk 27 | Total rows processed: 5,400,000
Processed chunk 28 | Total rows processed: 5,600,000
Processed chunk 29 | Total rows processed: 5,800,000
Processed chunk 30 | Total rows processed: 6,000,000
Processed chunk 31 | Total rows processed: 6,200,000
Processed chunk 32 | Total rows processed: 6,400,000
Processed chunk 33 | Total rows processed: 6,600,000
Processed chunk 34 | Total rows processed: 6,800,000
Processed chunk 35 | Total rows processed: 7,000,000
Processed chunk 36 | Total rows processed: 7,200,000
Processed chunk 37 | Total rows processed: 7,400,000
Processed chunk 38 | Total rows processed: 7,600,000
Processed chunk 39 | Total rows processed: 7,800,000
Processed chunk 40 | Total rows processed: 8,000,000
Processed chunk 41 | Total rows processed: 8,074,536

Total rows processed: 8,074,536

,non_missing_count,missing_count,missing_percent,min,q1_25%,median_50%,mean,q3_75%,max,std
loan_amount_000s,8074536.0,0,0.0,1.0,114.00,192.00,240.041,300.00,475000.00,638.034
applicant_income_000s,8074536.0,0,0.0,1.0,52.00,81.00,112.064,126.00,360000.00,408.534
population,8074536.0,0,0.0,0.0,3927.00,5248.00,5828.494,6882.00,53812.00,3250.390
minority_population,8074536.0,0,0.0,0.0,12.75,25.92,33.628,48.97,100.00,26.107
hud_median_family_income,8074536.0,0,0.0,18000.0,63200.00,69200.00,72570.757,79200.00,131500.00,14656.043
tract_to_msamd_income,8074536.0,0,0.0,0.0,86.47,108.98,114.595,135.90,507.47,42.549
number_of_owner_occupied_units,8074536.0,0,0.0,0.0,933.00,1342.00,1490.290,1843.00,19529.00,917.148
number_of_1_to_4_family_units,8074536.0,0,0.0,0.0,1322.00,1798.00,1991.370,2402.00,25391.00,1125.836

## Step 6: Remove Invalid Values

This step makes a stricter clean version of the classification dataset. It removes rows with real missing values, invalid zero values, non-numeric values in numeric columns, invalid numeric ranges, and wrong categorical codes. It also keeps special text values when they have a real meaning, such as `Not applicable`. After this step, 8,064,813 rows remain, and a problem summary file is saved.

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# 0. File paths
# =========================================================

DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready.csv")
OUTPUT_PATH = Path("hmda_2017_classification_ready_cleaned_invalid_removed.csv")

CHUNK_SIZE = 200_000

# =========================================================
# 1. Missing-like values
# =========================================================

real_missing_values = {
    "",
    "nan", "NaN", "NAN",
    "none", "None", "NONE",
    "null", "Null", "NULL",
    "na", "NA", "N/A", "n/a",
    ".", "-", "--"
}

real_missing_values_lower = {v.lower() for v in real_missing_values}

# These values are meaningful categories, not real missing values.
special_meaning_values = {
    "Information not provided by applicant in mail, Internet, or telephone application",
    "Information not provided",
    "Not applicable",
    "No co-applicant"
}

# =========================================================
# 2. Numeric columns
# =========================================================

numeric_value_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "minority_population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# Zero is invalid / missing-like in these columns.
zero_should_not_exist_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# Zero is valid in these columns.
zero_is_valid_cols = [
    "minority_population",
    "loan_approved"
]

# =========================================================
# 3. Valid categorical codes
# =========================================================

valid_codes = {
    "agency_code": {"1", "2", "3", "5", "7", "9"},
    "loan_type": {"1", "2", "3", "4"},
    "property_type": {"1", "2", "3"},
    "loan_purpose": {"1", "2", "3"},
    "owner_occupancy": {"1", "2", "3"},
    "preapproval": {"1", "2", "3"},

    # If action_taken still exists, only keep the actions used in your classification task.
    "action_taken": {"1", "2", "3", "7", "8"},

    "applicant_ethnicity": {"1", "2", "3", "4"},
    "co_applicant_ethnicity": {"1", "2", "3", "4", "5"},

    "applicant_race_1": {"1", "2", "3", "4", "5", "6", "7"},
    "co_applicant_race_1": {"1", "2", "3", "4", "5", "6", "7", "8"},

    "applicant_sex": {"1", "2", "3", "4"},
    "co_applicant_sex": {"1", "2", "3", "4", "5"},

    "hoepa_status": {"1", "2"},
    "lien_status": {"1", "2", "3", "4"},

    # Final binary target
    "loan_approved": {"0", "1"}
}

# =========================================================
# 4. Leftover columns that should not be used if they still exist
# =========================================================

columns_to_drop_if_still_exist = [
    "edit_status_name",
    "edit_status",
    "sequence_number",
    "application_date_indicator",

    "applicant_race_name_2",
    "applicant_race_2",
    "applicant_race_name_3",
    "applicant_race_3",
    "applicant_race_name_4",
    "applicant_race_4",
    "applicant_race_name_5",
    "applicant_race_5",

    "co_applicant_race_name_2",
    "co_applicant_race_2",
    "co_applicant_race_name_3",
    "co_applicant_race_3",
    "co_applicant_race_name_4",
    "co_applicant_race_4",
    "co_applicant_race_name_5",
    "co_applicant_race_5",

    "denial_reason_name_1",
    "denial_reason_1",
    "denial_reason_name_2",
    "denial_reason_2",
    "denial_reason_name_3",
    "denial_reason_3",

    "rate_spread",
    "purchaser_type_name",
    "purchaser_type",

    # If you already created loan_approved, these should not remain as model features.
    "action_taken_name"
]

# =========================================================
# 5. Helper functions
# =========================================================

def is_real_missing(s):
    """
    Detect real missing-like values after converting to string.
    """
    temp = s.astype(str).str.strip().str.lower()
    return temp.isin(real_missing_values_lower)


def is_zero_like(s):
    """
    Detect values like 0, 0.0, 0.00, 000, 000.0.
    """
    temp = s.astype(str).str.strip()

    zero_text_mask = temp.str.fullmatch(r"0+(\.0+)?", na=False)

    numeric_temp = pd.to_numeric(temp, errors="coerce")
    zero_numeric_mask = numeric_temp.eq(0)

    return zero_text_mask | zero_numeric_mask


def init_col_stats():
    """
    Initialize per-column problem counters.
    """
    return {
        "real_missing_count": 0,
        "zero_as_missing_count": 0,
        "non_numeric_count": 0,
        "invalid_numeric_range_count": 0,
        "invalid_code_count": 0
    }


# =========================================================
# 6. Read header and prepare dynamic column lists
# =========================================================

header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

original_columns = header_df.columns.tolist()

existing_drop_cols = [
    col for col in columns_to_drop_if_still_exist
    if col in original_columns
]

remaining_columns_after_drop = [
    col for col in original_columns
    if col not in existing_drop_cols
]

existing_numeric_cols = [
    col for col in numeric_value_cols
    if col in remaining_columns_after_drop
]

existing_zero_invalid_cols = [
    col for col in zero_should_not_exist_cols
    if col in remaining_columns_after_drop
]

existing_valid_code_cols = {
    col: codes
    for col, codes in valid_codes.items()
    if col in remaining_columns_after_drop
}

print("Original column count:", len(original_columns))
print("Columns to drop if still present:", len(existing_drop_cols))
print("Expected output column count:", len(remaining_columns_after_drop))

print("\nColumns dropped before row cleaning:")
for col in existing_drop_cols:
    print("-", col)

print("\nNumeric columns checked:")
print(existing_numeric_cols)

print("\nZero-invalid columns checked:")
print(existing_zero_invalid_cols)

print("\nCategorical code columns checked:")
print(list(existing_valid_code_cols.keys()))

# =========================================================
# 7. Process file chunk by chunk
# =========================================================

first_chunk = True

total_rows_before = 0
total_rows_after = 0
total_rows_removed = 0

reason_counts = {
    "real_missing_rows": 0,
    "zero_as_missing_rows": 0,
    "non_numeric_rows": 0,
    "invalid_numeric_range_rows": 0,
    "invalid_code_rows": 0,
    "total_removed_rows_unique": 0
}

per_column_stats = {}

def add_col_stat(col, key, count):
    if col not in per_column_stats:
        per_column_stats[col] = init_col_stats()
    per_column_stats[col][key] += int(count)


for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    rows_before = len(chunk)
    total_rows_before += rows_before

    # Drop leftover columns if they still exist.
    drop_cols_in_chunk = [
        col for col in existing_drop_cols
        if col in chunk.columns
    ]

    if drop_cols_in_chunk:
        chunk = chunk.drop(columns=drop_cols_in_chunk)

    # Normalize all remaining columns as stripped strings.
    for col in chunk.columns:
        chunk[col] = chunk[col].astype(str).str.strip()

    # -----------------------------------------------------
    # A. Real missing values in any remaining column
    # -----------------------------------------------------
    real_missing_row_mask = pd.Series(False, index=chunk.index)

    for col in chunk.columns:
        col_missing_mask = is_real_missing(chunk[col])
        add_col_stat(col, "real_missing_count", col_missing_mask.sum())
        real_missing_row_mask = real_missing_row_mask | col_missing_mask

    # -----------------------------------------------------
    # B. Zero-like values in columns where zero is invalid
    # -----------------------------------------------------
    zero_as_missing_row_mask = pd.Series(False, index=chunk.index)

    for col in existing_zero_invalid_cols:
        if col in chunk.columns:
            col_zero_mask = is_zero_like(chunk[col]) & (~is_real_missing(chunk[col]))
            add_col_stat(col, "zero_as_missing_count", col_zero_mask.sum())
            zero_as_missing_row_mask = zero_as_missing_row_mask | col_zero_mask

    # -----------------------------------------------------
    # C. Non-numeric values and invalid numeric ranges
    # -----------------------------------------------------
    non_numeric_row_mask = pd.Series(False, index=chunk.index)
    invalid_numeric_range_row_mask = pd.Series(False, index=chunk.index)

    for col in existing_numeric_cols:
        if col not in chunk.columns:
            continue

        col_missing_mask = is_real_missing(chunk[col])
        numeric_s = pd.to_numeric(chunk[col], errors="coerce")

        # Non-numeric but not already missing-like.
        col_non_numeric_mask = numeric_s.isna() & (~col_missing_mask)

        add_col_stat(col, "non_numeric_count", col_non_numeric_mask.sum())
        non_numeric_row_mask = non_numeric_row_mask | col_non_numeric_mask

        # Range rules for numeric columns.
        if col == "minority_population":
            # Minority percentage must be between 0 and 100.
            col_invalid_range_mask = (
                numeric_s.notna()
                & ((numeric_s < 0) | (numeric_s > 100))
            )
        elif col in zero_should_not_exist_cols:
            # These columns must be strictly positive.
            col_invalid_range_mask = (
                numeric_s.notna()
                & (numeric_s <= 0)
            )
        else:
            # General numeric columns should not be negative.
            col_invalid_range_mask = (
                numeric_s.notna()
                & (numeric_s < 0)
            )

        add_col_stat(col, "invalid_numeric_range_count", col_invalid_range_mask.sum())
        invalid_numeric_range_row_mask = invalid_numeric_range_row_mask | col_invalid_range_mask

    # -----------------------------------------------------
    # D. Invalid categorical codes
    # -----------------------------------------------------
    invalid_code_row_mask = pd.Series(False, index=chunk.index)

    for col, allowed_codes in existing_valid_code_cols.items():
        if col not in chunk.columns:
            continue

        col_missing_mask = is_real_missing(chunk[col])

        col_invalid_code_mask = (
            (~col_missing_mask)
            & (~chunk[col].isin(allowed_codes))
        )

        add_col_stat(col, "invalid_code_count", col_invalid_code_mask.sum())
        invalid_code_row_mask = invalid_code_row_mask | col_invalid_code_mask

    # -----------------------------------------------------
    # E. Combine all row-removal rules
    # -----------------------------------------------------
    rows_to_remove_mask = (
        real_missing_row_mask
        | zero_as_missing_row_mask
        | non_numeric_row_mask
        | invalid_numeric_range_row_mask
        | invalid_code_row_mask
    )

    chunk_clean = chunk.loc[~rows_to_remove_mask].copy()

    rows_after = len(chunk_clean)
    rows_removed = rows_before - rows_after

    total_rows_after += rows_after
    total_rows_removed += rows_removed

    reason_counts["real_missing_rows"] += int(real_missing_row_mask.sum())
    reason_counts["zero_as_missing_rows"] += int(zero_as_missing_row_mask.sum())
    reason_counts["non_numeric_rows"] += int(non_numeric_row_mask.sum())
    reason_counts["invalid_numeric_range_rows"] += int(invalid_numeric_range_row_mask.sum())
    reason_counts["invalid_code_rows"] += int(invalid_code_row_mask.sum())
    reason_counts["total_removed_rows_unique"] += int(rows_to_remove_mask.sum())

    # Write cleaned chunk.
    chunk_clean.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    print(
        f"Chunk {chunk_id} | "
        f"Before: {rows_before:,} | "
        f"After: {rows_after:,} | "
        f"Removed: {rows_removed:,} | "
        f"Total kept: {total_rows_after:,}"
    )

# =========================================================
# 8. Final summary
# =========================================================

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())

print("\nFinal row summary:")
print("Total rows before:", f"{total_rows_before:,}")
print("Total rows after:", f"{total_rows_after:,}")
print("Total rows removed:", f"{total_rows_removed:,}")

if total_rows_before > 0:
    print("Removed percent:", round(total_rows_removed / total_rows_before * 100, 4), "%")

print("\nRemoval reason counts:")
for key, value in reason_counts.items():
    print(f"{key}: {value:,}")

# Per-column problem summary
problem_summary = pd.DataFrame.from_dict(
    per_column_stats,
    orient="index"
).reset_index().rename(columns={"index": "column"})

problem_summary["total_problem_count"] = (
    problem_summary["real_missing_count"]
    + problem_summary["zero_as_missing_count"]
    + problem_summary["non_numeric_count"]
    + problem_summary["invalid_numeric_range_count"]
    + problem_summary["invalid_code_count"]
)

problem_summary = problem_summary.sort_values(
    "total_problem_count",
    ascending=False
).reset_index(drop=True)

print("\nTop columns with detected problems:")
display(problem_summary.head(30))

# Save the cleaning report.
REPORT_PATH = Path("hmda_2017_cleaning_problem_summary.csv")
problem_summary.to_csv(REPORT_PATH, index=False)

print("\nProblem summary saved to:", REPORT_PATH.resolve())

<>:9: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\S'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8156\2556719353.py:9: SyntaxWarning: invalid escape sequence '\S'
  DATA_PATH = Path("D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready.csv")

Original column count: 52
Columns to drop if still present: 3
Expected output column count: 49

Columns dropped before row cleaning:
- purchaser_type_name
- purchaser_type
- action_taken_name

Numeric columns checked:
['loan_amount_000s', 'applicant_income_000s', 'population', 'minority_population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units']

Zero-invalid columns checked:
['loan_amount_000s', 'applicant_income_000s', 'population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units']

Categorical code columns checked:
['agency_code', 'loan_type', 'property_type', 'loan_purpose', 'owner_occupancy', 'preapproval', 'action_taken', 'applicant_ethnicity', 'co_applicant_ethnicity', 'applicant_race_1', 'co_applicant_race_1', 'applicant_sex', 'co_applicant_sex', 'hoepa_status', 'lien_status', 'loan_approved']
Chunk 1 | Before: 200,000 | After: 199,771 | Removed: 229 | Total kept: 199,771
Chunk 2 | Before: 200,000 | After: 199,786 | Removed: 214 | Total kept: 399,557
Chunk 3 | Before: 200,000 | After: 199,801 | Removed: 199 | Total kept: 599,358
Chunk 4 | Before: 200,000 | After: 199,754 | Removed: 246 | Total kept: 799,112
Chunk 5 | Before: 200,000 | After: 199,692 | Removed: 308 | Total kept: 998,804
Chunk 6 | Before: 200,000 | After: 199,788 | Removed: 212 | Total kept: 1,198,592
Chunk 7 | Before: 200,000 | After: 199,700 | Removed: 300 | Total kept: 1,398,292
Chunk 8 | Before: 200,000 | After: 199,737 | Removed: 263 | Total kept: 1,598,029
Chunk 9 | Before: 200,000 | After: 199,767 | Removed: 233 | Total kept: 1,797,796
Chunk 10 | Before: 200,000 | After: 199,712 | Removed: 288 | Total kept: 1,997,508
Chunk 11 | Before: 200,000 | After: 199,773 | Removed: 227 | Total kept: 2,197,281
Chunk 12 | Before: 200,000 | After: 199,693 | Removed: 307 | Total kept: 2,396,974
Chunk 13 | Before: 200,000 | After: 199,707 | Removed: 293 | Total kept: 2,596,681
Chunk 14 | Before: 200,000 | After: 199,770 | Removed: 230 | Total kept: 2,796,451
Chunk 15 | Before: 200,000 | After: 199,698 | Removed: 302 | Total kept: 2,996,149
Chunk 16 | Before: 200,000 | After: 199,721 | Removed: 279 | Total kept: 3,195,870
Chunk 17 | Before: 200,000 | After: 199,568 | Removed: 432 | Total kept: 3,395,438
Chunk 18 | Before: 200,000 | After: 199,614 | Removed: 386 | Total kept: 3,595,052
Chunk 19 | Before: 200,000 | After: 199,764 | Removed: 236 | Total kept: 3,794,816
Chunk 20 | Before: 200,000 | After: 199,718 | Removed: 282 | Total kept: 3,994,534
Chunk 21 | Before: 200,000 | After: 199,763 | Removed: 237 | Total kept: 4,194,297
Chunk 22 | Before: 200,000 | After: 199,657 | Removed: 343 | Total kept: 4,393,954
Chunk 23 | Before: 200,000 | After: 199,733 | Removed: 267 | Total kept: 4,593,687
Chunk 24 | Before: 200,000 | After: 199,887 | Removed: 113 | Total kept: 4,793,574
Chunk 25 | Before: 200,000 | After: 199,907 | Removed: 93 | Total kept: 4,993,481
Chunk 26 | Before: 200,000 | After: 199,879 | Removed: 121 | Total kept: 5,193,360
Chunk 27 | Before: 200,000 | After: 199,920 | Removed: 80 | Total kept: 5,393,280
Chunk 28 | Before: 200,000 | After: 199,896 | Removed: 104 | Total kept: 5,593,176
Chunk 29 | Before: 200,000 | After: 199,846 | Removed: 154 | Total kept: 5,793,022
Chunk 30 | Before: 200,000 | After: 199,759 | Removed: 241 | Total kept: 5,992,781
Chunk 31 | Before: 200,000 | After: 199,808 | Removed: 192 | Total kept: 6,192,589
Chunk 32 | Before: 200,000 | After: 199,766 | Removed: 234 | Total kept: 6,392,355
Chunk 33 | Before: 200,000 | After: 199,752 | Removed: 248 | Total kept: 6,592,107
Chunk 34 | Before: 200,000 | After: 199,635 | Removed: 365 | Total kept: 6,791,742
Chunk 35 | Before: 200,000 | After: 199,745 | Removed: 255 | Total kept: 6,991,487
Chunk 36 | Before: 200,000 | After: 199,645 | Removed: 355 | Total kept: 7,191,132
Chunk 37 | Before: 200,000 | After: 199,795 | Removed: 205 | Total kept: 7,390,927
Chunk 38 | Before: 200,000 | After: 199,756 | Removed: 244 | Total kept: 7,590,683
Chunk 39 | Before: 200,000 | After: 199,799 | Removed: 201 | Total kept: 7,790,482
Chunk 40 | Before: 200,000 | After: 199,842 | Removed: 158 | Total kept: 7,990,324
Chunk 41 | Before: 74,536 | After: 74,489 | Removed: 47 | Total kept: 8,064,813

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_classification_ready_cleaned_invalid_removed.csv

Final row summary:
Total rows before: 8,074,536
Total rows after: 8,064,813
Total rows removed: 9,723
Removed percent: 0.1204 %

Removal reason counts:
real_missing_rows: 0
zero_as_missing_rows: 9,723
non_numeric_rows: 0
invalid_numeric_range_rows: 9,723
invalid_code_rows: 0
total_removed_rows_unique: 9,723

Top columns with detected problems:

,column,real_missing_count,zero_as_missing_count,non_numeric_count,invalid_numeric_range_count,invalid_code_count,total_problem_count
0,tract_to_msamd_income,0,8636,0,8636,0,17272
1,number_of_owner_occupied_units,0,938,0,938,0,1876
2,number_of_1_to_4_family_units,0,690,0,690,0,1380
3,population,0,159,0,159,0,318
4,agency_code,0,0,0,0,0,0
5,respondent_id,0,0,0,0,0,0
6,agency_name,0,0,0,0,0,0
7,agency_abbr,0,0,0,0,0,0
8,property_type,0,0,0,0,0,0
9,loan_purpose_name,0,0,0,0,0,0
10,loan_purpose,0,0,0,0,0,0
11,owner_occupancy_name,0,0,0,0,0,0
12,owner_occupancy,0,0,0,0,0,0
13,loan_type_name,0,0,0,0,0,0
14,loan_type,0,0,0,0,0,0
15,property_type_name,0,0,0,0,0,0
16,as_of_year,0,0,0,0,0,0
17,action_taken,0,0,0,0,0,0
18,preapproval,0,0,0,0,0,0
19,preapproval_name,0,0,0,0,0,0
20,loan_amount_000s,0,0,0,0,0,0
21,msamd_name,0,0,0,0,0,0
22,msamd,0,0,0,0,0,0
23,state_name,0,0,0,0,0,0
24,state_abbr,0,0,0,0,0,0
25,applicant_ethnicity_name,0,0,0,0,0,0
26,applicant_ethnicity,0,0,0,0,0,0
27,co_applicant_ethnicity_name,0,0,0,0,0,0
28,co_applicant_ethnicity,0,0,0,0,0,0
29,state_code,0,0,0,0,0,0

Problem summary saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_cleaning_problem_summary.csv

## Step 7: Check Numeric Columns After Invalid Value Cleaning

This step repeats the numeric summary after invalid rows are removed. It checks that the main numeric columns have no missing values and shows their minimum, maximum, mean, median, quartiles, and standard deviation. This confirms that the stricter cleaning step worked correctly.

In [4]:
import pandas as pd
from pathlib import Path

# Input file
DATA_PATH = Path("hmda_2017_classification_ready_cleaned_invalid_removed.csv")

CHUNK_SIZE = 200_000

# Continuous / semi-continuous numeric columns
continuous_numeric_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "minority_population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# --------------------------------------------------
# 1. Check which columns exist in the file
# --------------------------------------------------
header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

existing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col in header_df.columns
]

missing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col not in header_df.columns
]

print("Existing numeric columns:")
print(existing_numeric_cols)

if missing_numeric_cols:
    print("\nColumns not found:")
    print(missing_numeric_cols)

# --------------------------------------------------
# 2. Read the file chunk by chunk
#    Store only numeric columns, then make one final summary
# --------------------------------------------------
numeric_chunks = []

total_rows = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows += len(chunk)

    # Convert selected columns to numeric
    numeric_chunk = chunk[existing_numeric_cols].apply(
        pd.to_numeric,
        errors="coerce"
    )

    numeric_chunks.append(numeric_chunk)

    print(f"Processed chunk {chunk_id} | Total rows processed: {total_rows:,}")

# --------------------------------------------------
# 3. Combine numeric chunks and create one final summary
# --------------------------------------------------
df_numeric_all = pd.concat(numeric_chunks, ignore_index=True)

numeric_summary = df_numeric_all.describe(
    percentiles=[0.25, 0.5, 0.75]
).T

numeric_summary = numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
].rename(columns={
    "count": "non_missing_count",
    "mean": "mean",
    "std": "std",
    "min": "min",
    "25%": "q1_25%",
    "50%": "median_50%",
    "75%": "q3_75%",
    "max": "max"
})

# Add missing counts
numeric_summary["missing_count"] = df_numeric_all.isna().sum()
numeric_summary["missing_percent"] = (
    df_numeric_all.isna().mean() * 100
).round(2)

# Reorder columns
numeric_summary = numeric_summary[
    [
        "non_missing_count",
        "missing_count",
        "missing_percent",
        "min",
        "q1_25%",
        "median_50%",
        "mean",
        "q3_75%",
        "max",
        "std"
    ]
]

# Optional: round values for readability
numeric_summary = numeric_summary.round(3)

print("\nTotal rows processed:", f"{total_rows:,}")
display(numeric_summary)

Existing numeric columns:
['loan_amount_000s', 'applicant_income_000s', 'population', 'minority_population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units']
Processed chunk 1 | Total rows processed: 200,000
Processed chunk 2 | Total rows processed: 400,000
Processed chunk 3 | Total rows processed: 600,000
Processed chunk 4 | Total rows processed: 800,000
Processed chunk 5 | Total rows processed: 1,000,000
Processed chunk 6 | Total rows processed: 1,200,000
Processed chunk 7 | Total rows processed: 1,400,000
Processed chunk 8 | Total rows processed: 1,600,000
Processed chunk 9 | Total rows processed: 1,800,000
Processed chunk 10 | Total rows processed: 2,000,000
Processed chunk 11 | Total rows processed: 2,200,000
Processed chunk 12 | Total rows processed: 2,400,000
Processed chunk 13 | Total rows processed: 2,600,000
Processed chunk 14 | Total rows processed: 2,800,000
Processed chunk 15 | Total rows processed: 3,000,000
Processed chunk 16 | Total rows processed: 3,200,000
Processed chunk 17 | Total rows processed: 3,400,000
Processed chunk 18 | Total rows processed: 3,600,000
Processed chunk 19 | Total rows processed: 3,800,000
Processed chunk 20 | Total rows processed: 4,000,000
Processed chunk 21 | Total rows processed: 4,200,000
Processed chunk 22 | Total rows processed: 4,400,000
Processed chunk 23 | Total rows processed: 4,600,000
Processed chunk 24 | Total rows processed: 4,800,000
Processed chunk 25 | Total rows processed: 5,000,000
Processed chunk 26 | Total rows processed: 5,200,000
Processed chunk 27 | Total rows processed: 5,400,000
Processed chunk 28 | Total rows processed: 5,600,000
Processed chunk 29 | Total rows processed: 5,800,000
Processed chunk 30 | Total rows processed: 6,000,000
Processed chunk 31 | Total rows processed: 6,200,000
Processed chunk 32 | Total rows processed: 6,400,000
Processed chunk 33 | Total rows processed: 6,600,000
Processed chunk 34 | Total rows processed: 6,800,000
Processed chunk 35 | Total rows processed: 7,000,000
Processed chunk 36 | Total rows processed: 7,200,000
Processed chunk 37 | Total rows processed: 7,400,000
Processed chunk 38 | Total rows processed: 7,600,000
Processed chunk 39 | Total rows processed: 7,800,000
Processed chunk 40 | Total rows processed: 8,000,000
Processed chunk 41 | Total rows processed: 8,064,813

Total rows processed: 8,064,813

,non_missing_count,missing_count,missing_percent,min,q1_25%,median_50%,mean,q3_75%,max,std
loan_amount_000s,8064813.0,0,0.0,1.00,114.00,192.00,239.902,300.00,475000.00,638.130
applicant_income_000s,8064813.0,0,0.0,1.00,52.00,81.00,111.979,126.00,360000.00,408.575
population,8064813.0,0,0.0,30.00,3930.00,5250.00,5832.161,6884.00,53812.00,3249.660
minority_population,8064813.0,0,0.0,0.00,12.74,25.89,33.604,48.92,100.00,26.100
hud_median_family_income,8064813.0,0,0.0,18000.00,63200.00,69200.00,72567.704,79200.00,131500.00,14653.094
tract_to_msamd_income,8064813.0,0,0.0,3.71,86.52,109.03,114.717,135.94,507.47,42.396
number_of_owner_occupied_units,8064813.0,0,0.0,2.00,934.00,1343.00,1491.736,1844.00,19529.00,916.679
number_of_1_to_4_family_units,8064813.0,0,0.0,5.00,1324.00,1799.00,1993.253,2403.00,25391.00,1125.081

## Step 8: Find Extreme Income and Loan Values

This step looks for the 100 smallest and 100 largest values in `loan_amount_000s` and `applicant_income_000s`. These two columns are important because very small or very large values can affect the model. The data is processed in chunks, so only the running top and bottom values are stored.

In [6]:
import pandas as pd
from pathlib import Path

# Input file
DATA_PATH = Path("hmda_2017_classification_ready_cleaned_invalid_removed.csv")

CHUNK_SIZE = 200_000

target_cols = [
    "loan_amount_000s",
    "applicant_income_000s"
]

TOP_N = 100

# Store running smallest and largest values
smallest_values = {col: pd.Series(dtype="float64") for col in target_cols}
largest_values = {col: pd.Series(dtype="float64") for col in target_cols}

total_rows_processed = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows_processed += len(chunk)

    for col in target_cols:
        if col not in chunk.columns:
            print(f"Column not found: {col}")
            continue

        # Convert to numeric
        numeric_s = pd.to_numeric(
            chunk[col].astype(str).str.strip(),
            errors="coerce"
        ).dropna()

        # Update smallest values
        smallest_values[col] = (
            pd.concat([smallest_values[col], numeric_s])
            .nsmallest(TOP_N)
            .reset_index(drop=True)
        )

        # Update largest values
        largest_values[col] = (
            pd.concat([largest_values[col], numeric_s])
            .nlargest(TOP_N)
            .reset_index(drop=True)
        )

    print(f"Processed chunk {chunk_id} | Total rows processed: {total_rows_processed:,}")

print("\nDone.")
print("Total rows processed:", f"{total_rows_processed:,}")

Processed chunk 1 | Total rows processed: 200,000
Processed chunk 2 | Total rows processed: 400,000
Processed chunk 3 | Total rows processed: 600,000
Processed chunk 4 | Total rows processed: 800,000
Processed chunk 5 | Total rows processed: 1,000,000
Processed chunk 6 | Total rows processed: 1,200,000
Processed chunk 7 | Total rows processed: 1,400,000
Processed chunk 8 | Total rows processed: 1,600,000
Processed chunk 9 | Total rows processed: 1,800,000
Processed chunk 10 | Total rows processed: 2,000,000
Processed chunk 11 | Total rows processed: 2,200,000
Processed chunk 12 | Total rows processed: 2,400,000
Processed chunk 13 | Total rows processed: 2,600,000
Processed chunk 14 | Total rows processed: 2,800,000
Processed chunk 15 | Total rows processed: 3,000,000
Processed chunk 16 | Total rows processed: 3,200,000
Processed chunk 17 | Total rows processed: 3,400,000
Processed chunk 18 | Total rows processed: 3,600,000
Processed chunk 19 | Total rows processed: 3,800,000
Processed chunk 20 | Total rows processed: 4,000,000
Processed chunk 21 | Total rows processed: 4,200,000
Processed chunk 22 | Total rows processed: 4,400,000
Processed chunk 23 | Total rows processed: 4,600,000
Processed chunk 24 | Total rows processed: 4,800,000
Processed chunk 25 | Total rows processed: 5,000,000
Processed chunk 26 | Total rows processed: 5,200,000
Processed chunk 27 | Total rows processed: 5,400,000
Processed chunk 28 | Total rows processed: 5,600,000
Processed chunk 29 | Total rows processed: 5,800,000
Processed chunk 30 | Total rows processed: 6,000,000
Processed chunk 31 | Total rows processed: 6,200,000
Processed chunk 32 | Total rows processed: 6,400,000
Processed chunk 33 | Total rows processed: 6,600,000
Processed chunk 34 | Total rows processed: 6,800,000
Processed chunk 35 | Total rows processed: 7,000,000
Processed chunk 36 | Total rows processed: 7,200,000
Processed chunk 37 | Total rows processed: 7,400,000
Processed chunk 38 | Total rows processed: 7,600,000
Processed chunk 39 | Total rows processed: 7,800,000
Processed chunk 40 | Total rows processed: 8,000,000
Processed chunk 41 | Total rows processed: 8,064,813

Done.
Total rows processed: 8,064,813

## Step 9: Display Extreme Values

This step displays the smallest and largest values found in the previous step. The result helps us see possible outliers, such as very small values equal to `1` and very large income or loan amounts. These values need attention before final modeling.

In [7]:
for col in target_cols:
    print("=" * 80)
    print(f"Column: {col}")
    
    print("\n100 smallest values:")
    display(
        pd.DataFrame({
            col: smallest_values[col].sort_values(ascending=True).values
        })
    )

    print("\n100 largest values:")
    display(
        pd.DataFrame({
            col: largest_values[col].sort_values(ascending=False).values
        })
    )

================================================================================
Column: loan_amount_000s

100 smallest values:

    loan_amount_000s
0                1.0
1                1.0
2                1.0
3                1.0
4                1.0
..               ...
95               1.0
96               1.0
97               1.0
98               1.0
99               1.0

[100 rows x 1 columns]

100 largest values:

    loan_amount_000s
0           475000.0
1           475000.0
2           475000.0
3           380000.0
4           365000.0
..               ...
95           15750.0
96           15750.0
97           15275.0
98           15000.0
99           15000.0

[100 rows x 1 columns]

================================================================================
Column: applicant_income_000s

100 smallest values:

    applicant_income_000s
0                     1.0
1                     1.0
2                     1.0
3                     1.0
4                     1.0
..                    ...
95                    1.0
96                    1.0
97                    1.0
98                    1.0
99                    1.0

[100 rows x 1 columns]

100 largest values:

    applicant_income_000s
0                360000.0
1                360000.0
2                360000.0
3                291000.0
4                268000.0
..                    ...
95                21058.0
96                20400.0
97                20000.0
98                19796.0
99                19200.0

[100 rows x 1 columns]

## Step 10: Analyze Suspicious Extreme Values

This step studies important suspicious groups in more detail. It checks rows where income or loan amount equals `1`, which means 1,000 dollars, and also checks the top 100 highest income and loan rows. For each group, it compares the approval rate with the full dataset and summarizes loan amounts for approved loans.

In [9]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# 0. File path and settings
# =========================================================

DATA_PATH = Path("hmda_2017_classification_ready_cleaned_invalid_removed.csv")

CHUNK_SIZE = 200_000
TOP_N = 100

income_col = "applicant_income_000s"
loan_col = "loan_amount_000s"
class_target_col = "loan_approved"

# Because these columns are in thousands of dollars:
# value == 1 means 1,000 dollars
ONE_THOUSAND_DOLLARS_VALUE = 1


# =========================================================
# 1. Helper functions
# =========================================================

def safe_to_numeric(s):
    """Convert a pandas Series to numeric after stripping strings."""
    return pd.to_numeric(
        s.astype(str).str.strip(),
        errors="coerce"
    )


def classification_distribution(df, target_col=class_target_col):
    """Return count and percent distribution of classification target."""
    if target_col not in df.columns or len(df) == 0:
        return pd.DataFrame(columns=[target_col, "count", "percent"])

    counts = (
        df[target_col]
        .astype(str)
        .str.strip()
        .value_counts(dropna=False)
        .sort_index()
    )

    result = counts.reset_index()
    result.columns = [target_col, "count"]
    result["percent"] = (result["count"] / result["count"].sum() * 100).round(2)

    return result


def regression_distribution_for_approved(df):
    """
    Return regression target summary for approved rows only.
    Regression target is loan_amount_000s.
    """
    if len(df) == 0 or class_target_col not in df.columns or loan_col not in df.columns:
        return pd.DataFrame([{
            "approved_rows_for_regression": 0,
            "min": np.nan,
            "q1_25%": np.nan,
            "median_50%": np.nan,
            "mean": np.nan,
            "q3_75%": np.nan,
            "max": np.nan,
            "std": np.nan
        }])

    approved_df = df[
        df[class_target_col].astype(str).str.strip() == "1"
    ].copy()

    y = safe_to_numeric(approved_df[loan_col]).dropna()

    if len(y) == 0:
        return pd.DataFrame([{
            "approved_rows_for_regression": 0,
            "min": np.nan,
            "q1_25%": np.nan,
            "median_50%": np.nan,
            "mean": np.nan,
            "q3_75%": np.nan,
            "max": np.nan,
            "std": np.nan
        }])

    return pd.DataFrame([{
        "approved_rows_for_regression": len(y),
        "min": y.min(),
        "q1_25%": y.quantile(0.25),
        "median_50%": y.quantile(0.50),
        "mean": y.mean(),
        "q3_75%": y.quantile(0.75),
        "max": y.max(),
        "std": y.std()
    }]).round(3)


def compare_group_to_overall_distribution(group_df, overall_distribution):
    """
    Create one table comparing the group's loan_approved distribution
    with the overall dataset distribution.
    """
    group_distribution = classification_distribution(group_df)

    comparison = pd.DataFrame({
        class_target_col: ["0", "1"]
    })

    comparison = comparison.merge(
        overall_distribution.rename(columns={
            "count": "overall_count",
            "percent": "overall_percent"
        }),
        on=class_target_col,
        how="left"
    )

    comparison = comparison.merge(
        group_distribution.rename(columns={
            "count": "group_count",
            "percent": "group_percent"
        }),
        on=class_target_col,
        how="left"
    )

    comparison = comparison.fillna(0)

    comparison["group_minus_overall_percent"] = (
        comparison["group_percent"] - comparison["overall_percent"]
    ).round(2)

    return comparison


def make_full_report(group_name, df_group, overall_distribution):
    """Create classification comparison and regression report for one group."""
    print("=" * 100)
    print(group_name)
    print("Rows in group:", f"{len(df_group):,}")

    print("\nClassification target distribution: group vs overall dataset")
    display(compare_group_to_overall_distribution(df_group, overall_distribution))

    print("\nRegression target distribution among approved rows only:")
    display(regression_distribution_for_approved(df_group))


# =========================================================
# 2. Storage for filtered groups and top-100 groups
# =========================================================

income_1000_parts = []
loan_1000_parts = []

top_income_df = pd.DataFrame()
top_loan_df = pd.DataFrame()

overall_target_counts = {}

total_rows_processed = 0


# =========================================================
# 3. Read data chunk by chunk
# =========================================================

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows_processed += len(chunk)

    required_cols = [income_col, loan_col, class_target_col]
    missing_cols = [col for col in required_cols if col not in chunk.columns]

    if missing_cols:
        raise ValueError(f"Missing columns in dataset: {missing_cols}")

    # -----------------------------------------------------
    # Overall loan_approved distribution over the full dataset
    # -----------------------------------------------------
    target_counts = (
        chunk[class_target_col]
        .astype(str)
        .str.strip()
        .value_counts(dropna=False)
    )

    for key, value in target_counts.items():
        overall_target_counts[key] = overall_target_counts.get(key, 0) + int(value)

    # -----------------------------------------------------
    # Numeric conversion for income and loan amount
    # -----------------------------------------------------
    chunk["_income_numeric"] = safe_to_numeric(chunk[income_col])
    chunk["_loan_numeric"] = safe_to_numeric(chunk[loan_col])

    # -----------------------------------------------------
    # A. Rows with applicant_income_000s == 1
    # -----------------------------------------------------
    income_1000_chunk = chunk[
        chunk["_income_numeric"] == ONE_THOUSAND_DOLLARS_VALUE
    ].copy()

    if len(income_1000_chunk) > 0:
        income_1000_parts.append(
            income_1000_chunk.drop(columns=["_income_numeric", "_loan_numeric"])
        )

    # -----------------------------------------------------
    # B. Rows with loan_amount_000s == 1
    # -----------------------------------------------------
    loan_1000_chunk = chunk[
        chunk["_loan_numeric"] == ONE_THOUSAND_DOLLARS_VALUE
    ].copy()

    if len(loan_1000_chunk) > 0:
        loan_1000_parts.append(
            loan_1000_chunk.drop(columns=["_income_numeric", "_loan_numeric"])
        )

    # -----------------------------------------------------
    # C. Top 100 applicant income rows
    # -----------------------------------------------------
    candidate_top_income = pd.concat(
        [top_income_df, chunk],
        ignore_index=True
    )

    candidate_top_income["_income_numeric"] = safe_to_numeric(
        candidate_top_income[income_col]
    )

    top_income_df = (
        candidate_top_income
        .dropna(subset=["_income_numeric"])
        .nlargest(TOP_N, "_income_numeric")
        .reset_index(drop=True)
    )

    # -----------------------------------------------------
    # D. Top 100 loan amount rows
    # -----------------------------------------------------
    candidate_top_loan = pd.concat(
        [top_loan_df, chunk],
        ignore_index=True
    )

    candidate_top_loan["_loan_numeric"] = safe_to_numeric(
        candidate_top_loan[loan_col]
    )

    top_loan_df = (
        candidate_top_loan
        .dropna(subset=["_loan_numeric"])
        .nlargest(TOP_N, "_loan_numeric")
        .reset_index(drop=True)
    )

    print(
        f"Processed chunk {chunk_id} | "
        f"Total rows processed: {total_rows_processed:,} | "
        f"Income=$1,000 rows found so far: {sum(len(x) for x in income_1000_parts):,} | "
        f"Loan=$1,000 rows found so far: {sum(len(x) for x in loan_1000_parts):,}"
    )


# =========================================================
# 4. Build overall distribution table
# =========================================================

overall_distribution = (
    pd.Series(overall_target_counts)
    .sort_index()
    .reset_index()
)

overall_distribution.columns = [class_target_col, "count"]
overall_distribution["percent"] = (
    overall_distribution["count"] / overall_distribution["count"].sum() * 100
).round(2)

# Make sure both classes exist in the table
overall_distribution = (
    pd.DataFrame({class_target_col: ["0", "1"]})
    .merge(overall_distribution, on=class_target_col, how="left")
    .fillna(0)
)

print("\nOverall loan_approved distribution in full dataset:")
display(overall_distribution)


# =========================================================
# 5. Combine final groups
# =========================================================

if income_1000_parts:
    income_1000_df = pd.concat(income_1000_parts, ignore_index=True)
else:
    income_1000_df = pd.DataFrame(columns=[income_col, loan_col, class_target_col])

if loan_1000_parts:
    loan_1000_df = pd.concat(loan_1000_parts, ignore_index=True)
else:
    loan_1000_df = pd.DataFrame(columns=[income_col, loan_col, class_target_col])

helper_cols = ["_income_numeric", "_loan_numeric"]

top_income_df_clean = top_income_df.drop(
    columns=[col for col in helper_cols if col in top_income_df.columns],
    errors="ignore"
)

top_loan_df_clean = top_loan_df.drop(
    columns=[col for col in helper_cols if col in top_loan_df.columns],
    errors="ignore"
)


# =========================================================
# 6. Final reports
# =========================================================

print("\nFinal analysis done.")
print("Total rows processed:", f"{total_rows_processed:,}")

make_full_report(
    "Group 1: Rows where applicant_income_000s = 1, meaning applicant income is $1,000",
    income_1000_df,
    overall_distribution
)

make_full_report(
    "Group 2: Rows where loan_amount_000s = 1, meaning loan amount is $1,000",
    loan_1000_df,
    overall_distribution
)

make_full_report(
    "Group 3: Top 100 rows with the highest applicant_income_000s",
    top_income_df_clean,
    overall_distribution
)

make_full_report(
    "Group 4: Top 100 rows with the highest loan_amount_000s",
    top_loan_df_clean,
    overall_distribution
)

Processed chunk 1 | Total rows processed: 200,000 | Income=$1,000 rows found so far: 130 | Loan=$1,000 rows found so far: 408
Processed chunk 2 | Total rows processed: 400,000 | Income=$1,000 rows found so far: 245 | Loan=$1,000 rows found so far: 846
Processed chunk 3 | Total rows processed: 600,000 | Income=$1,000 rows found so far: 326 | Loan=$1,000 rows found so far: 1,324
Processed chunk 4 | Total rows processed: 800,000 | Income=$1,000 rows found so far: 411 | Loan=$1,000 rows found so far: 1,732
Processed chunk 5 | Total rows processed: 1,000,000 | Income=$1,000 rows found so far: 478 | Loan=$1,000 rows found so far: 2,131
Processed chunk 6 | Total rows processed: 1,200,000 | Income=$1,000 rows found so far: 553 | Loan=$1,000 rows found so far: 2,574
Processed chunk 7 | Total rows processed: 1,400,000 | Income=$1,000 rows found so far: 610 | Loan=$1,000 rows found so far: 2,980
Processed chunk 8 | Total rows processed: 1,600,000 | Income=$1,000 rows found so far: 708 | Loan=$1,000 rows found so far: 3,374
Processed chunk 9 | Total rows processed: 1,800,000 | Income=$1,000 rows found so far: 793 | Loan=$1,000 rows found so far: 3,731
Processed chunk 10 | Total rows processed: 2,000,000 | Income=$1,000 rows found so far: 874 | Loan=$1,000 rows found so far: 4,105
Processed chunk 11 | Total rows processed: 2,200,000 | Income=$1,000 rows found so far: 948 | Loan=$1,000 rows found so far: 4,440
Processed chunk 12 | Total rows processed: 2,400,000 | Income=$1,000 rows found so far: 1,042 | Loan=$1,000 rows found so far: 4,808
Processed chunk 13 | Total rows processed: 2,600,000 | Income=$1,000 rows found so far: 1,135 | Loan=$1,000 rows found so far: 5,142
Processed chunk 14 | Total rows processed: 2,800,000 | Income=$1,000 rows found so far: 1,229 | Loan=$1,000 rows found so far: 5,486
Processed chunk 15 | Total rows processed: 3,000,000 | Income=$1,000 rows found so far: 1,315 | Loan=$1,000 rows found so far: 5,906
Processed chunk 16 | Total rows processed: 3,200,000 | Income=$1,000 rows found so far: 1,398 | Loan=$1,000 rows found so far: 6,229
Processed chunk 17 | Total rows processed: 3,400,000 | Income=$1,000 rows found so far: 1,480 | Loan=$1,000 rows found so far: 6,598
Processed chunk 18 | Total rows processed: 3,600,000 | Income=$1,000 rows found so far: 1,554 | Loan=$1,000 rows found so far: 6,914
Processed chunk 19 | Total rows processed: 3,800,000 | Income=$1,000 rows found so far: 1,655 | Loan=$1,000 rows found so far: 7,256
Processed chunk 20 | Total rows processed: 4,000,000 | Income=$1,000 rows found so far: 1,739 | Loan=$1,000 rows found so far: 7,589
Processed chunk 21 | Total rows processed: 4,200,000 | Income=$1,000 rows found so far: 1,843 | Loan=$1,000 rows found so far: 7,905
Processed chunk 22 | Total rows processed: 4,400,000 | Income=$1,000 rows found so far: 1,937 | Loan=$1,000 rows found so far: 8,222
Processed chunk 23 | Total rows processed: 4,600,000 | Income=$1,000 rows found so far: 2,020 | Loan=$1,000 rows found so far: 8,521
Processed chunk 24 | Total rows processed: 4,800,000 | Income=$1,000 rows found so far: 2,102 | Loan=$1,000 rows found so far: 8,781
Processed chunk 25 | Total rows processed: 5,000,000 | Income=$1,000 rows found so far: 2,200 | Loan=$1,000 rows found so far: 9,055
Processed chunk 26 | Total rows processed: 5,200,000 | Income=$1,000 rows found so far: 2,275 | Loan=$1,000 rows found so far: 9,377
Processed chunk 27 | Total rows processed: 5,400,000 | Income=$1,000 rows found so far: 2,357 | Loan=$1,000 rows found so far: 9,693
Processed chunk 28 | Total rows processed: 5,600,000 | Income=$1,000 rows found so far: 2,456 | Loan=$1,000 rows found so far: 10,026
Processed chunk 29 | Total rows processed: 5,800,000 | Income=$1,000 rows found so far: 2,561 | Loan=$1,000 rows found so far: 10,393
Processed chunk 30 | Total rows processed: 6,000,000 | Income=$1,000 rows found so far: 2,668 | Loan=$1,000 rows found so far: 10,761
Processed chunk 31 | Total rows processed: 6,200,000 | Income=$1,000 rows found so far: 2,777 | Loan=$1,000 rows found so far: 11,186
Processed chunk 32 | Total rows processed: 6,400,000 | Income=$1,000 rows found so far: 2,877 | Loan=$1,000 rows found so far: 11,623
Processed chunk 33 | Total rows processed: 6,600,000 | Income=$1,000 rows found so far: 3,017 | Loan=$1,000 rows found so far: 12,151
Processed chunk 34 | Total rows processed: 6,800,000 | Income=$1,000 rows found so far: 3,155 | Loan=$1,000 rows found so far: 12,580
Processed chunk 35 | Total rows processed: 7,000,000 | Income=$1,000 rows found so far: 3,280 | Loan=$1,000 rows found so far: 13,044
Processed chunk 36 | Total rows processed: 7,200,000 | Income=$1,000 rows found so far: 3,431 | Loan=$1,000 rows found so far: 13,446
Processed chunk 37 | Total rows processed: 7,400,000 | Income=$1,000 rows found so far: 3,569 | Loan=$1,000 rows found so far: 13,865
Processed chunk 38 | Total rows processed: 7,600,000 | Income=$1,000 rows found so far: 3,703 | Loan=$1,000 rows found so far: 14,293
Processed chunk 39 | Total rows processed: 7,800,000 | Income=$1,000 rows found so far: 3,857 | Loan=$1,000 rows found so far: 14,647
Processed chunk 40 | Total rows processed: 8,000,000 | Income=$1,000 rows found so far: 3,983 | Loan=$1,000 rows found so far: 15,074
Processed chunk 41 | Total rows processed: 8,064,813 | Income=$1,000 rows found so far: 4,027 | Loan=$1,000 rows found so far: 15,182

Overall loan_approved distribution in full dataset:

  loan_approved    count  percent
0             0  1593183    19.75
1             1  6471630    80.25

Final analysis done.
Total rows processed: 8,064,813
====================================================================================================
Group 1: Rows where applicant_income_000s = 1, meaning applicant income is $1,000
Rows in group: 4,027

Classification target distribution: group vs overall dataset

,loan_approved,overall_count,overall_percent,group_count,group_percent,group_minus_overall_percent
0,0,1593183,19.75,2963,73.58,53.83
1,1,6471630,80.25,1064,26.42,-53.83

Regression target distribution among approved rows only:

,approved_rows_for_regression,min,q1_25%,median_50%,mean,q3_75%,max,std
0,1064,1,139.0,197.5,215.016,276.25,1368,128.884

====================================================================================================
Group 2: Rows where loan_amount_000s = 1, meaning loan amount is $1,000
Rows in group: 15,182

Classification target distribution: group vs overall dataset

,loan_approved,overall_count,overall_percent,group_count,group_percent,group_minus_overall_percent
0,0,1593183,19.75,11951,78.72,58.97
1,1,6471630,80.25,3231,21.28,-58.97

Regression target distribution among approved rows only:

,approved_rows_for_regression,min,q1_25%,median_50%,mean,q3_75%,max,std
0,3231,1,1.0,1.0,1.0,1.0,1,0.0

====================================================================================================
Group 3: Top 100 rows with the highest applicant_income_000s
Rows in group: 100

Classification target distribution: group vs overall dataset

,loan_approved,overall_count,overall_percent,group_count,group_percent,group_minus_overall_percent
0,0,1593183,19.75,35,35.0,15.25
1,1,6471630,80.25,65,65.0,-15.25

Regression target distribution among approved rows only:

,approved_rows_for_regression,min,q1_25%,median_50%,mean,q3_75%,max,std
0,65,94,551.0,10000.0,73627.2,128000.0,320000,98933.832

====================================================================================================
Group 4: Top 100 rows with the highest loan_amount_000s
Rows in group: 100

Classification target distribution: group vs overall dataset

,loan_approved,overall_count,overall_percent,group_count,group_percent,group_minus_overall_percent
0,0,1593183,19.75,50,50.0,30.25
1,1,6471630,80.25,50,50.0,-30.25

Regression target distribution among approved rows only:

,approved_rows_for_regression,min,q1_25%,median_50%,mean,q3_75%,max,std
0,50,15000,19700.0,65500.0,102731.88,164750.0,320000,96943.238

## Step 11: Explore Features and Approval Rate

This step takes a random sample of 20,000 rows and studies how each feature relates to loan approval. Categorical features are grouped by their most common values, and numeric features are grouped into bins. The output shows approval and rejection rates for each group and highlights groups that are far from the overall approval rate.

In [10]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

# =========================================================
# 0. Settings
# =========================================================

DATA_PATH = Path("hmda_2017_classification_ready.csv")

CHUNK_SIZE = 200_000
SAMPLE_SIZE = 20_000
RANDOM_STATE = 42

TARGET_COL = "loan_approved"

TOP_N_CATEGORIES = 15
NUMERIC_BINS = 10

# Continuous / semi-continuous numeric columns
continuous_numeric_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "minority_population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# Columns that should not be analyzed as features
columns_to_skip = [
    TARGET_COL,
    "action_taken",
    "action_taken_name"
]

# =========================================================
# 1. Feature explanations
# =========================================================

feature_explanations = {
    "as_of_year": "Report year. Usually constant in this dataset.",
    "respondent_id": "Financial institution / lender identifier.",
    "agency_name": "Name of the supervising agency.",
    "agency_abbr": "Abbreviation of the supervising agency.",
    "agency_code": "Code of the supervising agency.",
    "loan_type_name": "Loan type label, such as Conventional, FHA, VA, or FSA/RHS.",
    "loan_type": "Loan type code.",
    "property_type_name": "Property type label.",
    "property_type": "Property type code.",
    "loan_purpose_name": "Loan purpose label: home purchase, refinancing, or home improvement.",
    "loan_purpose": "Loan purpose code.",
    "owner_occupancy_name": "Whether the property is owner-occupied.",
    "owner_occupancy": "Owner occupancy code.",
    "loan_amount_000s": "Loan amount in thousands of dollars.",
    "preapproval_name": "Preapproval status label.",
    "preapproval": "Preapproval status code.",
    "msamd_name": "Metropolitan statistical area / division name.",
    "msamd": "Metropolitan statistical area / division code.",
    "state_name": "State name.",
    "state_abbr": "State abbreviation.",
    "state_code": "State code.",
    "county_name": "County name.",
    "county_code": "County code.",
    "census_tract_number": "Census tract identifier.",
    "applicant_ethnicity_name": "Applicant ethnicity label.",
    "applicant_ethnicity": "Applicant ethnicity code.",
    "co_applicant_ethnicity_name": "Co-applicant ethnicity label.",
    "co_applicant_ethnicity": "Co-applicant ethnicity code.",
    "applicant_race_name_1": "Main applicant race label.",
    "applicant_race_1": "Main applicant race code.",
    "co_applicant_race_name_1": "Main co-applicant race label.",
    "co_applicant_race_1": "Main co-applicant race code.",
    "applicant_sex_name": "Applicant sex label.",
    "applicant_sex": "Applicant sex code.",
    "co_applicant_sex_name": "Co-applicant sex label.",
    "co_applicant_sex": "Co-applicant sex code.",
    "applicant_income_000s": "Applicant annual income in thousands of dollars.",
    "hoepa_status_name": "Whether the loan is a HOEPA high-cost loan.",
    "hoepa_status": "HOEPA status code.",
    "lien_status_name": "Lien status label.",
    "lien_status": "Lien status code.",
    "population": "Population of the census tract.",
    "minority_population": "Minority population percentage in the census tract.",
    "hud_median_family_income": "Median family income in the area.",
    "tract_to_msamd_income": "Tract income as a percentage of MSA/MD income.",
    "number_of_owner_occupied_units": "Number of owner-occupied housing units in the census tract.",
    "number_of_1_to_4_family_units": "Number of 1-to-4 family housing units in the census tract.",
    "loan_approved": "Classification target: 1 means approved/accepted, 0 means rejected."
}

# =========================================================
# 2. Take an in-memory random sample from the full dataset
# =========================================================

sample_df = None
total_rows_seen = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows_seen += len(chunk)

    # Strip whitespace from all values
    for col in chunk.columns:
        chunk[col] = chunk[col].astype(str).str.strip()

    # Keep a running in-memory random sample
    if sample_df is None:
        sample_df = chunk.copy()
    else:
        sample_df = pd.concat([sample_df, chunk], ignore_index=True)

    # Downsample if the temporary sample becomes larger than needed
    if len(sample_df) > SAMPLE_SIZE:
        sample_df = sample_df.sample(
            n=SAMPLE_SIZE,
            random_state=RANDOM_STATE + chunk_id
        ).reset_index(drop=True)

    print(
        f"Processed chunk {chunk_id} | "
        f"Rows seen: {total_rows_seen:,} | "
        f"Current sample size: {len(sample_df):,}"
    )

# Final shuffle
df_sample = sample_df.sample(
    frac=1,
    random_state=RANDOM_STATE
).reset_index(drop=True)

print("\nFinal in-memory sample shape:", df_sample.shape)
display(df_sample.head())

# =========================================================
# 3. Prepare target distribution
# =========================================================

if TARGET_COL not in df_sample.columns:
    raise ValueError(f"Target column '{TARGET_COL}' was not found.")

df_sample[TARGET_COL] = df_sample[TARGET_COL].astype(str).str.strip()

overall_counts = df_sample[TARGET_COL].value_counts(dropna=False).sort_index()
overall_percent = (overall_counts / overall_counts.sum() * 100).round(2)

overall_target_distribution = pd.DataFrame({
    TARGET_COL: overall_counts.index,
    "overall_count": overall_counts.values,
    "overall_percent": overall_percent.values
})

print("\nOverall target distribution in the 20,000-row sample:")
display(overall_target_distribution)

overall_approval_rate = pd.to_numeric(
    df_sample[TARGET_COL],
    errors="coerce"
).mean()

overall_rejection_rate = 1 - overall_approval_rate

print("Overall approval rate:", round(overall_approval_rate * 100, 2), "%")
print("Overall rejection rate:", round(overall_rejection_rate * 100, 2), "%")

# =========================================================
# 4. Helper functions
# =========================================================

def is_numeric_feature(df, col, numeric_cols):
    """
    Decide whether a feature should be treated as numeric.
    Some code columns look numeric but are actually categorical.
    """
    if col in numeric_cols:
        return True

    numeric_s = pd.to_numeric(df[col], errors="coerce")
    numeric_ratio = numeric_s.notna().mean()

    return numeric_ratio > 0.95 and df[col].nunique(dropna=False) > 20


def make_binned_numeric_feature(df, col, n_bins=10):
    """
    Convert a numeric column into quantile bins.
    This makes target distribution easier to compare.
    """
    numeric_s = pd.to_numeric(df[col], errors="coerce")

    if numeric_s.nunique(dropna=True) < 3:
        return numeric_s.astype(str)

    try:
        binned = pd.qcut(
            numeric_s,
            q=n_bins,
            duplicates="drop"
        )
        return binned.astype(str)
    except Exception:
        return numeric_s.astype(str)


def make_categorical_feature_limited(df, col, top_n=15):
    """
    Keep only top N categories.
    Less frequent categories are grouped as Other.
    """
    s = df[col].astype(str).str.strip()

    top_categories = s.value_counts(dropna=False).head(top_n).index

    limited = s.where(s.isin(top_categories), other="Other")

    return limited


def target_distribution_by_feature(
    df,
    feature_col,
    target_col=TARGET_COL,
    numeric_cols=continuous_numeric_cols,
    top_n_categories=15,
    numeric_bins=10
):
    """
    Create one target distribution table for one feature.
    Numeric features are binned.
    Categorical features are limited to top categories.
    """
    temp = df[[feature_col, target_col]].copy()

    temp[target_col] = temp[target_col].astype(str).str.strip()

    if is_numeric_feature(temp, feature_col, numeric_cols):
        temp["feature_group"] = make_binned_numeric_feature(
            temp,
            feature_col,
            n_bins=numeric_bins
        )
        feature_type = "numeric_binned"
    else:
        temp["feature_group"] = make_categorical_feature_limited(
            temp,
            feature_col,
            top_n=top_n_categories
        )
        feature_type = "categorical_limited"

    grouped = (
        temp
        .groupby(["feature_group", target_col])
        .size()
        .reset_index(name="count")
    )

    pivot = grouped.pivot_table(
        index="feature_group",
        columns=target_col,
        values="count",
        fill_value=0
    ).reset_index()

    if "0" not in pivot.columns:
        pivot["0"] = 0

    if "1" not in pivot.columns:
        pivot["1"] = 0

    pivot = pivot.rename(columns={
        "0": "rejected_count",
        "1": "approved_count"
    })

    pivot["total_count"] = pivot["rejected_count"] + pivot["approved_count"]

    pivot["approved_percent"] = (
        pivot["approved_count"] / pivot["total_count"] * 100
    ).round(2)

    pivot["rejected_percent"] = (
        pivot["rejected_count"] / pivot["total_count"] * 100
    ).round(2)

    pivot["overall_approved_percent"] = round(overall_approval_rate * 100, 2)
    pivot["overall_rejected_percent"] = round(overall_rejection_rate * 100, 2)

    pivot["approved_percent_minus_overall"] = (
        pivot["approved_percent"] - pivot["overall_approved_percent"]
    ).round(2)

    pivot["feature"] = feature_col
    pivot["feature_type"] = feature_type
    pivot["feature_explanation"] = feature_explanations.get(
        feature_col,
        "No manual explanation provided for this feature."
    )

    pivot = pivot[
        [
            "feature",
            "feature_explanation",
            "feature_type",
            "feature_group",
            "total_count",
            "approved_count",
            "rejected_count",
            "approved_percent",
            "rejected_percent",
            "overall_approved_percent",
            "overall_rejected_percent",
            "approved_percent_minus_overall"
        ]
    ]

    pivot = pivot.sort_values(
        "total_count",
        ascending=False
    ).reset_index(drop=True)

    return pivot


# =========================================================
# 5. Show target distribution for each feature
# =========================================================

feature_cols = [
    col for col in df_sample.columns
    if col not in columns_to_skip
]

all_feature_tables = {}

for col in feature_cols:
    print("=" * 120)
    print(f"Feature: {col}")
    print("Explanation:", feature_explanations.get(
        col,
        "No manual explanation provided for this feature."
    ))

    feature_table = target_distribution_by_feature(
        df_sample,
        feature_col=col,
        target_col=TARGET_COL,
        numeric_cols=continuous_numeric_cols,
        top_n_categories=TOP_N_CATEGORIES,
        numeric_bins=NUMERIC_BINS
    )

    all_feature_tables[col] = feature_table

    display(feature_table)

# =========================================================
# 6. Optional: one combined dataframe inside memory only
# =========================================================

all_feature_distributions_df = pd.concat(
    all_feature_tables.values(),
    ignore_index=True
)

print("=" * 120)
print("Combined in-memory table shape:", all_feature_distributions_df.shape)
display(all_feature_distributions_df.head(50))

# =========================================================
# 7. Optional: show strongest differences from overall approval rate
# =========================================================

important_groups = all_feature_distributions_df[
    all_feature_distributions_df["total_count"] >= 50
].copy()

important_groups["abs_difference"] = (
    important_groups["approved_percent_minus_overall"]
    .abs()
)

important_groups = important_groups.sort_values(
    "abs_difference",
    ascending=False
).reset_index(drop=True)

print("=" * 120)
print("Feature groups with strongest difference from overall approval rate:")
display(important_groups.head(50))

Processed chunk 1 | Rows seen: 200,000 | Current sample size: 20,000
Processed chunk 2 | Rows seen: 400,000 | Current sample size: 20,000
Processed chunk 3 | Rows seen: 600,000 | Current sample size: 20,000
Processed chunk 4 | Rows seen: 800,000 | Current sample size: 20,000
Processed chunk 5 | Rows seen: 1,000,000 | Current sample size: 20,000
Processed chunk 6 | Rows seen: 1,200,000 | Current sample size: 20,000
Processed chunk 7 | Rows seen: 1,400,000 | Current sample size: 20,000
Processed chunk 8 | Rows seen: 1,600,000 | Current sample size: 20,000
Processed chunk 9 | Rows seen: 1,800,000 | Current sample size: 20,000
Processed chunk 10 | Rows seen: 2,000,000 | Current sample size: 20,000
Processed chunk 11 | Rows seen: 2,200,000 | Current sample size: 20,000
Processed chunk 12 | Rows seen: 2,400,000 | Current sample size: 20,000
Processed chunk 13 | Rows seen: 2,600,000 | Current sample size: 20,000
Processed chunk 14 | Rows seen: 2,800,000 | Current sample size: 20,000
Processed chunk 15 | Rows seen: 3,000,000 | Current sample size: 20,000
Processed chunk 16 | Rows seen: 3,200,000 | Current sample size: 20,000
Processed chunk 17 | Rows seen: 3,400,000 | Current sample size: 20,000
Processed chunk 18 | Rows seen: 3,600,000 | Current sample size: 20,000
Processed chunk 19 | Rows seen: 3,800,000 | Current sample size: 20,000
Processed chunk 20 | Rows seen: 4,000,000 | Current sample size: 20,000
Processed chunk 21 | Rows seen: 4,200,000 | Current sample size: 20,000
Processed chunk 22 | Rows seen: 4,400,000 | Current sample size: 20,000
Processed chunk 23 | Rows seen: 4,600,000 | Current sample size: 20,000
Processed chunk 24 | Rows seen: 4,800,000 | Current sample size: 20,000
Processed chunk 25 | Rows seen: 5,000,000 | Current sample size: 20,000
Processed chunk 26 | Rows seen: 5,200,000 | Current sample size: 20,000
Processed chunk 27 | Rows seen: 5,400,000 | Current sample size: 20,000
Processed chunk 28 | Rows seen: 5,600,000 | Current sample size: 20,000
Processed chunk 29 | Rows seen: 5,800,000 | Current sample size: 20,000
Processed chunk 30 | Rows seen: 6,000,000 | Current sample size: 20,000
Processed chunk 31 | Rows seen: 6,200,000 | Current sample size: 20,000
Processed chunk 32 | Rows seen: 6,400,000 | Current sample size: 20,000
Processed chunk 33 | Rows seen: 6,600,000 | Current sample size: 20,000
Processed chunk 34 | Rows seen: 6,800,000 | Current sample size: 20,000
Processed chunk 35 | Rows seen: 7,000,000 | Current sample size: 20,000
Processed chunk 36 | Rows seen: 7,200,000 | Current sample size: 20,000
Processed chunk 37 | Rows seen: 7,400,000 | Current sample size: 20,000
Processed chunk 38 | Rows seen: 7,600,000 | Current sample size: 20,000
Processed chunk 39 | Rows seen: 7,800,000 | Current sample size: 20,000
Processed chunk 40 | Rows seen: 8,000,000 | Current sample size: 20,000
Processed chunk 41 | Rows seen: 8,074,536 | Current sample size: 20,000

Final in-memory sample shape: (20000, 52)

,as_of_year,respondent_id,agency_name,agency_abbr,agency_code,loan_type_name,loan_type,property_type_name,property_type,loan_purpose_name,...,hoepa_status,lien_status_name,lien_status,population,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units,loan_approved
0,2017,0001842065,Consumer Financial Protection Bureau,CFPB,9,Conventional,1,One-to-four family dwelling (other than manufa...,1,Refinancing,...,2,Secured by a first lien,1,2577,5.940000057220459,69000,98.81999969482422,828,1145,0
1,2017,42-1554181,Department of Housing and Urban Development,HUD,7,Conventional,1,One-to-four family dwelling (other than manufa...,1,Home purchase,...,2,Secured by a first lien,1,13466,10.369999885559082,64300,139.00999450683594,3567,4547,1
2,2017,0000476810,Consumer Financial Protection Bureau,CFPB,9,Conventional,1,One-to-four family dwelling (other than manufa...,1,Home improvement,...,2,Secured by a first lien,1,6256,51.279998779296875,73700,113.44000244140625,554,396,1
3,2017,0542409990,Department of Housing and Urban Development,HUD,7,VA-guaranteed,3,One-to-four family dwelling (other than manufa...,1,Home purchase,...,2,Secured by a first lien,1,5026,12.100000381469727,64300,124.80999755859375,1528,1934,1
4,2017,0000013573,National Credit Union Administration,NCUA,5,Conventional,1,One-to-four family dwelling (other than manufa...,1,Home improvement,...,2,Secured by a first lien,1,2475,24.889999389648438,67700,68.31999969482422,828,1043,0

Overall target distribution in the 20,000-row sample:

  loan_approved  overall_count  overall_percent
0             0           5784            28.92
1             1          14216            71.08

Overall approval rate: 71.08 %
Overall rejection rate: 28.92 %
========================================================================================================================
Feature: as_of_year
Explanation: Report year. Usually constant in this dataset.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,as_of_year,Report year. Usually constant in this dataset.,categorical_limited,2017,20000.0,14216.0,5784.0,71.08,28.92,71.08,28.92,0.0

========================================================================================================================
Feature: respondent_id
Explanation: Financial institution / lender identifier.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,respondent_id,Financial institution / lender identifier.,categorical_limited,Other,13893.0,10358.0,3535.0,74.56,25.44,71.08,28.92,3.48
1,respondent_id,Financial institution / lender identifier.,categorical_limited,7197000003,1603.0,1016.0,587.0,63.38,36.62,71.08,28.92,-7.70
2,respondent_id,Financial institution / lender identifier.,categorical_limited,0000451965,902.0,542.0,360.0,60.09,39.91,71.08,28.92,-10.99
3,respondent_id,Financial institution / lender identifier.,categorical_limited,26-4599244,481.0,329.0,152.0,68.40,31.60,71.08,28.92,-2.68
4,respondent_id,Financial institution / lender identifier.,categorical_limited,0000852218,417.0,318.0,99.0,76.26,23.74,71.08,28.92,5.18
5,respondent_id,Financial institution / lender identifier.,categorical_limited,0000504713,325.0,154.0,171.0,47.38,52.62,71.08,28.92,-23.70
6,respondent_id,Financial institution / lender identifier.,categorical_limited,0000617677,320.0,211.0,109.0,65.94,34.06,71.08,28.92,-5.14
7,respondent_id,Financial institution / lender identifier.,categorical_limited,38-2750395,281.0,239.0,42.0,85.05,14.95,71.08,28.92,13.97
8,respondent_id,Financial institution / lender identifier.,categorical_limited,0000480228,275.0,206.0,69.0,74.91,25.09,71.08,28.92,3.83
9,respondent_id,Financial institution / lender identifier.,categorical_limited,13-6131491,260.0,206.0,54.0,79.23,20.77,71.08,28.92,8.15
10,respondent_id,Financial institution / lender identifier.,categorical_limited,0000146672,234.0,172.0,62.0,73.50,26.50,71.08,28.92,2.42
11,respondent_id,Financial institution / lender identifier.,categorical_limited,0000817824,234.0,121.0,113.0,51.71,48.29,71.08,28.92,-19.37
12,respondent_id,Financial institution / lender identifier.,categorical_limited,0000675332,208.0,53.0,155.0,25.48,74.52,71.08,28.92,-45.60
13,respondent_id,Financial institution / lender identifier.,categorical_limited,75-2921540,196.0,73.0,123.0,37.24,62.76,71.08,28.92,-33.84
14,respondent_id,Financial institution / lender identifier.,categorical_limited,41-1795868,188.0,106.0,82.0,56.38,43.62,71.08,28.92,-14.70
15,respondent_id,Financial institution / lender identifier.,categorical_limited,0000012311,183.0,112.0,71.0,61.20,38.80,71.08,28.92,-9.88

========================================================================================================================
Feature: agency_name
Explanation: Name of the supervising agency.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,agency_name,Name of the supervising agency.,categorical_limited,Department of Housing and Urban Development,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
1,agency_name,Name of the supervising agency.,categorical_limited,Consumer Financial Protection Bureau,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
2,agency_name,Name of the supervising agency.,categorical_limited,National Credit Union Administration,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
3,agency_name,Name of the supervising agency.,categorical_limited,Federal Deposit Insurance Corporation,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
4,agency_name,Name of the supervising agency.,categorical_limited,Office of the Comptroller of the Currency,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
5,agency_name,Name of the supervising agency.,categorical_limited,Federal Reserve System,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07

========================================================================================================================
Feature: agency_abbr
Explanation: Abbreviation of the supervising agency.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,HUD,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
1,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,CFPB,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
2,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,NCUA,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
3,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,FDIC,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
4,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,OCC,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
5,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,FRS,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07

========================================================================================================================
Feature: agency_code
Explanation: Code of the supervising agency.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,agency_code,Code of the supervising agency.,categorical_limited,7,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
1,agency_code,Code of the supervising agency.,categorical_limited,9,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
2,agency_code,Code of the supervising agency.,categorical_limited,5,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
3,agency_code,Code of the supervising agency.,categorical_limited,3,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
4,agency_code,Code of the supervising agency.,categorical_limited,1,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
5,agency_code,Code of the supervising agency.,categorical_limited,2,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07

========================================================================================================================
Feature: loan_type_name
Explanation: Loan type label, such as Conventional, FHA, VA, or FSA/RHS.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,Conventional,14807.0,10532.0,4275.0,71.13,28.87,71.08,28.92,0.05
1,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,FHA-insured,3319.0,2339.0,980.0,70.47,29.53,71.08,28.92,-0.61
2,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,VA-guaranteed,1659.0,1182.0,477.0,71.25,28.75,71.08,28.92,0.17
3,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,FSA/RHS-guaranteed,215.0,163.0,52.0,75.81,24.19,71.08,28.92,4.73

========================================================================================================================
Feature: loan_type
Explanation: Loan type code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,loan_type,Loan type code.,categorical_limited,1,14807.0,10532.0,4275.0,71.13,28.87,71.08,28.92,0.05
1,loan_type,Loan type code.,categorical_limited,2,3319.0,2339.0,980.0,70.47,29.53,71.08,28.92,-0.61
2,loan_type,Loan type code.,categorical_limited,3,1659.0,1182.0,477.0,71.25,28.75,71.08,28.92,0.17
3,loan_type,Loan type code.,categorical_limited,4,215.0,163.0,52.0,75.81,24.19,71.08,28.92,4.73

========================================================================================================================
Feature: property_type_name
Explanation: Property type label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,property_type_name,Property type label.,categorical_limited,One-to-four family dwelling (other than manufa...,19350.0,13947.0,5403.0,72.08,27.92,71.08,28.92,1.0
1,property_type_name,Property type label.,categorical_limited,Manufactured housing,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.7

========================================================================================================================
Feature: property_type
Explanation: Property type code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,property_type,Property type code.,categorical_limited,1,19350.0,13947.0,5403.0,72.08,27.92,71.08,28.92,1.0
1,property_type,Property type code.,categorical_limited,2,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.7

========================================================================================================================
Feature: loan_purpose_name
Explanation: Loan purpose label: home purchase, refinancing, or home improvement.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Home purchase,10462.0,8521.0,1941.0,81.45,18.55,71.08,28.92,10.37
1,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Refinancing,7499.0,4670.0,2829.0,62.27,37.73,71.08,28.92,-8.81
2,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Home improvement,2039.0,1025.0,1014.0,50.27,49.73,71.08,28.92,-20.81

========================================================================================================================
Feature: loan_purpose
Explanation: Loan purpose code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,loan_purpose,Loan purpose code.,categorical_limited,1,10462.0,8521.0,1941.0,81.45,18.55,71.08,28.92,10.37
1,loan_purpose,Loan purpose code.,categorical_limited,3,7499.0,4670.0,2829.0,62.27,37.73,71.08,28.92,-8.81
2,loan_purpose,Loan purpose code.,categorical_limited,2,2039.0,1025.0,1014.0,50.27,49.73,71.08,28.92,-20.81

========================================================================================================================
Feature: owner_occupancy_name
Explanation: Whether the property is owner-occupied.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,owner_occupancy_name,Whether the property is owner-occupied.,categorical_limited,Owner-occupied as a principal dwelling,18219.0,12996.0,5223.0,71.33,28.67,71.08,28.92,0.25
1,owner_occupancy_name,Whether the property is owner-occupied.,categorical_limited,Not owner-occupied as a principal dwelling,1773.0,1212.0,561.0,68.36,31.64,71.08,28.92,-2.72
2,owner_occupancy_name,Whether the property is owner-occupied.,categorical_limited,Not applicable,8.0,8.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: owner_occupancy
Explanation: Owner occupancy code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,owner_occupancy,Owner occupancy code.,categorical_limited,1,18219.0,12996.0,5223.0,71.33,28.67,71.08,28.92,0.25
1,owner_occupancy,Owner occupancy code.,categorical_limited,2,1773.0,1212.0,561.0,68.36,31.64,71.08,28.92,-2.72
2,owner_occupancy,Owner occupancy code.,categorical_limited,3,8.0,8.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: loan_amount_000s
Explanation: Loan amount in thousands of dollars.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(316.0, 424.0]",2164.0,1717.0,447.0,79.34,20.66,71.08,28.92,8.26
1,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(121.0, 150.0]",2082.0,1495.0,587.0,71.81,28.19,71.08,28.92,0.73
2,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(48.0, 90.0]",2051.0,1264.0,787.0,61.63,38.37,71.08,28.92,-9.45
3,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(0.999, 48.0]",2016.0,991.0,1025.0,49.16,50.84,71.08,28.92,-21.92
4,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(213.0, 255.0]",2014.0,1543.0,471.0,76.61,23.39,71.08,28.92,5.53
5,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(255.0, 316.0]",1969.0,1560.0,409.0,79.23,20.77,71.08,28.92,8.15
6,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(180.0, 213.0]",1967.0,1489.0,478.0,75.70,24.30,71.08,28.92,4.62
7,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(90.0, 121.0]",1962.0,1342.0,620.0,68.40,31.60,71.08,28.92,-2.68
8,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(150.0, 180.0]",1947.0,1421.0,526.0,72.98,27.02,71.08,28.92,1.90
9,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(424.0, 15000.0]",1828.0,1394.0,434.0,76.26,23.74,71.08,28.92,5.18

========================================================================================================================
Feature: preapproval_name
Explanation: Preapproval status label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,preapproval_name,Preapproval status label.,categorical_limited,Not applicable,15657.0,10612.0,5045.0,67.78,32.22,71.08,28.92,-3.30
1,preapproval_name,Preapproval status label.,categorical_limited,Preapproval was not requested,3772.0,3114.0,658.0,82.56,17.44,71.08,28.92,11.48
2,preapproval_name,Preapproval status label.,categorical_limited,Preapproval was requested,571.0,490.0,81.0,85.81,14.19,71.08,28.92,14.73

========================================================================================================================
Feature: preapproval
Explanation: Preapproval status code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,preapproval,Preapproval status code.,categorical_limited,3,15657.0,10612.0,5045.0,67.78,32.22,71.08,28.92,-3.30
1,preapproval,Preapproval status code.,categorical_limited,2,3772.0,3114.0,658.0,82.56,17.44,71.08,28.92,11.48
2,preapproval,Preapproval status code.,categorical_limited,1,571.0,490.0,81.0,85.81,14.19,71.08,28.92,14.73

========================================================================================================================
Feature: msamd_name
Explanation: Metropolitan statistical area / division name.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,msamd_name,Metropolitan statistical area / division name.,categorical_limited,Other,8210.0,5586.0,2624.0,68.04,31.96,71.08,28.92,-3.04
1,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Chicago, Naperville, Arlington Heights - IL",1486.0,1023.0,463.0,68.84,31.16,71.08,28.92,-2.24
2,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"San Diego, Carlsbad - CA",1198.0,919.0,279.0,76.71,23.29,71.08,28.92,5.63
3,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Washington, Arlington, Alexandria - DC, VA, MD...",1156.0,889.0,267.0,76.90,23.10,71.08,28.92,5.82
4,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Houston, The Woodlands, Sugar Land - TX",1051.0,838.0,213.0,79.73,20.27,71.08,28.92,8.65
5,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Las Vegas, Henderson, Paradise - NV",867.0,679.0,188.0,78.32,21.68,71.08,28.92,7.24
6,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Charleston, North Charleston - SC",837.0,611.0,226.0,73.00,27.00,71.08,28.92,1.92
7,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"New York, Jersey City, White Plains - NY, NJ",727.0,413.0,314.0,56.81,43.19,71.08,28.92,-14.27
8,msamd_name,Metropolitan statistical area / division name.,categorical_limited,Bakersfield - CA,699.0,564.0,135.0,80.69,19.31,71.08,28.92,9.61
9,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Warren, Troy, Farmington Hills - MI",693.0,456.0,237.0,65.80,34.20,71.08,28.92,-5.28
10,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"New Haven, Milford - CT",612.0,460.0,152.0,75.16,24.84,71.08,28.92,4.08
11,msamd_name,Metropolitan statistical area / division name.,categorical_limited,Akron - OH,553.0,412.0,141.0,74.50,25.50,71.08,28.92,3.42
12,msamd_name,Metropolitan statistical area / division name.,categorical_limited,Port St. Lucie - FL,520.0,400.0,120.0,76.92,23.08,71.08,28.92,5.84
13,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Riverside, San Bernardino, Ontario - CA",466.0,246.0,220.0,52.79,47.21,71.08,28.92,-18.29
14,msamd_name,Metropolitan statistical area / division name.,categorical_limited,Baton Rouge - LA,464.0,358.0,106.0,77.16,22.84,71.08,28.92,6.08
15,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Albany, Schenectady, Troy - NY",461.0,362.0,99.0,78.52,21.48,71.08,28.92,7.44

========================================================================================================================
Feature: msamd
Explanation: Metropolitan statistical area / division code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,msamd,Metropolitan statistical area / division code.,numeric_binned,"(12940.0, 16974.0]",2978.0,2069.0,909.0,69.48,30.52,71.08,28.92,-1.60
1,msamd,Metropolitan statistical area / division code.,numeric_binned,"(19300.0, 26420.0]",2852.0,1925.0,927.0,67.50,32.50,71.08,28.92,-3.58
2,msamd,Metropolitan statistical area / division code.,numeric_binned,"(41540.0, 47664.0]",2487.0,1722.0,765.0,69.24,30.76,71.08,28.92,-1.84
3,msamd,Metropolitan statistical area / division code.,numeric_binned,"(10379.999, 12940.0]",2332.0,1793.0,539.0,76.89,23.11,71.08,28.92,5.81
4,msamd,Metropolitan statistical area / division code.,numeric_binned,"(34740.0, 35980.0]",2032.0,1442.0,590.0,70.96,29.04,71.08,28.92,-0.12
5,msamd,Metropolitan statistical area / division code.,numeric_binned,"(26420.0, 29820.0]",1904.0,1354.0,550.0,71.11,28.89,71.08,28.92,0.03
6,msamd,Metropolitan statistical area / division code.,numeric_binned,"(35980.0, 41540.0]",1874.0,1287.0,587.0,68.68,31.32,71.08,28.92,-2.40
7,msamd,Metropolitan statistical area / division code.,numeric_binned,"(47664.0, 49660.0]",1500.0,1128.0,372.0,75.20,24.80,71.08,28.92,4.12
8,msamd,Metropolitan statistical area / division code.,numeric_binned,"(29820.0, 34740.0]",1296.0,930.0,366.0,71.76,28.24,71.08,28.92,0.68
9,msamd,Metropolitan statistical area / division code.,numeric_binned,"(16974.0, 19300.0]",745.0,566.0,179.0,75.97,24.03,71.08,28.92,4.89

========================================================================================================================
Feature: state_name
Explanation: State name.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,state_name,State name.,categorical_limited,California,2945.0,2075.0,870.0,70.46,29.54,71.08,28.92,-0.62
1,state_name,State name.,categorical_limited,Illinois,1570.0,1093.0,477.0,69.62,30.38,71.08,28.92,-1.46
2,state_name,State name.,categorical_limited,Florida,1484.0,1010.0,474.0,68.06,31.94,71.08,28.92,-3.02
3,state_name,State name.,categorical_limited,New York,1481.0,1002.0,479.0,67.66,32.34,71.08,28.92,-3.42
4,state_name,State name.,categorical_limited,Virginia,1436.0,1085.0,351.0,75.56,24.44,71.08,28.92,4.48
5,state_name,State name.,categorical_limited,South Carolina,1420.0,984.0,436.0,69.30,30.70,71.08,28.92,-1.78
6,state_name,State name.,categorical_limited,Connecticut,1401.0,993.0,408.0,70.88,29.12,71.08,28.92,-0.20
7,state_name,State name.,categorical_limited,Texas,1332.0,974.0,358.0,73.12,26.88,71.08,28.92,2.04
8,state_name,State name.,categorical_limited,Michigan,1331.0,960.0,371.0,72.13,27.87,71.08,28.92,1.05
9,state_name,State name.,categorical_limited,Ohio,1230.0,872.0,358.0,70.89,29.11,71.08,28.92,-0.19
10,state_name,State name.,categorical_limited,Louisiana,1105.0,815.0,290.0,73.76,26.24,71.08,28.92,2.68
11,state_name,State name.,categorical_limited,Nevada,867.0,679.0,188.0,78.32,21.68,71.08,28.92,7.24
12,state_name,State name.,categorical_limited,Alabama,774.0,576.0,198.0,74.42,25.58,71.08,28.92,3.34
13,state_name,State name.,categorical_limited,Wisconsin,735.0,520.0,215.0,70.75,29.25,71.08,28.92,-0.33
14,state_name,State name.,categorical_limited,Other,671.0,445.0,226.0,66.32,33.68,71.08,28.92,-4.76
15,state_name,State name.,categorical_limited,Nebraska,218.0,133.0,85.0,61.01,38.99,71.08,28.92,-10.07

========================================================================================================================
Feature: state_abbr
Explanation: State abbreviation.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,state_abbr,State abbreviation.,categorical_limited,CA,2945.0,2075.0,870.0,70.46,29.54,71.08,28.92,-0.62
1,state_abbr,State abbreviation.,categorical_limited,IL,1570.0,1093.0,477.0,69.62,30.38,71.08,28.92,-1.46
2,state_abbr,State abbreviation.,categorical_limited,FL,1484.0,1010.0,474.0,68.06,31.94,71.08,28.92,-3.02
3,state_abbr,State abbreviation.,categorical_limited,NY,1481.0,1002.0,479.0,67.66,32.34,71.08,28.92,-3.42
4,state_abbr,State abbreviation.,categorical_limited,VA,1436.0,1085.0,351.0,75.56,24.44,71.08,28.92,4.48
5,state_abbr,State abbreviation.,categorical_limited,SC,1420.0,984.0,436.0,69.30,30.70,71.08,28.92,-1.78
6,state_abbr,State abbreviation.,categorical_limited,CT,1401.0,993.0,408.0,70.88,29.12,71.08,28.92,-0.20
7,state_abbr,State abbreviation.,categorical_limited,TX,1332.0,974.0,358.0,73.12,26.88,71.08,28.92,2.04
8,state_abbr,State abbreviation.,categorical_limited,MI,1331.0,960.0,371.0,72.13,27.87,71.08,28.92,1.05
9,state_abbr,State abbreviation.,categorical_limited,OH,1230.0,872.0,358.0,70.89,29.11,71.08,28.92,-0.19
10,state_abbr,State abbreviation.,categorical_limited,LA,1105.0,815.0,290.0,73.76,26.24,71.08,28.92,2.68
11,state_abbr,State abbreviation.,categorical_limited,NV,867.0,679.0,188.0,78.32,21.68,71.08,28.92,7.24
12,state_abbr,State abbreviation.,categorical_limited,AL,774.0,576.0,198.0,74.42,25.58,71.08,28.92,3.34
13,state_abbr,State abbreviation.,categorical_limited,WI,735.0,520.0,215.0,70.75,29.25,71.08,28.92,-0.33
14,state_abbr,State abbreviation.,categorical_limited,Other,671.0,445.0,226.0,66.32,33.68,71.08,28.92,-4.76
15,state_abbr,State abbreviation.,categorical_limited,NE,218.0,133.0,85.0,61.01,38.99,71.08,28.92,-10.07

========================================================================================================================
Feature: state_code
Explanation: State code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,state_code,State code.,numeric_binned,"(0.999, 6.0]",3721.0,2653.0,1068.0,71.30,28.70,71.08,28.92,0.22
1,state_code,State code.,numeric_binned,"(45.0, 51.0]",2793.0,2074.0,719.0,74.26,25.74,71.08,28.92,3.18
2,state_code,State code.,numeric_binned,"(26.0, 36.0]",2581.0,1819.0,762.0,70.48,29.52,71.08,28.92,-0.60
3,state_code,State code.,numeric_binned,"(17.0, 26.0]",2576.0,1829.0,747.0,71.00,29.00,71.08,28.92,-0.08
4,state_code,State code.,numeric_binned,"(9.0, 12.0]",1582.0,1091.0,491.0,68.96,31.04,71.08,28.92,-2.12
5,state_code,State code.,numeric_binned,"(12.0, 17.0]",1572.0,1095.0,477.0,69.66,30.34,71.08,28.92,-1.42
6,state_code,State code.,numeric_binned,"(39.0, 45.0]",1504.0,1035.0,469.0,68.82,31.18,71.08,28.92,-2.26
7,state_code,State code.,numeric_binned,"(6.0, 9.0]",1426.0,1005.0,421.0,70.48,29.52,71.08,28.92,-0.60
8,state_code,State code.,numeric_binned,"(36.0, 39.0]",1232.0,874.0,358.0,70.94,29.06,71.08,28.92,-0.14
9,state_code,State code.,numeric_binned,"(51.0, 72.0]",1013.0,741.0,272.0,73.15,26.85,71.08,28.92,2.07

========================================================================================================================
Feature: county_name
Explanation: County name.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,county_name,County name.,categorical_limited,Other,10159.0,6907.0,3252.0,67.99,32.01,71.08,28.92,-3.09
1,county_name,County name.,categorical_limited,San Diego County,1198.0,919.0,279.0,76.71,23.29,71.08,28.92,5.63
2,county_name,County name.,categorical_limited,Fairfax County,993.0,777.0,216.0,78.25,21.75,71.08,28.92,7.17
3,county_name,County name.,categorical_limited,DuPage County,886.0,765.0,121.0,86.34,13.66,71.08,28.92,15.26
4,county_name,County name.,categorical_limited,Clark County,867.0,679.0,188.0,78.32,21.68,71.08,28.92,7.24
5,county_name,County name.,categorical_limited,Fort Bend County,762.0,578.0,184.0,75.85,24.15,71.08,28.92,4.77
6,county_name,County name.,categorical_limited,Kern County,699.0,564.0,135.0,80.69,19.31,71.08,28.92,9.61
7,county_name,County name.,categorical_limited,New Haven County,612.0,460.0,152.0,75.16,24.84,71.08,28.92,4.08
8,county_name,County name.,categorical_limited,Cook County,588.0,248.0,340.0,42.18,57.82,71.08,28.92,-28.90
9,county_name,County name.,categorical_limited,Macomb County,532.0,338.0,194.0,63.53,36.47,71.08,28.92,-7.55
10,county_name,County name.,categorical_limited,St. Lucie County,520.0,400.0,120.0,76.92,23.08,71.08,28.92,5.84
11,county_name,County name.,categorical_limited,Summit County,514.0,400.0,114.0,77.82,22.18,71.08,28.92,6.74
12,county_name,County name.,categorical_limited,San Bernardino County,465.0,245.0,220.0,52.69,47.31,71.08,28.92,-18.39
13,county_name,County name.,categorical_limited,Charleston County,429.0,319.0,110.0,74.36,25.64,71.08,28.92,3.28
14,county_name,County name.,categorical_limited,Baldwin County,389.0,301.0,88.0,77.38,22.62,71.08,28.92,6.30
15,county_name,County name.,categorical_limited,East Baton Rouge Parish,387.0,316.0,71.0,81.65,18.35,71.08,28.92,10.57

========================================================================================================================
Feature: county_code
Explanation: County code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,county_code,County code.,numeric_binned,"(0.999, 9.0]",2654.0,1906.0,748.0,71.82,28.18,71.08,28.92,0.74
1,county_code,County code.,numeric_binned,"(29.0, 43.0]",2581.0,1871.0,710.0,72.49,27.51,71.08,28.92,1.41
2,county_code,County code.,numeric_binned,"(61.0, 81.0]",2335.0,1548.0,787.0,66.30,33.70,71.08,28.92,-4.78
3,county_code,County code.,numeric_binned,"(9.0, 19.0]",2169.0,1443.0,726.0,66.53,33.47,71.08,28.92,-4.55
4,county_code,County code.,numeric_binned,"(115.0, 153.0]",2107.0,1464.0,643.0,69.48,30.52,71.08,28.92,-1.60
5,county_code,County code.,numeric_binned,"(81.0, 103.0]",1958.0,1330.0,628.0,67.93,32.07,71.08,28.92,-3.15
6,county_code,County code.,numeric_binned,"(103.0, 115.0]",1856.0,1296.0,560.0,69.83,30.17,71.08,28.92,-1.25
7,county_code,County code.,numeric_binned,"(153.0, 510.0]",1729.0,1336.0,393.0,77.27,22.73,71.08,28.92,6.19
8,county_code,County code.,numeric_binned,"(43.0, 61.0]",1430.0,1086.0,344.0,75.94,24.06,71.08,28.92,4.86
9,county_code,County code.,numeric_binned,"(19.0, 29.0]",1181.0,936.0,245.0,79.25,20.75,71.08,28.92,8.17

========================================================================================================================
Feature: census_tract_number
Explanation: Census tract identifier.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,census_tract_number,Census tract identifier.,numeric_binned,"(44.01, 103.0]",2035.0,1481.0,554.0,72.78,27.22,71.08,28.92,1.70
1,census_tract_number,Census tract identifier.,numeric_binned,"(0.999, 25.0]",2006.0,1395.0,611.0,69.54,30.46,71.08,28.92,-1.54
2,census_tract_number,Census tract identifier.,numeric_binned,"(6106.846, 8305.0]",2004.0,1354.0,650.0,67.56,32.44,71.08,28.92,-3.52
3,census_tract_number,Census tract identifier.,numeric_binned,"(331.015, 1861.0]",2002.0,1375.0,627.0,68.68,31.32,71.08,28.92,-2.40
4,census_tract_number,Census tract identifier.,numeric_binned,"(4071.203, 6106.846]",2000.0,1443.0,557.0,72.15,27.85,71.08,28.92,1.07
5,census_tract_number,Census tract identifier.,numeric_binned,"(134.01, 331.015]",1999.0,1373.0,626.0,68.68,31.32,71.08,28.92,-2.40
6,census_tract_number,Census tract identifier.,numeric_binned,"(1861.0, 4071.203]",1998.0,1453.0,545.0,72.72,27.28,71.08,28.92,1.64
7,census_tract_number,Census tract identifier.,numeric_binned,"(25.0, 44.01]",1997.0,1481.0,516.0,74.16,25.84,71.08,28.92,3.08
8,census_tract_number,Census tract identifier.,numeric_binned,"(8305.0, 9718.0]",1996.0,1555.0,441.0,77.91,22.09,71.08,28.92,6.83
9,census_tract_number,Census tract identifier.,numeric_binned,"(103.0, 134.01]",1963.0,1306.0,657.0,66.53,33.47,71.08,28.92,-4.55

========================================================================================================================
Feature: applicant_ethnicity_name
Explanation: Applicant ethnicity label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_ethnicity_name,Applicant ethnicity label.,categorical_limited,Not Hispanic or Latino,14297.0,10285.0,4012.0,71.94,28.06,71.08,28.92,0.86
1,applicant_ethnicity_name,Applicant ethnicity label.,categorical_limited,"Information not provided by applicant in mail,...",3475.0,2467.0,1008.0,70.99,29.01,71.08,28.92,-0.09
2,applicant_ethnicity_name,Applicant ethnicity label.,categorical_limited,Hispanic or Latino,2215.0,1455.0,760.0,65.69,34.31,71.08,28.92,-5.39
3,applicant_ethnicity_name,Applicant ethnicity label.,categorical_limited,Not applicable,13.0,9.0,4.0,69.23,30.77,71.08,28.92,-1.85

========================================================================================================================
Feature: applicant_ethnicity
Explanation: Applicant ethnicity code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_ethnicity,Applicant ethnicity code.,categorical_limited,2,14297.0,10285.0,4012.0,71.94,28.06,71.08,28.92,0.86
1,applicant_ethnicity,Applicant ethnicity code.,categorical_limited,3,3475.0,2467.0,1008.0,70.99,29.01,71.08,28.92,-0.09
2,applicant_ethnicity,Applicant ethnicity code.,categorical_limited,1,2215.0,1455.0,760.0,65.69,34.31,71.08,28.92,-5.39
3,applicant_ethnicity,Applicant ethnicity code.,categorical_limited,4,13.0,9.0,4.0,69.23,30.77,71.08,28.92,-1.85

========================================================================================================================
Feature: co_applicant_ethnicity_name
Explanation: Co-applicant ethnicity label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_ethnicity_name,Co-applicant ethnicity label.,categorical_limited,No co-applicant,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_ethnicity_name,Co-applicant ethnicity label.,categorical_limited,Not Hispanic or Latino,5809.0,4435.0,1374.0,76.35,23.65,71.08,28.92,5.27
2,co_applicant_ethnicity_name,Co-applicant ethnicity label.,categorical_limited,"Information not provided by applicant in mail,...",1644.0,1225.0,419.0,74.51,25.49,71.08,28.92,3.43
3,co_applicant_ethnicity_name,Co-applicant ethnicity label.,categorical_limited,Hispanic or Latino,813.0,566.0,247.0,69.62,30.38,71.08,28.92,-1.46
4,co_applicant_ethnicity_name,Co-applicant ethnicity label.,categorical_limited,Not applicable,15.0,13.0,2.0,86.67,13.33,71.08,28.92,15.59

========================================================================================================================
Feature: co_applicant_ethnicity
Explanation: Co-applicant ethnicity code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_ethnicity,Co-applicant ethnicity code.,categorical_limited,5,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_ethnicity,Co-applicant ethnicity code.,categorical_limited,2,5809.0,4435.0,1374.0,76.35,23.65,71.08,28.92,5.27
2,co_applicant_ethnicity,Co-applicant ethnicity code.,categorical_limited,3,1644.0,1225.0,419.0,74.51,25.49,71.08,28.92,3.43
3,co_applicant_ethnicity,Co-applicant ethnicity code.,categorical_limited,1,813.0,566.0,247.0,69.62,30.38,71.08,28.92,-1.46
4,co_applicant_ethnicity,Co-applicant ethnicity code.,categorical_limited,4,15.0,13.0,2.0,86.67,13.33,71.08,28.92,15.59

========================================================================================================================
Feature: applicant_race_name_1
Explanation: Main applicant race label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_race_name_1,Main applicant race label.,categorical_limited,White,13070.0,9568.0,3502.0,73.21,26.79,71.08,28.92,2.13
1,applicant_race_name_1,Main applicant race label.,categorical_limited,"Information not provided by applicant in mail,...",3709.0,2630.0,1079.0,70.91,29.09,71.08,28.92,-0.17
2,applicant_race_name_1,Main applicant race label.,categorical_limited,Black or African American,1762.0,1022.0,740.0,58.00,42.00,71.08,28.92,-13.08
3,applicant_race_name_1,Main applicant race label.,categorical_limited,Asian,1193.0,826.0,367.0,69.24,30.76,71.08,28.92,-1.84
4,applicant_race_name_1,Main applicant race label.,categorical_limited,American Indian or Alaska Native,163.0,94.0,69.0,57.67,42.33,71.08,28.92,-13.41
5,applicant_race_name_1,Main applicant race label.,categorical_limited,Native Hawaiian or Other Pacific Islander,99.0,73.0,26.0,73.74,26.26,71.08,28.92,2.66
6,applicant_race_name_1,Main applicant race label.,categorical_limited,Not applicable,4.0,3.0,1.0,75.00,25.00,71.08,28.92,3.92

========================================================================================================================
Feature: applicant_race_1
Explanation: Main applicant race code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_race_1,Main applicant race code.,categorical_limited,5,13070.0,9568.0,3502.0,73.21,26.79,71.08,28.92,2.13
1,applicant_race_1,Main applicant race code.,categorical_limited,6,3709.0,2630.0,1079.0,70.91,29.09,71.08,28.92,-0.17
2,applicant_race_1,Main applicant race code.,categorical_limited,3,1762.0,1022.0,740.0,58.00,42.00,71.08,28.92,-13.08
3,applicant_race_1,Main applicant race code.,categorical_limited,2,1193.0,826.0,367.0,69.24,30.76,71.08,28.92,-1.84
4,applicant_race_1,Main applicant race code.,categorical_limited,1,163.0,94.0,69.0,57.67,42.33,71.08,28.92,-13.41
5,applicant_race_1,Main applicant race code.,categorical_limited,4,99.0,73.0,26.0,73.74,26.26,71.08,28.92,2.66
6,applicant_race_1,Main applicant race code.,categorical_limited,7,4.0,3.0,1.0,75.00,25.00,71.08,28.92,3.92

========================================================================================================================
Feature: co_applicant_race_name_1
Explanation: Main co-applicant race label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,No co-applicant,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,White,5477.0,4221.0,1256.0,77.07,22.93,71.08,28.92,5.99
2,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,"Information not provided by applicant in mail,...",1731.0,1296.0,435.0,74.87,25.13,71.08,28.92,3.79
3,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,Asian,508.0,361.0,147.0,71.06,28.94,71.08,28.92,-0.02
4,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,Black or African American,473.0,295.0,178.0,62.37,37.63,71.08,28.92,-8.71
5,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,Native Hawaiian or Other Pacific Islander,43.0,33.0,10.0,76.74,23.26,71.08,28.92,5.66
6,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,American Indian or Alaska Native,40.0,26.0,14.0,65.00,35.00,71.08,28.92,-6.08
7,co_applicant_race_name_1,Main co-applicant race label.,categorical_limited,Not applicable,9.0,7.0,2.0,77.78,22.22,71.08,28.92,6.70

========================================================================================================================
Feature: co_applicant_race_1
Explanation: Main co-applicant race code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_race_1,Main co-applicant race code.,categorical_limited,8,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_race_1,Main co-applicant race code.,categorical_limited,5,5477.0,4221.0,1256.0,77.07,22.93,71.08,28.92,5.99
2,co_applicant_race_1,Main co-applicant race code.,categorical_limited,6,1731.0,1296.0,435.0,74.87,25.13,71.08,28.92,3.79
3,co_applicant_race_1,Main co-applicant race code.,categorical_limited,2,508.0,361.0,147.0,71.06,28.94,71.08,28.92,-0.02
4,co_applicant_race_1,Main co-applicant race code.,categorical_limited,3,473.0,295.0,178.0,62.37,37.63,71.08,28.92,-8.71
5,co_applicant_race_1,Main co-applicant race code.,categorical_limited,4,43.0,33.0,10.0,76.74,23.26,71.08,28.92,5.66
6,co_applicant_race_1,Main co-applicant race code.,categorical_limited,1,40.0,26.0,14.0,65.00,35.00,71.08,28.92,-6.08
7,co_applicant_race_1,Main co-applicant race code.,categorical_limited,7,9.0,7.0,2.0,77.78,22.22,71.08,28.92,6.70

========================================================================================================================
Feature: applicant_sex_name
Explanation: Applicant sex label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_sex_name,Applicant sex label.,categorical_limited,Male,11839.0,8632.0,3207.0,72.91,27.09,71.08,28.92,1.83
1,applicant_sex_name,Applicant sex label.,categorical_limited,Female,5903.0,3989.0,1914.0,67.58,32.42,71.08,28.92,-3.50
2,applicant_sex_name,Applicant sex label.,categorical_limited,"Information not provided by applicant in mail,...",2252.0,1590.0,662.0,70.60,29.40,71.08,28.92,-0.48
3,applicant_sex_name,Applicant sex label.,categorical_limited,Not applicable,6.0,5.0,1.0,83.33,16.67,71.08,28.92,12.25

========================================================================================================================
Feature: applicant_sex
Explanation: Applicant sex code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_sex,Applicant sex code.,categorical_limited,1,11839.0,8632.0,3207.0,72.91,27.09,71.08,28.92,1.83
1,applicant_sex,Applicant sex code.,categorical_limited,2,5903.0,3989.0,1914.0,67.58,32.42,71.08,28.92,-3.50
2,applicant_sex,Applicant sex code.,categorical_limited,3,2252.0,1590.0,662.0,70.60,29.40,71.08,28.92,-0.48
3,applicant_sex,Applicant sex code.,categorical_limited,4,6.0,5.0,1.0,83.33,16.67,71.08,28.92,12.25

========================================================================================================================
Feature: co_applicant_sex_name
Explanation: Co-applicant sex label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_sex_name,Co-applicant sex label.,categorical_limited,No co-applicant,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_sex_name,Co-applicant sex label.,categorical_limited,Female,5503.0,4219.0,1284.0,76.67,23.33,71.08,28.92,5.59
2,co_applicant_sex_name,Co-applicant sex label.,categorical_limited,Male,1697.0,1210.0,487.0,71.30,28.70,71.08,28.92,0.22
3,co_applicant_sex_name,Co-applicant sex label.,categorical_limited,"Information not provided by applicant in mail,...",1074.0,804.0,270.0,74.86,25.14,71.08,28.92,3.78
4,co_applicant_sex_name,Co-applicant sex label.,categorical_limited,Not applicable,7.0,6.0,1.0,85.71,14.29,71.08,28.92,14.63

========================================================================================================================
Feature: co_applicant_sex
Explanation: Co-applicant sex code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,co_applicant_sex,Co-applicant sex code.,categorical_limited,5,11719.0,7977.0,3742.0,68.07,31.93,71.08,28.92,-3.01
1,co_applicant_sex,Co-applicant sex code.,categorical_limited,2,5503.0,4219.0,1284.0,76.67,23.33,71.08,28.92,5.59
2,co_applicant_sex,Co-applicant sex code.,categorical_limited,1,1697.0,1210.0,487.0,71.30,28.70,71.08,28.92,0.22
3,co_applicant_sex,Co-applicant sex code.,categorical_limited,3,1074.0,804.0,270.0,74.86,25.14,71.08,28.92,3.78
4,co_applicant_sex,Co-applicant sex code.,categorical_limited,4,7.0,6.0,1.0,85.71,14.29,71.08,28.92,14.63

========================================================================================================================
Feature: applicant_income_000s
Explanation: Applicant annual income in thousands of dollars.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(66.0, 79.0]",2063.0,1505.0,558.0,72.95,27.05,71.08,28.92,1.87
1,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(0.999, 34.0]",2060.0,963.0,1097.0,46.75,53.25,71.08,28.92,-24.33
2,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(93.0, 112.0]",2056.0,1578.0,478.0,76.75,23.25,71.08,28.92,5.67
3,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(55.0, 66.0]",2037.0,1467.0,570.0,72.02,27.98,71.08,28.92,0.94
4,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(193.0, 7608.0]",1988.0,1594.0,394.0,80.18,19.82,71.08,28.92,9.10
5,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(45.0, 55.0]",1987.0,1346.0,641.0,67.74,32.26,71.08,28.92,-3.34
6,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(139.0, 193.0]",1972.0,1577.0,395.0,79.97,20.03,71.08,28.92,8.89
7,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(112.0, 139.0]",1970.0,1537.0,433.0,78.02,21.98,71.08,28.92,6.94
8,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(34.0, 45.0]",1968.0,1219.0,749.0,61.94,38.06,71.08,28.92,-9.14
9,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(79.0, 93.0]",1899.0,1430.0,469.0,75.30,24.70,71.08,28.92,4.22

========================================================================================================================
Feature: purchaser_type_name
Explanation: No manual explanation provided for this feature.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Loan was not originated or was not sold in cal...,10210.0,4426.0,5784.0,43.35,56.65,71.08,28.92,-27.73
1,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Fannie Mae (FNMA),2611.0,2611.0,0.0,100.00,0.00,71.08,28.92,28.92
2,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Freddie Mac (FHLMC),1738.0,1738.0,0.0,100.00,0.00,71.08,28.92,28.92
3,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Ginnie Mae (GNMA),1623.0,1623.0,0.0,100.00,0.00,71.08,28.92,28.92
4,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,"Life insurance company, credit union, mortgage...",1562.0,1562.0,0.0,100.00,0.00,71.08,28.92,28.92
5,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,"Commercial bank, savings bank or savings assoc...",1323.0,1323.0,0.0,100.00,0.00,71.08,28.92,28.92
6,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Other type of purchaser,659.0,659.0,0.0,100.00,0.00,71.08,28.92,28.92
7,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Affiliate institution,209.0,209.0,0.0,100.00,0.00,71.08,28.92,28.92
8,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Private securitization,65.0,65.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: purchaser_type
Explanation: No manual explanation provided for this feature.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,purchaser_type,No manual explanation provided for this feature.,categorical_limited,0,10210.0,4426.0,5784.0,43.35,56.65,71.08,28.92,-27.73
1,purchaser_type,No manual explanation provided for this feature.,categorical_limited,1,2611.0,2611.0,0.0,100.00,0.00,71.08,28.92,28.92
2,purchaser_type,No manual explanation provided for this feature.,categorical_limited,3,1738.0,1738.0,0.0,100.00,0.00,71.08,28.92,28.92
3,purchaser_type,No manual explanation provided for this feature.,categorical_limited,2,1623.0,1623.0,0.0,100.00,0.00,71.08,28.92,28.92
4,purchaser_type,No manual explanation provided for this feature.,categorical_limited,7,1562.0,1562.0,0.0,100.00,0.00,71.08,28.92,28.92
5,purchaser_type,No manual explanation provided for this feature.,categorical_limited,6,1323.0,1323.0,0.0,100.00,0.00,71.08,28.92,28.92
6,purchaser_type,No manual explanation provided for this feature.,categorical_limited,9,659.0,659.0,0.0,100.00,0.00,71.08,28.92,28.92
7,purchaser_type,No manual explanation provided for this feature.,categorical_limited,8,209.0,209.0,0.0,100.00,0.00,71.08,28.92,28.92
8,purchaser_type,No manual explanation provided for this feature.,categorical_limited,5,65.0,65.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: hoepa_status_name
Explanation: Whether the loan is a HOEPA high-cost loan.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,hoepa_status_name,Whether the loan is a HOEPA high-cost loan.,categorical_limited,Not a HOEPA loan,19994.0,14210.0,5784.0,71.07,28.93,71.08,28.92,-0.01
1,hoepa_status_name,Whether the loan is a HOEPA high-cost loan.,categorical_limited,HOEPA loan,6.0,6.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: hoepa_status
Explanation: HOEPA status code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,hoepa_status,HOEPA status code.,categorical_limited,2,19994.0,14210.0,5784.0,71.07,28.93,71.08,28.92,-0.01
1,hoepa_status,HOEPA status code.,categorical_limited,1,6.0,6.0,0.0,100.00,0.00,71.08,28.92,28.92

========================================================================================================================
Feature: lien_status_name
Explanation: Lien status label.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,lien_status_name,Lien status label.,categorical_limited,Secured by a first lien,18245.0,13330.0,4915.0,73.06,26.94,71.08,28.92,1.98
1,lien_status_name,Lien status label.,categorical_limited,Not secured by a lien,924.0,372.0,552.0,40.26,59.74,71.08,28.92,-30.82
2,lien_status_name,Lien status label.,categorical_limited,Secured by a subordinate lien,831.0,514.0,317.0,61.85,38.15,71.08,28.92,-9.23

========================================================================================================================
Feature: lien_status
Explanation: Lien status code.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,lien_status,Lien status code.,categorical_limited,1,18245.0,13330.0,4915.0,73.06,26.94,71.08,28.92,1.98
1,lien_status,Lien status code.,categorical_limited,3,924.0,372.0,552.0,40.26,59.74,71.08,28.92,-30.82
2,lien_status,Lien status code.,categorical_limited,2,831.0,514.0,317.0,61.85,38.15,71.08,28.92,-9.23

========================================================================================================================
Feature: population
Explanation: Population of the census tract.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,population,Population of the census tract.,numeric_binned,"(2909.9, 3618.0]",2006.0,1430.0,576.0,71.29,28.71,71.08,28.92,0.21
1,population,Population of the census tract.,numeric_binned,"(4190.7, 4715.0]",2005.0,1404.0,601.0,70.02,29.98,71.08,28.92,-1.06
2,population,Population of the census tract.,numeric_binned,"(7511.2, 9838.0]",2005.0,1435.0,570.0,71.57,28.43,71.08,28.92,0.49
3,population,Population of the census tract.,numeric_binned,"(5860.0, 6620.0]",2001.0,1441.0,560.0,72.01,27.99,71.08,28.92,0.93
4,population,Population of the census tract.,numeric_binned,"(92.999, 2909.9]",2000.0,1326.0,674.0,66.30,33.70,71.08,28.92,-4.78
5,population,Population of the census tract.,numeric_binned,"(4715.0, 5242.0]",2000.0,1420.0,580.0,71.00,29.00,71.08,28.92,-0.08
6,population,Population of the census tract.,numeric_binned,"(6620.0, 7511.2]",1998.0,1436.0,562.0,71.87,28.13,71.08,28.92,0.79
7,population,Population of the census tract.,numeric_binned,"(5242.0, 5860.0]",1996.0,1407.0,589.0,70.49,29.51,71.08,28.92,-0.59
8,population,Population of the census tract.,numeric_binned,"(9838.0, 53812.0]",1995.0,1539.0,456.0,77.14,22.86,71.08,28.92,6.06
9,population,Population of the census tract.,numeric_binned,"(3618.0, 4190.7]",1994.0,1378.0,616.0,69.11,30.89,71.08,28.92,-1.97

========================================================================================================================
Feature: minority_population
Explanation: Minority population percentage in the census tract.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,minority_population,Minority population percentage in the census t...,numeric_binned,"(27.08, 34.96]",2023.0,1478.0,545.0,73.06,26.94,71.08,28.92,1.98
1,minority_population,Minority population percentage in the census t...,numeric_binned,"(15.054, 20.35]",2004.0,1492.0,512.0,74.45,25.55,71.08,28.92,3.37
2,minority_population,Minority population percentage in the census t...,numeric_binned,"(20.35, 27.08]",2002.0,1487.0,515.0,74.28,25.72,71.08,28.92,3.20
3,minority_population,Minority population percentage in the census t...,numeric_binned,"(-0.001, 6.22]",2002.0,1424.0,578.0,71.13,28.87,71.08,28.92,0.05
4,minority_population,Minority population percentage in the census t...,numeric_binned,"(6.22, 10.22]",2002.0,1536.0,466.0,76.72,23.28,71.08,28.92,5.64
5,minority_population,Minority population percentage in the census t...,numeric_binned,"(58.112, 76.78]",2001.0,1324.0,677.0,66.17,33.83,71.08,28.92,-4.91
6,minority_population,Minority population percentage in the census t...,numeric_binned,"(44.876, 58.112]",2000.0,1387.0,613.0,69.35,30.65,71.08,28.92,-1.73
7,minority_population,Minority population percentage in the census t...,numeric_binned,"(76.78, 100.0]",1999.0,1175.0,824.0,58.78,41.22,71.08,28.92,-12.30
8,minority_population,Minority population percentage in the census t...,numeric_binned,"(10.22, 15.054]",1996.0,1488.0,508.0,74.55,25.45,71.08,28.92,3.47
9,minority_population,Minority population percentage in the census t...,numeric_binned,"(34.96, 44.876]",1971.0,1425.0,546.0,72.30,27.70,71.08,28.92,1.22

========================================================================================================================
Feature: hud_median_family_income
Explanation: Median family income in the area.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,hud_median_family_income,Median family income in the area.,numeric_binned,"(72000.0, 73700.0]",2371.0,1680.0,691.0,70.86,29.14,71.08,28.92,-0.22
1,hud_median_family_income,Median family income in the area.,numeric_binned,"(60200.0, 63200.0]",2249.0,1554.0,695.0,69.10,30.90,71.08,28.92,-1.98
2,hud_median_family_income,Median family income in the area.,numeric_binned,"(77500.0, 79600.0]",2051.0,1477.0,574.0,72.01,27.99,71.08,28.92,0.93
3,hud_median_family_income,Median family income in the area.,numeric_binned,"(17999.999, 53500.0]",2048.0,1345.0,703.0,65.67,34.33,71.08,28.92,-5.41
4,hud_median_family_income,Median family income in the area.,numeric_binned,"(73700.0, 77500.0]",2030.0,1418.0,612.0,69.85,30.15,71.08,28.92,-1.23
5,hud_median_family_income,Median family income in the area.,numeric_binned,"(63200.0, 67700.0]",2019.0,1482.0,537.0,73.40,26.60,71.08,28.92,2.32
6,hud_median_family_income,Median family income in the area.,numeric_binned,"(84900.0, 111200.0]",1999.0,1433.0,566.0,71.69,28.31,71.08,28.92,0.61
7,hud_median_family_income,Median family income in the area.,numeric_binned,"(53500.0, 60200.0]",1960.0,1378.0,582.0,70.31,29.69,71.08,28.92,-0.77
8,hud_median_family_income,Median family income in the area.,numeric_binned,"(67700.0, 72000.0]",1747.0,1259.0,488.0,72.07,27.93,71.08,28.92,0.99
9,hud_median_family_income,Median family income in the area.,numeric_binned,"(79600.0, 84900.0]",1526.0,1190.0,336.0,77.98,22.02,71.08,28.92,6.90

========================================================================================================================
Feature: tract_to_msamd_income
Explanation: Tract income as a percentage of MSA/MD income.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(101.71, 111.05]",2008.0,1446.0,562.0,72.01,27.99,71.08,28.92,0.93
1,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(82.62, 93.19]",2007.0,1358.0,649.0,67.66,32.34,71.08,28.92,-3.42
2,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(145.904, 172.23]",2004.0,1547.0,457.0,77.20,22.80,71.08,28.92,6.12
3,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(-0.001, 69.21]",2002.0,1154.0,848.0,57.64,42.36,71.08,28.92,-13.44
4,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(131.39, 145.904]",1999.0,1532.0,467.0,76.64,23.36,71.08,28.92,5.56
5,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(111.05, 120.31]",1999.0,1456.0,543.0,72.84,27.16,71.08,28.92,1.76
6,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(69.21, 82.62]",1999.0,1304.0,695.0,65.23,34.77,71.08,28.92,-5.85
7,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(172.23, 390.37]",1996.0,1591.0,405.0,79.71,20.29,71.08,28.92,8.63
8,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(120.31, 131.39]",1993.0,1472.0,521.0,73.86,26.14,71.08,28.92,2.78
9,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(93.19, 101.71]",1993.0,1356.0,637.0,68.04,31.96,71.08,28.92,-3.04

========================================================================================================================
Feature: number_of_owner_occupied_units
Explanation: Number of owner-occupied housing units in the census tract.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(2058.0, 2651.0]",2019.0,1469.0,550.0,72.76,27.24,71.08,28.92,1.68
1,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(1025.0, 1203.0]",2013.0,1423.0,590.0,70.69,29.31,71.08,28.92,-0.39
2,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(628.9, 853.0]",2010.0,1367.0,643.0,68.01,31.99,71.08,28.92,-3.07
3,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(1203.0, 1358.0]",2008.0,1422.0,586.0,70.82,29.18,71.08,28.92,-0.26
4,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(7.999, 628.9]",2000.0,1258.0,742.0,62.90,37.10,71.08,28.92,-8.18
5,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(853.0, 1025.0]",1997.0,1378.0,619.0,69.00,31.00,71.08,28.92,-2.08
6,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(1536.0, 1754.0]",1996.0,1454.0,542.0,72.85,27.15,71.08,28.92,1.77
7,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(1358.0, 1536.0]",1991.0,1451.0,540.0,72.88,27.12,71.08,28.92,1.80
8,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(1754.0, 2058.0]",1986.0,1440.0,546.0,72.51,27.49,71.08,28.92,1.43
9,number_of_owner_occupied_units,Number of owner-occupied housing units in the ...,numeric_binned,"(2651.0, 13975.0]",1980.0,1554.0,426.0,78.48,21.52,71.08,28.92,7.40

========================================================================================================================
Feature: number_of_1_to_4_family_units
Explanation: Number of 1-to-4 family housing units in the census tract.

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(956.0, 1214.0]",2025.0,1414.0,611.0,69.83,30.17,71.08,28.92,-1.25
1,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(1828.0, 2043.0]",2005.0,1416.0,589.0,70.62,29.38,71.08,28.92,-0.46
2,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(1428.0, 1627.0]",2003.0,1422.0,581.0,70.99,29.01,71.08,28.92,-0.09
3,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(2321.0, 2683.0]",2002.0,1387.0,615.0,69.28,30.72,71.08,28.92,-1.80
4,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(19.999, 956.0]",2001.0,1341.0,660.0,67.02,32.98,71.08,28.92,-4.06
5,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(3418.0, 15386.0]",1999.0,1555.0,444.0,77.79,22.21,71.08,28.92,6.71
6,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(2043.0, 2321.0]",1997.0,1445.0,552.0,72.36,27.64,71.08,28.92,1.28
7,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(2683.0, 3418.0]",1996.0,1419.0,577.0,71.09,28.91,71.08,28.92,0.01
8,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(1627.0, 1828.0]",1994.0,1422.0,572.0,71.31,28.69,71.08,28.92,0.23
9,number_of_1_to_4_family_units,Number of 1-to-4 family housing units in the c...,numeric_binned,"(1214.0, 1428.0]",1978.0,1395.0,583.0,70.53,29.47,71.08,28.92,-0.55

========================================================================================================================
Combined in-memory table shape: (343, 12)

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall
0,as_of_year,Report year. Usually constant in this dataset.,categorical_limited,2017,20000.0,14216.0,5784.0,71.08,28.92,71.08,28.92,0.00
1,respondent_id,Financial institution / lender identifier.,categorical_limited,Other,13893.0,10358.0,3535.0,74.56,25.44,71.08,28.92,3.48
2,respondent_id,Financial institution / lender identifier.,categorical_limited,7197000003,1603.0,1016.0,587.0,63.38,36.62,71.08,28.92,-7.70
3,respondent_id,Financial institution / lender identifier.,categorical_limited,0000451965,902.0,542.0,360.0,60.09,39.91,71.08,28.92,-10.99
4,respondent_id,Financial institution / lender identifier.,categorical_limited,26-4599244,481.0,329.0,152.0,68.40,31.60,71.08,28.92,-2.68
5,respondent_id,Financial institution / lender identifier.,categorical_limited,0000852218,417.0,318.0,99.0,76.26,23.74,71.08,28.92,5.18
6,respondent_id,Financial institution / lender identifier.,categorical_limited,0000504713,325.0,154.0,171.0,47.38,52.62,71.08,28.92,-23.70
7,respondent_id,Financial institution / lender identifier.,categorical_limited,0000617677,320.0,211.0,109.0,65.94,34.06,71.08,28.92,-5.14
8,respondent_id,Financial institution / lender identifier.,categorical_limited,38-2750395,281.0,239.0,42.0,85.05,14.95,71.08,28.92,13.97
9,respondent_id,Financial institution / lender identifier.,categorical_limited,0000480228,275.0,206.0,69.0,74.91,25.09,71.08,28.92,3.83
10,respondent_id,Financial institution / lender identifier.,categorical_limited,13-6131491,260.0,206.0,54.0,79.23,20.77,71.08,28.92,8.15
11,respondent_id,Financial institution / lender identifier.,categorical_limited,0000146672,234.0,172.0,62.0,73.50,26.50,71.08,28.92,2.42
12,respondent_id,Financial institution / lender identifier.,categorical_limited,0000817824,234.0,121.0,113.0,51.71,48.29,71.08,28.92,-19.37
13,respondent_id,Financial institution / lender identifier.,categorical_limited,0000675332,208.0,53.0,155.0,25.48,74.52,71.08,28.92,-45.60
14,respondent_id,Financial institution / lender identifier.,categorical_limited,75-2921540,196.0,73.0,123.0,37.24,62.76,71.08,28.92,-33.84
15,respondent_id,Financial institution / lender identifier.,categorical_limited,41-1795868,188.0,106.0,82.0,56.38,43.62,71.08,28.92,-14.70
16,respondent_id,Financial institution / lender identifier.,categorical_limited,0000012311,183.0,112.0,71.0,61.20,38.80,71.08,28.92,-9.88
17,agency_name,Name of the supervising agency.,categorical_limited,Department of Housing and Urban Development,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
18,agency_name,Name of the supervising agency.,categorical_limited,Consumer Financial Protection Bureau,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
19,agency_name,Name of the supervising agency.,categorical_limited,National Credit Union Administration,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
20,agency_name,Name of the supervising agency.,categorical_limited,Federal Deposit Insurance Corporation,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
21,agency_name,Name of the supervising agency.,categorical_limited,Office of the Comptroller of the Currency,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
22,agency_name,Name of the supervising agency.,categorical_limited,Federal Reserve System,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07
23,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,HUD,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
24,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,CFPB,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
25,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,NCUA,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
26,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,FDIC,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
27,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,OCC,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
28,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,FRS,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07
29,agency_code,Code of the supervising agency.,categorical_limited,7,10425.0,7610.0,2815.0,73.00,27.00,71.08,28.92,1.92
30,agency_code,Code of the supervising agency.,categorical_limited,9,5348.0,3327.0,2021.0,62.21,37.79,71.08,28.92,-8.87
31,agency_code,Code of the supervising agency.,categorical_limited,5,1729.0,1270.0,459.0,73.45,26.55,71.08,28.92,2.37
32,agency_code,Code of the supervising agency.,categorical_limited,3,1334.0,1085.0,249.0,81.33,18.67,71.08,28.92,10.25
33,agency_code,Code of the supervising agency.,categorical_limited,1,666.0,485.0,181.0,72.82,27.18,71.08,28.92,1.74
34,agency_code,Code of the supervising agency.,categorical_limited,2,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07
35,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,Conventional,14807.0,10532.0,4275.0,71.13,28.87,71.08,28.92,0.05
36,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,FHA-insured,3319.0,2339.0,980.0,70.47,29.53,71.08,28.92,-0.61
37,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,VA-guaranteed,1659.0,1182.0,477.0,71.25,28.75,71.08,28.92,0.17
38,loan_type_name,"Loan type label, such as Conventional, FHA, VA...",categorical_limited,FSA/RHS-guaranteed,215.0,163.0,52.0,75.81,24.19,71.08,28.92,4.73
39,loan_type,Loan type code.,categorical_limited,1,14807.0,10532.0,4275.0,71.13,28.87,71.08,28.92,0.05
40,loan_type,Loan type code.,categorical_limited,2,3319.0,2339.0,980.0,70.47,29.53,71.08,28.92,-0.61
41,loan_type,Loan type code.,categorical_limited,3,1659.0,1182.0,477.0,71.25,28.75,71.08,28.92,0.17
42,loan_type,Loan type code.,categorical_limited,4,215.0,163.0,52.0,75.81,24.19,71.08,28.92,4.73
43,property_type_name,Property type label.,categorical_limited,One-to-four family dwelling (other than manufa...,19350.0,13947.0,5403.0,72.08,27.92,71.08,28.92,1.00
44,property_type_name,Property type label.,categorical_limited,Manufactured housing,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.70
45,property_type,Property type code.,categorical_limited,1,19350.0,13947.0,5403.0,72.08,27.92,71.08,28.92,1.00
46,property_type,Property type code.,categorical_limited,2,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.70
47,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Home purchase,10462.0,8521.0,1941.0,81.45,18.55,71.08,28.92,10.37
48,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Refinancing,7499.0,4670.0,2829.0,62.27,37.73,71.08,28.92,-8.81
49,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Home improvement,2039.0,1025.0,1014.0,50.27,49.73,71.08,28.92,-20.81

========================================================================================================================
Feature groups with strongest difference from overall approval rate:

loan_approved,feature,feature_explanation,feature_type,feature_group,total_count,approved_count,rejected_count,approved_percent,rejected_percent,overall_approved_percent,overall_rejected_percent,approved_percent_minus_overall,abs_difference
0,respondent_id,Financial institution / lender identifier.,categorical_limited,0000675332,208.0,53.0,155.0,25.48,74.52,71.08,28.92,-45.60,45.60
1,respondent_id,Financial institution / lender identifier.,categorical_limited,75-2921540,196.0,73.0,123.0,37.24,62.76,71.08,28.92,-33.84,33.84
2,lien_status_name,Lien status label.,categorical_limited,Not secured by a lien,924.0,372.0,552.0,40.26,59.74,71.08,28.92,-30.82,30.82
3,lien_status,Lien status code.,categorical_limited,3,924.0,372.0,552.0,40.26,59.74,71.08,28.92,-30.82,30.82
4,property_type,Property type code.,categorical_limited,2,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.70,29.70
5,property_type_name,Property type label.,categorical_limited,Manufactured housing,650.0,269.0,381.0,41.38,58.62,71.08,28.92,-29.70,29.70
6,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Freddie Mac (FHLMC),1738.0,1738.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
7,purchaser_type,No manual explanation provided for this feature.,categorical_limited,6,1323.0,1323.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
8,purchaser_type,No manual explanation provided for this feature.,categorical_limited,9,659.0,659.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
9,purchaser_type,No manual explanation provided for this feature.,categorical_limited,8,209.0,209.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
10,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Ginnie Mae (GNMA),1623.0,1623.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
11,purchaser_type,No manual explanation provided for this feature.,categorical_limited,2,1623.0,1623.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
12,purchaser_type,No manual explanation provided for this feature.,categorical_limited,7,1562.0,1562.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
13,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Affiliate institution,209.0,209.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
14,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Private securitization,65.0,65.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
15,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,"Life insurance company, credit union, mortgage...",1562.0,1562.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
16,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,"Commercial bank, savings bank or savings assoc...",1323.0,1323.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
17,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Other type of purchaser,659.0,659.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
18,purchaser_type,No manual explanation provided for this feature.,categorical_limited,5,65.0,65.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
19,purchaser_type,No manual explanation provided for this feature.,categorical_limited,3,1738.0,1738.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
20,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Fannie Mae (FNMA),2611.0,2611.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
21,purchaser_type,No manual explanation provided for this feature.,categorical_limited,1,2611.0,2611.0,0.0,100.00,0.00,71.08,28.92,28.92,28.92
22,county_name,County name.,categorical_limited,Cook County,588.0,248.0,340.0,42.18,57.82,71.08,28.92,-28.90,28.90
23,purchaser_type_name,No manual explanation provided for this feature.,categorical_limited,Loan was not originated or was not sold in cal...,10210.0,4426.0,5784.0,43.35,56.65,71.08,28.92,-27.73,27.73
24,purchaser_type,No manual explanation provided for this feature.,categorical_limited,0,10210.0,4426.0,5784.0,43.35,56.65,71.08,28.92,-27.73,27.73
25,applicant_income_000s,Applicant annual income in thousands of dollars.,numeric_binned,"(0.999, 34.0]",2060.0,963.0,1097.0,46.75,53.25,71.08,28.92,-24.33,24.33
26,respondent_id,Financial institution / lender identifier.,categorical_limited,0000504713,325.0,154.0,171.0,47.38,52.62,71.08,28.92,-23.70,23.70
27,loan_amount_000s,Loan amount in thousands of dollars.,numeric_binned,"(0.999, 48.0]",2016.0,991.0,1025.0,49.16,50.84,71.08,28.92,-21.92,21.92
28,loan_purpose_name,"Loan purpose label: home purchase, refinancing...",categorical_limited,Home improvement,2039.0,1025.0,1014.0,50.27,49.73,71.08,28.92,-20.81,20.81
29,loan_purpose,Loan purpose code.,categorical_limited,2,2039.0,1025.0,1014.0,50.27,49.73,71.08,28.92,-20.81,20.81
30,respondent_id,Financial institution / lender identifier.,categorical_limited,0000817824,234.0,121.0,113.0,51.71,48.29,71.08,28.92,-19.37,19.37
31,county_name,County name.,categorical_limited,San Bernardino County,465.0,245.0,220.0,52.69,47.31,71.08,28.92,-18.39,18.39
32,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"Riverside, San Bernardino, Ontario - CA",466.0,246.0,220.0,52.79,47.21,71.08,28.92,-18.29,18.29
33,agency_abbr,Abbreviation of the supervising agency.,categorical_limited,FRS,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07,17.07
34,agency_name,Name of the supervising agency.,categorical_limited,Federal Reserve System,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07,17.07
35,agency_code,Code of the supervising agency.,categorical_limited,2,498.0,439.0,59.0,88.15,11.85,71.08,28.92,17.07,17.07
36,county_name,County name.,categorical_limited,DuPage County,886.0,765.0,121.0,86.34,13.66,71.08,28.92,15.26,15.26
37,preapproval_name,Preapproval status label.,categorical_limited,Preapproval was requested,571.0,490.0,81.0,85.81,14.19,71.08,28.92,14.73,14.73
38,preapproval,Preapproval status code.,categorical_limited,1,571.0,490.0,81.0,85.81,14.19,71.08,28.92,14.73,14.73
39,respondent_id,Financial institution / lender identifier.,categorical_limited,41-1795868,188.0,106.0,82.0,56.38,43.62,71.08,28.92,-14.70,14.70
40,msamd_name,Metropolitan statistical area / division name.,categorical_limited,"New York, Jersey City, White Plains - NY, NJ",727.0,413.0,314.0,56.81,43.19,71.08,28.92,-14.27,14.27
41,respondent_id,Financial institution / lender identifier.,categorical_limited,38-2750395,281.0,239.0,42.0,85.05,14.95,71.08,28.92,13.97,13.97
42,tract_to_msamd_income,Tract income as a percentage of MSA/MD income.,numeric_binned,"(-0.001, 69.21]",2002.0,1154.0,848.0,57.64,42.36,71.08,28.92,-13.44,13.44
43,applicant_race_name_1,Main applicant race label.,categorical_limited,American Indian or Alaska Native,163.0,94.0,69.0,57.67,42.33,71.08,28.92,-13.41,13.41
44,applicant_race_1,Main applicant race code.,categorical_limited,1,163.0,94.0,69.0,57.67,42.33,71.08,28.92,-13.41,13.41
45,applicant_race_name_1,Main applicant race label.,categorical_limited,Black or African American,1762.0,1022.0,740.0,58.00,42.00,71.08,28.92,-13.08,13.08
46,applicant_race_1,Main applicant race code.,categorical_limited,3,1762.0,1022.0,740.0,58.00,42.00,71.08,28.92,-13.08,13.08
47,minority_population,Minority population percentage in the census t...,numeric_binned,"(76.78, 100.0]",1999.0,1175.0,824.0,58.78,41.22,71.08,28.92,-12.30,12.30
48,preapproval_name,Preapproval status label.,categorical_limited,Preapproval was not requested,3772.0,3114.0,658.0,82.56,17.44,71.08,28.92,11.48,11.48
49,preapproval,Preapproval status code.,categorical_limited,2,3772.0,3114.0,658.0,82.56,17.44,71.08,28.92,11.48,11.48

## Step 12: Create the Final Modeling Dataset

This step removes columns that are redundant, coded duplicates, post-decision fields, or not needed for modeling. It keeps clear label columns, useful numeric columns, location information, and the final target column. The output file is `hmda_2017_ready.csv`, with 29 columns and 8,064,813 rows.

In [11]:
import pandas as pd
from pathlib import Path

# =========================================================
# 0. File paths and settings
# =========================================================

DATA_PATH = Path("hmda_2017_classification_ready_cleaned_invalid_removed.csv")
OUTPUT_PATH = Path("hmda_2017_ready.csv")

CHUNK_SIZE = 200_000

# =========================================================
# 1. Columns to drop
# =========================================================

columns_to_drop = [
    "agency_abbr",
    "agency_code",
    "loan_type",
    "property_type",
    "loan_purpose",
    "owner_occupancy",
    "preapproval",
    "msamd",
    "state_abbr",
    "applicant_ethnicity",
    "co_applicant_ethnicity",
    "applicant_race_1",
    "co_applicant_race_1",
    "applicant_sex",
    "co_applicant_sex",
    "purchaser_type_name",
    "purchaser_type",
    "hoepa_status_name",
    "hoepa_status",
    "lien_status",
    "action_taken",
    "action_taken_name",
    "as_of_year"
]

# =========================================================
# 2. Check which columns exist
# =========================================================

header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

existing_columns_to_drop = [
    col for col in columns_to_drop
    if col in header_df.columns
]

missing_columns_to_drop = [
    col for col in columns_to_drop
    if col not in header_df.columns
]

print("Original column count:", len(header_df.columns))
print("Columns found and will be dropped:", len(existing_columns_to_drop))
print("Expected final column count:", len(header_df.columns) - len(existing_columns_to_drop))

print("\nColumns that will be dropped:")
for col in existing_columns_to_drop:
    print("-", col)

if missing_columns_to_drop:
    print("\nColumns not found in dataset:")
    for col in missing_columns_to_drop:
        print("-", col)

# =========================================================
# 3. Process file chunk by chunk
# =========================================================

first_chunk = True
total_rows_processed = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    rows_before = len(chunk)
    total_rows_processed += rows_before

    # Drop only columns that exist in this chunk
    drop_cols_in_chunk = [
        col for col in existing_columns_to_drop
        if col in chunk.columns
    ]

    chunk = chunk.drop(columns=drop_cols_in_chunk)

    # Write chunk to output file
    chunk.to_csv(
        OUTPUT_PATH,
        index=False,
        mode="w" if first_chunk else "a",
        header=first_chunk
    )

    first_chunk = False

    print(
        f"Chunk {chunk_id} | "
        f"Rows processed: {total_rows_processed:,} | "
        f"Current column count: {chunk.shape[1]}"
    )

print("\nDone.")
print("Output saved to:", OUTPUT_PATH.resolve())
print("Total rows processed:", f"{total_rows_processed:,}")

# =========================================================
# 4. Final column count check
# =========================================================

output_header_df = pd.read_csv(
    OUTPUT_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

print("\nFinal check:")
print("Output column count:", len(output_header_df.columns))
print("Output columns:")
print(output_header_df.columns.tolist())

Original column count: 49
Columns found and will be dropped: 20
Expected final column count: 29

Columns that will be dropped:
- agency_abbr
- agency_code
- loan_type
- property_type
- loan_purpose
- owner_occupancy
- preapproval
- msamd
- state_abbr
- applicant_ethnicity
- co_applicant_ethnicity
- applicant_race_1
- co_applicant_race_1
- applicant_sex
- co_applicant_sex
- hoepa_status_name
- hoepa_status
- lien_status
- action_taken
- as_of_year

Columns not found in dataset:
- purchaser_type_name
- purchaser_type
- action_taken_name
Chunk 1 | Rows processed: 200,000 | Current column count: 29
Chunk 2 | Rows processed: 400,000 | Current column count: 29
Chunk 3 | Rows processed: 600,000 | Current column count: 29
Chunk 4 | Rows processed: 800,000 | Current column count: 29
Chunk 5 | Rows processed: 1,000,000 | Current column count: 29
Chunk 6 | Rows processed: 1,200,000 | Current column count: 29
Chunk 7 | Rows processed: 1,400,000 | Current column count: 29
Chunk 8 | Rows processed: 1,600,000 | Current column count: 29
Chunk 9 | Rows processed: 1,800,000 | Current column count: 29
Chunk 10 | Rows processed: 2,000,000 | Current column count: 29
Chunk 11 | Rows processed: 2,200,000 | Current column count: 29
Chunk 12 | Rows processed: 2,400,000 | Current column count: 29
Chunk 13 | Rows processed: 2,600,000 | Current column count: 29
Chunk 14 | Rows processed: 2,800,000 | Current column count: 29
Chunk 15 | Rows processed: 3,000,000 | Current column count: 29
Chunk 16 | Rows processed: 3,200,000 | Current column count: 29
Chunk 17 | Rows processed: 3,400,000 | Current column count: 29
Chunk 18 | Rows processed: 3,600,000 | Current column count: 29
Chunk 19 | Rows processed: 3,800,000 | Current column count: 29
Chunk 20 | Rows processed: 4,000,000 | Current column count: 29
Chunk 21 | Rows processed: 4,200,000 | Current column count: 29
Chunk 22 | Rows processed: 4,400,000 | Current column count: 29
Chunk 23 | Rows processed: 4,600,000 | Current column count: 29
Chunk 24 | Rows processed: 4,800,000 | Current column count: 29
Chunk 25 | Rows processed: 5,000,000 | Current column count: 29
Chunk 26 | Rows processed: 5,200,000 | Current column count: 29
Chunk 27 | Rows processed: 5,400,000 | Current column count: 29
Chunk 28 | Rows processed: 5,600,000 | Current column count: 29
Chunk 29 | Rows processed: 5,800,000 | Current column count: 29
Chunk 30 | Rows processed: 6,000,000 | Current column count: 29
Chunk 31 | Rows processed: 6,200,000 | Current column count: 29
Chunk 32 | Rows processed: 6,400,000 | Current column count: 29
Chunk 33 | Rows processed: 6,600,000 | Current column count: 29
Chunk 34 | Rows processed: 6,800,000 | Current column count: 29
Chunk 35 | Rows processed: 7,000,000 | Current column count: 29
Chunk 36 | Rows processed: 7,200,000 | Current column count: 29
Chunk 37 | Rows processed: 7,400,000 | Current column count: 29
Chunk 38 | Rows processed: 7,600,000 | Current column count: 29
Chunk 39 | Rows processed: 7,800,000 | Current column count: 29
Chunk 40 | Rows processed: 8,000,000 | Current column count: 29
Chunk 41 | Rows processed: 8,064,813 | Current column count: 29

Done.
Output saved to: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_2017_ready.csv
Total rows processed: 8,064,813

Final check:
Output column count: 29
Output columns:
['respondent_id', 'agency_name', 'loan_type_name', 'property_type_name', 'loan_purpose_name', 'owner_occupancy_name', 'loan_amount_000s', 'preapproval_name', 'msamd_name', 'state_name', 'state_code', 'county_name', 'county_code', 'census_tract_number', 'applicant_ethnicity_name', 'co_applicant_ethnicity_name', 'applicant_race_name_1', 'co_applicant_race_name_1', 'applicant_sex_name', 'co_applicant_sex_name', 'applicant_income_000s', 'lien_status_name', 'population', 'minority_population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units', 'loan_approved']

## Step 13: Check Numeric Columns in the Final Dataset

This step creates the final numeric summary for `hmda_2017_ready.csv`. It checks the same main numeric columns after final column selection. This is a final quality check before sampling and model building.

In [12]:
import pandas as pd
from pathlib import Path

# Input file
DATA_PATH = Path("hmda_2017_ready.csv")

CHUNK_SIZE = 200_000

# Continuous / semi-continuous numeric columns
continuous_numeric_cols = [
    "loan_amount_000s",
    "applicant_income_000s",
    "population",
    "minority_population",
    "hud_median_family_income",
    "tract_to_msamd_income",
    "number_of_owner_occupied_units",
    "number_of_1_to_4_family_units"
]

# --------------------------------------------------
# 1. Check which columns exist in the file
# --------------------------------------------------
header_df = pd.read_csv(
    DATA_PATH,
    nrows=0,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

existing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col in header_df.columns
]

missing_numeric_cols = [
    col for col in continuous_numeric_cols
    if col not in header_df.columns
]

print("Existing numeric columns:")
print(existing_numeric_cols)

if missing_numeric_cols:
    print("\nColumns not found:")
    print(missing_numeric_cols)

# --------------------------------------------------
# 2. Read the file chunk by chunk
#    Store only numeric columns, then make one final summary
# --------------------------------------------------
numeric_chunks = []

total_rows = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    total_rows += len(chunk)

    # Convert selected columns to numeric
    numeric_chunk = chunk[existing_numeric_cols].apply(
        pd.to_numeric,
        errors="coerce"
    )

    numeric_chunks.append(numeric_chunk)

    print(f"Processed chunk {chunk_id} | Total rows processed: {total_rows:,}")

# --------------------------------------------------
# 3. Combine numeric chunks and create one final summary
# --------------------------------------------------
df_numeric_all = pd.concat(numeric_chunks, ignore_index=True)

numeric_summary = df_numeric_all.describe(
    percentiles=[0.25, 0.5, 0.75]
).T

numeric_summary = numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
].rename(columns={
    "count": "non_missing_count",
    "mean": "mean",
    "std": "std",
    "min": "min",
    "25%": "q1_25%",
    "50%": "median_50%",
    "75%": "q3_75%",
    "max": "max"
})

# Add missing counts
numeric_summary["missing_count"] = df_numeric_all.isna().sum()
numeric_summary["missing_percent"] = (
    df_numeric_all.isna().mean() * 100
).round(2)

# Reorder columns
numeric_summary = numeric_summary[
    [
        "non_missing_count",
        "missing_count",
        "missing_percent",
        "min",
        "q1_25%",
        "median_50%",
        "mean",
        "q3_75%",
        "max",
        "std"
    ]
]

# Optional: round values for readability
numeric_summary = numeric_summary.round(3)

print("\nTotal rows processed:", f"{total_rows:,}")
display(numeric_summary)

Existing numeric columns:
['loan_amount_000s', 'applicant_income_000s', 'population', 'minority_population', 'hud_median_family_income', 'tract_to_msamd_income', 'number_of_owner_occupied_units', 'number_of_1_to_4_family_units']
Processed chunk 1 | Total rows processed: 200,000
Processed chunk 2 | Total rows processed: 400,000
Processed chunk 3 | Total rows processed: 600,000
Processed chunk 4 | Total rows processed: 800,000
Processed chunk 5 | Total rows processed: 1,000,000
Processed chunk 6 | Total rows processed: 1,200,000
Processed chunk 7 | Total rows processed: 1,400,000
Processed chunk 8 | Total rows processed: 1,600,000
Processed chunk 9 | Total rows processed: 1,800,000
Processed chunk 10 | Total rows processed: 2,000,000
Processed chunk 11 | Total rows processed: 2,200,000
Processed chunk 12 | Total rows processed: 2,400,000
Processed chunk 13 | Total rows processed: 2,600,000
Processed chunk 14 | Total rows processed: 2,800,000
Processed chunk 15 | Total rows processed: 3,000,000
Processed chunk 16 | Total rows processed: 3,200,000
Processed chunk 17 | Total rows processed: 3,400,000
Processed chunk 18 | Total rows processed: 3,600,000
Processed chunk 19 | Total rows processed: 3,800,000
Processed chunk 20 | Total rows processed: 4,000,000
Processed chunk 21 | Total rows processed: 4,200,000
Processed chunk 22 | Total rows processed: 4,400,000
Processed chunk 23 | Total rows processed: 4,600,000
Processed chunk 24 | Total rows processed: 4,800,000
Processed chunk 25 | Total rows processed: 5,000,000
Processed chunk 26 | Total rows processed: 5,200,000
Processed chunk 27 | Total rows processed: 5,400,000
Processed chunk 28 | Total rows processed: 5,600,000
Processed chunk 29 | Total rows processed: 5,800,000
Processed chunk 30 | Total rows processed: 6,000,000
Processed chunk 31 | Total rows processed: 6,200,000
Processed chunk 32 | Total rows processed: 6,400,000
Processed chunk 33 | Total rows processed: 6,600,000
Processed chunk 34 | Total rows processed: 6,800,000
Processed chunk 35 | Total rows processed: 7,000,000
Processed chunk 36 | Total rows processed: 7,200,000
Processed chunk 37 | Total rows processed: 7,400,000
Processed chunk 38 | Total rows processed: 7,600,000
Processed chunk 39 | Total rows processed: 7,800,000
Processed chunk 40 | Total rows processed: 8,000,000
Processed chunk 41 | Total rows processed: 8,064,813

Total rows processed: 8,064,813

,non_missing_count,missing_count,missing_percent,min,q1_25%,median_50%,mean,q3_75%,max,std
loan_amount_000s,8064813.0,0,0.0,1.00,114.00,192.00,239.902,300.00,475000.00,638.130
applicant_income_000s,8064813.0,0,0.0,1.00,52.00,81.00,111.979,126.00,360000.00,408.575
population,8064813.0,0,0.0,30.00,3930.00,5250.00,5832.161,6884.00,53812.00,3249.660
minority_population,8064813.0,0,0.0,0.00,12.74,25.89,33.604,48.92,100.00,26.100
hud_median_family_income,8064813.0,0,0.0,18000.00,63200.00,69200.00,72567.704,79200.00,131500.00,14653.094
tract_to_msamd_income,8064813.0,0,0.0,3.71,86.52,109.03,114.717,135.94,507.47,42.396
number_of_owner_occupied_units,8064813.0,0,0.0,2.00,934.00,1343.00,1491.736,1844.00,19529.00,916.679
number_of_1_to_4_family_units,8064813.0,0,0.0,5.00,1324.00,1799.00,1993.253,2403.00,25391.00,1125.081

## Step 14: Create Final Samples for Modeling

This step creates two 500,000-row datasets. The classification sample keeps the same approval and rejection ratio as the full dataset, so it is stratified by `loan_approved`. The regression sample keeps only approved loans, because the regression target is loan amount for approved applications. Both samples are saved as CSV files for the next modeling stage.

In [13]:
import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# 0. File paths and settings
# =========================================================

# Change this path if your final cleaned dataset has another name
DATA_PATH = Path("hmda_2017_ready.csv")

CLASSIFICATION_OUTPUT_PATH = Path("hmda_classification_stratified_500k.csv")
REGRESSION_OUTPUT_PATH = Path("hmda_regression_approved_500k.csv")

CHUNK_SIZE = 200_000
RANDOM_STATE = 42

CLASSIFICATION_SAMPLE_SIZE = 500_000
REGRESSION_SAMPLE_SIZE = 500_000

TARGET_COL = "loan_approved"

# =========================================================
# 1. First pass: count target distribution in full dataset
# =========================================================

target_counts = {}
total_rows = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    if TARGET_COL not in chunk.columns:
        raise ValueError(f"Target column '{TARGET_COL}' not found in dataset.")

    chunk[TARGET_COL] = chunk[TARGET_COL].astype(str).str.strip()

    counts = chunk[TARGET_COL].value_counts(dropna=False)

    for key, value in counts.items():
        target_counts[key] = target_counts.get(key, 0) + int(value)

    total_rows += len(chunk)

    print(f"Counting pass | Chunk {chunk_id} | Rows counted: {total_rows:,}")

target_counts = pd.Series(target_counts).sort_index()

print("\nFull dataset target distribution:")
display(target_counts)

target_percent = (target_counts / target_counts.sum() * 100).round(2)

print("\nFull dataset target distribution percent:")
display(target_percent)

# =========================================================
# 2. Compute sample size per class for stratified classification sample
# =========================================================

if target_counts.sum() < CLASSIFICATION_SAMPLE_SIZE:
    raise ValueError("Classification sample size is larger than total dataset size.")

target_sample_sizes = (
    target_counts / target_counts.sum() * CLASSIFICATION_SAMPLE_SIZE
).round().astype(int)

# Fix possible rounding difference
rounding_diff = CLASSIFICATION_SAMPLE_SIZE - target_sample_sizes.sum()

if rounding_diff != 0:
    largest_class = target_counts.idxmax()
    target_sample_sizes.loc[largest_class] += rounding_diff

print("\nTarget sample sizes per class:")
display(target_sample_sizes)

if "1" not in target_counts.index:
    raise ValueError("No approved rows found: loan_approved = 1 does not exist.")

if target_counts.loc["1"] < REGRESSION_SAMPLE_SIZE:
    raise ValueError(
        f"Not enough approved rows. Available approved rows: {target_counts.loc['1']:,}"
    )

# =========================================================
# 3. Second pass: create stratified classification sample
# =========================================================

classification_samples = {
    class_label: pd.DataFrame()
    for class_label in target_sample_sizes.index
}

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    chunk[TARGET_COL] = chunk[TARGET_COL].astype(str).str.strip()

    for class_label, desired_n in target_sample_sizes.items():
        class_chunk = chunk[chunk[TARGET_COL] == class_label].copy()

        if len(class_chunk) == 0:
            continue

        classification_samples[class_label] = pd.concat(
            [classification_samples[class_label], class_chunk],
            ignore_index=True
        )

        if len(classification_samples[class_label]) > desired_n:
            classification_samples[class_label] = (
                classification_samples[class_label]
                .sample(
                    n=desired_n,
                    random_state=RANDOM_STATE + chunk_id + int(class_label)
                )
                .reset_index(drop=True)
            )

    print(
        f"Classification sampling pass | Chunk {chunk_id} | "
        + " | ".join([
            f"class {label}: {len(df):,}/{target_sample_sizes[label]:,}"
            for label, df in classification_samples.items()
        ])
    )

df_classification_sample = pd.concat(
    classification_samples.values(),
    ignore_index=True
)

df_classification_sample = df_classification_sample.sample(
    frac=1,
    random_state=RANDOM_STATE
).reset_index(drop=True)

df_classification_sample.to_csv(
    CLASSIFICATION_OUTPUT_PATH,
    index=False
)

print("\nClassification sample saved.")
print("Path:", CLASSIFICATION_OUTPUT_PATH.resolve())
print("Shape:", df_classification_sample.shape)

print("\nClassification sample target distribution:")
display(df_classification_sample[TARGET_COL].value_counts(dropna=False).sort_index())

print("\nClassification sample target distribution percent:")
display(
    (df_classification_sample[TARGET_COL].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

# =========================================================
# 4. Third pass: create approved-only regression sample
# =========================================================

regression_sample = pd.DataFrame()
approved_rows_seen = 0

for chunk_id, chunk in enumerate(
    pd.read_csv(
        DATA_PATH,
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        chunksize=CHUNK_SIZE
    ),
    start=1
):
    chunk[TARGET_COL] = chunk[TARGET_COL].astype(str).str.strip()

    approved_chunk = chunk[chunk[TARGET_COL] == "1"].copy()

    if len(approved_chunk) == 0:
        continue

    approved_rows_seen += len(approved_chunk)

    regression_sample = pd.concat(
        [regression_sample, approved_chunk],
        ignore_index=True
    )

    if len(regression_sample) > REGRESSION_SAMPLE_SIZE:
        regression_sample = (
            regression_sample
            .sample(
                n=REGRESSION_SAMPLE_SIZE,
                random_state=RANDOM_STATE + chunk_id
            )
            .reset_index(drop=True)
        )

    print(
        f"Regression sampling pass | Chunk {chunk_id} | "
        f"Approved rows seen: {approved_rows_seen:,} | "
        f"Current regression sample size: {len(regression_sample):,}"
    )

regression_sample = regression_sample.sample(
    frac=1,
    random_state=RANDOM_STATE
).reset_index(drop=True)

regression_sample.to_csv(
    REGRESSION_OUTPUT_PATH,
    index=False
)

print("\nRegression approved-only sample saved.")
print("Path:", REGRESSION_OUTPUT_PATH.resolve())
print("Shape:", regression_sample.shape)

print("\nRegression sample loan_approved distribution:")
display(regression_sample[TARGET_COL].value_counts(dropna=False).sort_index())

# =========================================================
# 5. Final checks
# =========================================================

df_cls_check = pd.read_csv(
    CLASSIFICATION_OUTPUT_PATH,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

df_reg_check = pd.read_csv(
    REGRESSION_OUTPUT_PATH,
    dtype=str,
    keep_default_na=False,
    na_filter=False
)

print("\nFinal check - Classification sample shape:")
print(df_cls_check.shape)

print("\nFinal check - Classification target distribution:")
display(df_cls_check[TARGET_COL].value_counts(dropna=False).sort_index())

print("\nFinal check - Classification target distribution percent:")
display(
    (df_cls_check[TARGET_COL].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

print("\nFinal check - Regression sample shape:")
print(df_reg_check.shape)

print("\nFinal check - Regression target distribution:")
display(df_reg_check[TARGET_COL].value_counts(dropna=False).sort_index())

Counting pass | Chunk 1 | Rows counted: 200,000
Counting pass | Chunk 2 | Rows counted: 400,000
Counting pass | Chunk 3 | Rows counted: 600,000
Counting pass | Chunk 4 | Rows counted: 800,000
Counting pass | Chunk 5 | Rows counted: 1,000,000
Counting pass | Chunk 6 | Rows counted: 1,200,000
Counting pass | Chunk 7 | Rows counted: 1,400,000
Counting pass | Chunk 8 | Rows counted: 1,600,000
Counting pass | Chunk 9 | Rows counted: 1,800,000
Counting pass | Chunk 10 | Rows counted: 2,000,000
Counting pass | Chunk 11 | Rows counted: 2,200,000
Counting pass | Chunk 12 | Rows counted: 2,400,000
Counting pass | Chunk 13 | Rows counted: 2,600,000
Counting pass | Chunk 14 | Rows counted: 2,800,000
Counting pass | Chunk 15 | Rows counted: 3,000,000
Counting pass | Chunk 16 | Rows counted: 3,200,000
Counting pass | Chunk 17 | Rows counted: 3,400,000
Counting pass | Chunk 18 | Rows counted: 3,600,000
Counting pass | Chunk 19 | Rows counted: 3,800,000
Counting pass | Chunk 20 | Rows counted: 4,000,000
Counting pass | Chunk 21 | Rows counted: 4,200,000
Counting pass | Chunk 22 | Rows counted: 4,400,000
Counting pass | Chunk 23 | Rows counted: 4,600,000
Counting pass | Chunk 24 | Rows counted: 4,800,000
Counting pass | Chunk 25 | Rows counted: 5,000,000
Counting pass | Chunk 26 | Rows counted: 5,200,000
Counting pass | Chunk 27 | Rows counted: 5,400,000
Counting pass | Chunk 28 | Rows counted: 5,600,000
Counting pass | Chunk 29 | Rows counted: 5,800,000
Counting pass | Chunk 30 | Rows counted: 6,000,000
Counting pass | Chunk 31 | Rows counted: 6,200,000
Counting pass | Chunk 32 | Rows counted: 6,400,000
Counting pass | Chunk 33 | Rows counted: 6,600,000
Counting pass | Chunk 34 | Rows counted: 6,800,000
Counting pass | Chunk 35 | Rows counted: 7,000,000
Counting pass | Chunk 36 | Rows counted: 7,200,000
Counting pass | Chunk 37 | Rows counted: 7,400,000
Counting pass | Chunk 38 | Rows counted: 7,600,000
Counting pass | Chunk 39 | Rows counted: 7,800,000
Counting pass | Chunk 40 | Rows counted: 8,000,000
Counting pass | Chunk 41 | Rows counted: 8,064,813

Full dataset target distribution:

0    1593183
1    6471630
dtype: int64

Full dataset target distribution percent:

0    19.75
1    80.25
dtype: float64

Target sample sizes per class:

0     98774
1    401226
dtype: int64

Classification sampling pass | Chunk 1 | class 0: 60,527/98,774 | class 1: 139,473/401,226
Classification sampling pass | Chunk 2 | class 0: 98,774/98,774 | class 1: 282,920/401,226
Classification sampling pass | Chunk 3 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 4 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 5 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 6 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 7 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 8 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 9 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 10 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 11 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 12 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 13 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 14 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 15 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 16 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 17 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 18 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 19 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 20 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 21 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 22 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 23 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 24 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 25 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 26 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 27 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 28 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 29 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 30 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 31 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 32 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 33 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 34 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 35 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 36 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 37 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 38 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 39 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 40 | class 0: 98,774/98,774 | class 1: 401,226/401,226
Classification sampling pass | Chunk 41 | class 0: 98,774/98,774 | class 1: 401,226/401,226

Classification sample saved.
Path: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_classification_stratified_500k.csv
Shape: (500000, 29)

Classification sample target distribution:

loan_approved
0     98774
1    401226
Name: count, dtype: int64

Classification sample target distribution percent:

loan_approved
0    19.75
1    80.25
Name: proportion, dtype: float64

Regression sampling pass | Chunk 1 | Approved rows seen: 139,473 | Current regression sample size: 139,473
Regression sampling pass | Chunk 2 | Approved rows seen: 282,920 | Current regression sample size: 282,920
Regression sampling pass | Chunk 3 | Approved rows seen: 433,351 | Current regression sample size: 433,351
Regression sampling pass | Chunk 4 | Approved rows seen: 587,391 | Current regression sample size: 500,000
Regression sampling pass | Chunk 5 | Approved rows seen: 747,261 | Current regression sample size: 500,000
Regression sampling pass | Chunk 6 | Approved rows seen: 913,896 | Current regression sample size: 500,000
Regression sampling pass | Chunk 7 | Approved rows seen: 1,075,579 | Current regression sample size: 500,000
Regression sampling pass | Chunk 8 | Approved rows seen: 1,233,949 | Current regression sample size: 500,000
Regression sampling pass | Chunk 9 | Approved rows seen: 1,392,826 | Current regression sample size: 500,000
Regression sampling pass | Chunk 10 | Approved rows seen: 1,557,127 | Current regression sample size: 500,000
Regression sampling pass | Chunk 11 | Approved rows seen: 1,724,454 | Current regression sample size: 500,000
Regression sampling pass | Chunk 12 | Approved rows seen: 1,887,695 | Current regression sample size: 500,000
Regression sampling pass | Chunk 13 | Approved rows seen: 2,048,041 | Current regression sample size: 500,000
Regression sampling pass | Chunk 14 | Approved rows seen: 2,209,875 | Current regression sample size: 500,000
Regression sampling pass | Chunk 15 | Approved rows seen: 2,375,041 | Current regression sample size: 500,000
Regression sampling pass | Chunk 16 | Approved rows seen: 2,539,365 | Current regression sample size: 500,000
Regression sampling pass | Chunk 17 | Approved rows seen: 2,708,159 | Current regression sample size: 500,000
Regression sampling pass | Chunk 18 | Approved rows seen: 2,874,582 | Current regression sample size: 500,000
Regression sampling pass | Chunk 19 | Approved rows seen: 3,040,066 | Current regression sample size: 500,000
Regression sampling pass | Chunk 20 | Approved rows seen: 3,206,989 | Current regression sample size: 500,000
Regression sampling pass | Chunk 21 | Approved rows seen: 3,373,912 | Current regression sample size: 500,000
Regression sampling pass | Chunk 22 | Approved rows seen: 3,538,782 | Current regression sample size: 500,000
Regression sampling pass | Chunk 23 | Approved rows seen: 3,709,577 | Current regression sample size: 500,000
Regression sampling pass | Chunk 24 | Approved rows seen: 3,880,702 | Current regression sample size: 500,000
Regression sampling pass | Chunk 25 | Approved rows seen: 4,052,005 | Current regression sample size: 500,000
Regression sampling pass | Chunk 26 | Approved rows seen: 4,223,149 | Current regression sample size: 500,000
Regression sampling pass | Chunk 27 | Approved rows seen: 4,395,839 | Current regression sample size: 500,000
Regression sampling pass | Chunk 28 | Approved rows seen: 4,563,823 | Current regression sample size: 500,000
Regression sampling pass | Chunk 29 | Approved rows seen: 4,728,811 | Current regression sample size: 500,000
Regression sampling pass | Chunk 30 | Approved rows seen: 4,895,485 | Current regression sample size: 500,000
Regression sampling pass | Chunk 31 | Approved rows seen: 5,062,384 | Current regression sample size: 500,000
Regression sampling pass | Chunk 32 | Approved rows seen: 5,228,685 | Current regression sample size: 500,000
Regression sampling pass | Chunk 33 | Approved rows seen: 5,375,670 | Current regression sample size: 500,000
Regression sampling pass | Chunk 34 | Approved rows seen: 5,535,704 | Current regression sample size: 500,000
Regression sampling pass | Chunk 35 | Approved rows seen: 5,691,655 | Current regression sample size: 500,000
Regression sampling pass | Chunk 36 | Approved rows seen: 5,841,008 | Current regression sample size: 500,000
Regression sampling pass | Chunk 37 | Approved rows seen: 5,998,420 | Current regression sample size: 500,000
Regression sampling pass | Chunk 38 | Approved rows seen: 6,139,573 | Current regression sample size: 500,000
Regression sampling pass | Chunk 39 | Approved rows seen: 6,281,379 | Current regression sample size: 500,000
Regression sampling pass | Chunk 40 | Approved rows seen: 6,425,070 | Current regression sample size: 500,000
Regression sampling pass | Chunk 41 | Approved rows seen: 6,471,630 | Current regression sample size: 500,000

Regression approved-only sample saved.
Path: D:\SHARIF\TERM7\DATA\PROJECT\main\hmda_regression_approved_500k.csv
Shape: (500000, 29)

Regression sample loan_approved distribution:

loan_approved
1    500000
Name: count, dtype: int64

Final check - Classification sample shape:
(500000, 29)

Final check - Classification target distribution:

loan_approved
0     98774
1    401226
Name: count, dtype: int64

Final check - Classification target distribution percent:

loan_approved
0    19.75
1    80.25
Name: proportion, dtype: float64

Final check - Regression sample shape:
(500000, 29)

Final check - Regression target distribution:

loan_approved
1    500000
Name: count, dtype: int64